### ISSUE TITLE
Why is the content stored in a file?

### ISSUE THREAD

**Issue by royduin** [rainlab/pages-plugin#100]
OctoberCMS stores almost everything in files, but why content? Content should be in a database. I thought this plugin uses the database, but neither. OctoberCMS is for developers but as developer I don't want any file changes when content changes. Then I've to commit content changes from my clients on a production environment? Or do I've to ignore all the `/content/static-pages` and the `/meta` directories in themes? I don't think so. Am I missing something or do I not see the advantages?

**Comment by gavinfostered** [comment]
Got to admit I found this strange too coming from almost any other CMS out there. I'd say there are a few  awesome advantages using flat files. 

One is speed. Not having several database calls to piece together the page content dramatically improves load time. The server only has to fetch a flat file after all.

It's also a DRY approach. Being able to programatically inject scripts and styles on a per page basis and other cool tricks means you can keep layouts to a minimum and re-use stuff more readily. 

As far as work flow goes, it's now actually much easier. I do just as you suggested and ignore static-pages and meta directories. When it comes to production I can just push them up with FTP. With other CMS's I'd have to mess around with dumping and importing databases just to make sure I've got all the client's changes. OctoberCMS (at least as far as the bulk of content goes) this is largely eliminated.

If you make use of "Projects" in your OctoberCMS account, deployment is literally a walk in the park. The only thing in my git repo is my theme (minus static pages). OctoberCMS takes care of everything else like build and plugin updates through the backend.

In recent months there's been a huge rise in popularity of "static-site generators"; jekkyl, hugo, wintersmith to name just a few. Seems that developers are tired of hacking around "popular" CMS platforms to build simple, fast, sites. I believe OctoberCMS leverages the advantages of using a static-site generator while retaining all dynamic features of an Enterprise grade CMS.

It is a very different approach to what we're used to, but if you stick with it and explore further you'll see that it ultimately streamlines your work flow, saves you time and headaches and makes things super-fast. And don't get me started on plugins and components. Wrote a plugin for a client in 56 minutes! Not possible with most the others.

**Comment by royduin** [comment]
Thank you for your clarifying answer! I now see the advantages of it and I'm going to play further with it. But before I'll use it for a client I need some more answers, so far:

- https://github.com/rainlab/pages-plugin/issues/32
- https://github.com/octobercms/october/issues/1513

**Comment by pedzed** [comment]
I feel that I am in the same boat. The main problem I have is loading a variable amount of content. If it came from the database, you would just loop through the data, but you can't really do that for the content files.

**Comment by daftspunk** [comment]
It would be possible for someone to port this plugin across to store the content in a database instead. That is the beauty of plugins, if you prefer a different way then you are free to do it as your own plugin!

**Comment by eugenbg** [comment]
what if there is 50k pages? will this work with the file approach?

**Comment by daftspunk** [comment]
> what if there is 50k pages? will this work with the file approach?

October CMS uses a URL route cache so 50k pages are manageable.
