### ISSUE TITLE
Static page url

### ISSUE THREAD

**Issue by webmaxx** [rainlab/pages-plugin#101]
Now there is no way to create a URL address in the format: `/page_name.html`. Only `/page_name`.

Please, add character '.' to `RainLab\Pages\Classes\Page::viewBagValidationRules['url']`.

P.S. Sorry my English.

**Comment by webmaxx** [comment]
I created pull request: https://github.com/rainlab/pages-plugin/pull/107

**Comment by gavinfostered** [comment]
Don't think this will get in Webmaxx... there's no good reason why you should want to add .html. Is there something you're trying to achieve by having this available?

**Comment by webmaxx** [comment]
There are several projects with such url, which must be transferred to october cms.
Required to maintain them.

**Comment by gavinfostered** [comment]
Ah ok. I still don't think it'll happen. If you are worried about search engine's you could always very easily 301 redirect any indexed links using .htaccess or similar. That's what I'd do :)

**Comment by webmaxx** [comment]
It is not SEO. It is the customer's requirements.

**Comment by oleg90990** [comment]
Hello!
Very often I use your plugin. And I have the same problem as the author of this topic. Please correct it and I will be very grateful to you.

P.S. Sorry. I know English bad.

**Comment by daftspunk** [comment]
Fixed by #107
