### ISSUE TITLE
Select multiple images on Syntax Field

### ISSUE THREAD

**Issue by nathanjdunn** [rainlab/pages-plugin#102]
Hi, 

Just been having a play around with the Pages Plugin for a website I am creating. I was thinking about  utilising an image slider on each page of the site and allowing the user to pick their own images using a custom page field (Syntax Field). I am currently using the following code in my theme: 

`{variable name="banner" label="Banner" tab="Header" type="mediafinder" mode="image"}{/variable}`

This works well for selecting a single image for the CMS but does not allow me to add multiple images in the same field, which would be ideal for an on-page slider. Is there a parameter I could set to upload multiple images? If not, it would be nice to have this sort of syntax for multiple uploads: 

`{variable name="banner" label="Banner" tab="Header" type="mediafinder" mode="image" multiple="true"}{/variable}`

If has an answer for this, it would be greatly appreciated.

Many thanks,
Nathan
##

**Comment by jwilson8767** [comment]
Nathan, currently this sort of functionality is not available directly in the pages plugin. However, you could conceivably create a snippet(component) which provides this functionality. Alternatively you could use a plugin like [the Bootstrap Carousel plugin](https://octobercms.com/plugin/mohsin-carousel) but register it as a snippet.

**Comment by gavinfostered** [comment]
If it's just images in your slider Nathan, you could always inject a bit of PHP to pull out images inside a specific folder. In the "code" section of your layout you could do this (where 'slider-images' is the name of your media folder that holds your slides):

```
function onStart()
{
    $this['slides'] = MediaLibrary::instance()->listFolderContents($folder = 'slider-images');
}
```

Then in your layout markup, iterate through the `slides` array like this...

```
{% for key,val in slides %}
    <li><img src="{{ val.publicUrl }}" alt=""></li>
{% endfor %}
```

Quick and simple; if you wanted more control then jwilson8767's suggestion would be the way to go. Writing your own plugin is super-simple to do with OctoberCMS by the way :)

**Comment by jacobalvarez** [comment]
I implemented @gavinworks solution, but it would be more client-friendly to have the functionality built in to the mediafinder.  Telling the client to put the images in a specific directory is not good.

**Comment by LukeTowers** [comment]
Support for multiple images selected with the MediaFinder will be implemented here: https://github.com/octobercms/october/issues/1658. Until then, use a repeater and mediafinder combination.

**Comment by robinbonnes** [comment]
+1 For this.

Normally I can solve this with a repeater:
```
{repeater tab="Images" name="images" prompt="Add image"}
    {variable type="mediafinder" mode="image" name="image" label="Image" commentAbove="Some image."}{/variable}
{/repeater}
```
But this is not working when I need to add images for multiple repeater items (Repeater in repeater not supported?):

```
{repeater tab="Portfolio" name="portfolio" prompt="Add portfolio section."}
    {variable type="text" name="title" label="Section title" commentAbove="For example: Website development."}{/variable}
    {repeater tab="Images" name="images" prompt="Add image to this section."}
        {variable type="mediafinder" mode="image" name="image" label="Image"}{/variable}
    {/repeater}
{/repeater}
```
If some kind of 'multiple=true' option will be implemented, I could solve this as following:
```
{repeater tab="Portfolio" name="portfolio" prompt="Add portfolio section."}
    {variable type="text" name="title" label="Section title" commentAbove="For example: Website development."}{/variable}
    {variable type="mediafinder" mode="image" name="images" multiple="true" label="Image"}{/variable}
{/repeater}
```
Then access the images for example like this:
```
{% for section in portfolio %}
<div class="section">
    <h1 class="section-title">{{ section.title }}</h1>
    <div class="section-images">
        {% for image in section.images %}
        <img src="{{ image|media }}" />
        {% endfor %}
    </div>
</div>
{% endfor %}
```

**Comment by LukeTowers** [comment]
@robinbonnes that's the plan. In regards to repeaters in repeaters with syntax fields, I believe that is a reported issue.
