### ISSUE TITLE
Showing certain menu items to authenticated users only

### ISSUE THREAD

**Issue by msimkunas** [rainlab/pages-plugin#103]
Is it possible to change the visibility of some menu items so that they are only shown to authenticated users (using the RainLab Users plugin)?
##

**Comment by reidblomquist** [comment]
@msimkunas I haven't dug very deep into either of these (just started playing with October) but it would seem that you should be able to loop through your StaticMenu items and declare those elements availability on a per-item basis, but it may take some work to add an attribute to static menu items to filter on.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
