### ISSUE TITLE
static page

### ISSUE THREAD

**Issue by kodermax** [rainlab/pages-plugin#104]
Why doesn't work this on the pages?

```
<img src="{{'assets/images/slider/image_01.jpg' | theme}}" />
```
##

**Comment by jwilson8767** [comment]
The pages are **static** pages, meaning they are not evaluated for twig tags.

**Comment by gavinfostered** [comment]
Might be worth mentioning, if you don't already know, that static pages can automatically populate variables if you declare them in the page layout your static page is using. They're called Syntax Variables. You can read more here: https://octobercms.com/blog/post/building-client-friendly-websites

Let's say if you want to give your user/client the ability to add 3 slides to the page and your static page uses a layout called "home". In your home layout declare the variables like below. You can put them anywhere but I put them right before the closing body tag

```
{variable tab="Slider Images" commentAbove="Minimum width 950px" type="mediafinder" mode="image" name="SliderImage1" label="Choose the First Slider Image"}{/variable}

{variable tab="Slider Images" commentAbove="Minimum width 950px" type="mediafinder" mode="image" name="SliderImage2" label="Choose the Secpmd Slider Image"}{/variable}

{variable tab="Slider Images" commentAbove="Minimum width 950px" type="mediafinder" mode="image" name="SliderImage3" label="Choose the Third Slider Image"}{/variable}
```

That's it, whenever you go to the page that uses the "home" layout, you'll have an extra tab to add in your slider images. You can use the values set there in your layout like any other twig variable just by using `{{ SliderImage1 }}` etc.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
