### ISSUE TITLE
variable definitions in layout code block

### ISSUE THREAD

**Issue by jwilson8767** [rainlab/pages-plugin#111]
Rather than using the parser service to pull variables from the markup of the layout, why not just provide a method on the layout that returns a property definition list in the same way that components do?

I think this would also allow the properties to be loaded earlier in the page life cycle as well allowing mediafinders, fileuploads, and other formwidgets to work as well.

BONUS: this would eliminate the need for pages plugin specific documentation on how to use variables!

Example:

```
//mylayout.htm
==
function defineProperties()
    {
        return [
            'code' => [
                'title'       => 'Menu',
                'description' => 'Specify a code of the menu the page should output',
                'type'        => 'dropdown'
            ]
        ];
    }
==
//layout content

```

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
