### ISSUE TITLE
Saving page doesn't save changes made in code view

### ISSUE THREAD

**Issue by ixperiencenl** [rainlab/pages-plugin#112]
Then trying to save my changes I've made in the code view instead of the wysiwyg view, the changes aren't saved. When I switch back to wysiwyg and I press the save button, it ís saved.

**Comment by jacobalvarez** [comment]
[Related issue](https://github.com/octobercms/october/issues/1627#issuecomment-169416494)

**Comment by daftspunk** [comment]
Duplicate issue in the main repo
This will be fixed by https://github.com/octobercms/october/issues/2005
