### ISSUE TITLE
Fire event on Save

### ISSUE THREAD

**Issue by that0n3guy** [rainlab/pages-plugin#12]
It would be nice if there were some events that fired.  I need one on save (save menu, page, etc..).
##

**Comment by daftspunk** [comment]
To propose a new event please provide supporting material on why you need it.

**Comment by grohman** [comment]
i'm building search engine and i need to get page content after successful save. Probably not possible without event. Or there is another way?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
