### ISSUE TITLE
Variable in repeater doesn't work

### ISSUE THREAD

**Issue by surahmans** [rainlab/pages-plugin#121]
Hi, 
I have some case about repeater. I have tried to create variable in repeater but it doesn't work.

Here's my code,

```
             {repeater name="banner_sections" tab="Table" prompt="Add more item"} 
              <tr>
                <td>{text name="kind" label="Title" tab="Table"}Weekdays{/text}</td>
                <td>{text name="item" label="Item" tab="Table"}Eclair{/text}</td>
                {variable type="textarea"  name="price" label="Price" tab="Table"}$0.87{/variable}
               <td>{{ price|nl2br }}</td>
              </tr>
             {/repeater}
```

When I access the page in fron end, the price section is not appear. But, it works in backend. When I using variable outside repeater, it working correctly. Is impossible to create a variable in repeater?

Thanks
##

**Comment by FelixINX** [comment]
> Note: The repeater field type is currently unsupported, however we hope to change this in the future.

From documentation

**Comment by surahmans** [comment]
The repeater field has been fixed in this commit,
https://github.com/rainlab/pages-plugin/commit/34dcf5e9ef04812854a0426c21d03454a755c523

**Comment by FelixINX** [comment]
I'm not sure if it is complete. Because the message (Note: The repeater field type is currently unsupported, however we hope to change this in the future.) is also there. I have not played around with this, so I will try soon.

**Comment by surahmans** [comment]
It's work right now. But, for variable in repeater I think still not work.

**Comment by JellevanMil** [comment]
The repeater field is supported since static pages version 1.1.11 (which is the latest on this github page), however the current version on the octobercms site and system is 1.1.10.

For outputting a variable inside a repeater you should use ` {{ fields.variableName }}` so in your case `{{ fields.price | nl2br }}`, see this documentation: https://github.com/octobercms/library/blob/master/src/Parse/Syntax/README.md

Which says a repeater renders in twig as:
```
{% for fields in repeater %}
    <h2>{{ fields.title }}</h2>
    <p>{{ fields.content|raw }}</p>
{% endfor %}
```

**Comment by LukeTowers** [comment]
Fixed by https://github.com/rainlab/pages-plugin/commit/34dcf5e9ef04812854a0426c21d03454a755c523
