### ISSUE TITLE
Can't link CMS Page when menu type is "All Blog Categories"

### ISSUE THREAD

**Issue by lincolnbrito** [rainlab/pages-plugin#122]
I'm following the [tutorial on blog](http://octobercms.com/blog/post/getting-started-static-pages), but when try to select the "CMS Page" the page is not listed.

![capturar](https://cloud.githubusercontent.com/assets/310896/12106536/5fd54204-b33f-11e5-887f-3e34b15e3377.PNG)

On console, the script ***storm-min.js?v313*** has the error:

![capturar2](https://cloud.githubusercontent.com/assets/310896/12106703/e56070d2-b340-11e5-86bc-1aa0b30dad4a.PNG)

**Comment by pcampbell-software** [comment]
I also get this issue, although I can see no JS errors in my console. It simply just doesn't show any available CMS pages for some reason. I have this issue for both the "All categories" and single category menu type options (i.e.: it's only an issue for blog-related menu items for some reason).

**Comment by daftspunk** [comment]
It will only show CMS pages that use the blog category component on there. Try installing RainLab.Vanilla theme for another example. It should be working here:

https://github.com/rainlab/vanilla-theme

**Comment by pcampbell-software** [comment]
> It will only show CMS pages that use the blog category component on there. Try installing RainLab.Vanilla theme for another example. It should be working here:

https://github.com/rainlab/vanilla-theme

Thank you, but the sample given does not appear to have a static menu with which to compare. I have ensured that the page I am trying to link to contains the categories component, as so:

<img width="521" alt="screen shot 2016-07-03 at 12 13 26 pm" src="https://cloud.githubusercontent.com/assets/17199516/16543734/b1a94bc8-4117-11e6-8afb-b3c9ee2d9071.png">

**Comment by daftspunk** [comment]
1. Installed RainLab.Vanilla theme
1. Created new menu
1. Added new menu item
1. Selected Type: All Blog Categories

![screenshot 2016-07-03 14 21 30](https://cloud.githubusercontent.com/assets/1392869/16543742/7a1bb53a-4129-11e6-9d32-b939f6ca637d.png)

**Comment by amdad** [comment]
Slug must be property. So with brackets {{ :slug }}. It's required.

**Comment by MiguelDebruyne** [comment]
Why is it that a single blog item page is the only one in the CMS Page dropdown which you can select when type is set to 'all blog posts'? Shouldn't that page be the blog overview page since that is the page where all the blog posts are shown? I'm confused
