### ISSUE TITLE
Use subdomain to render some pages

### ISSUE THREAD

**Issue by Kabangi** [rainlab/pages-plugin#123]
Is it possible to have some urls being rendered on a subdomain for the static pages

I would appreciate if such functionality was available instead of relying on the root domain.

Thanks

**Comment by FelixINX** [comment]
I will take a look at this. I am planning to realease a SP-Subdomain plugins, that will extend StaticPage plugin.

**Comment by Kabangi** [comment]
Thanks. Meanwhile I will go through the plugin and see if there is something I can do to achieve that

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
