### ISSUE TITLE
Can not enter UTF-8 characters in the URL

### ISSUE THREAD

**Issue by palamike** [rainlab/pages-plugin#125]
Hi, 

I try to input the UTF-8 in the URL but it shows the following error 

Invalid URL format. The URL should start with the forward slash symbol and can contain digits, Latin letters and the following symbols: _-/

The UTF-8 URL will affect the SEO. 

Could you please fix that...

**Comment by sajjad-ser** [comment]
+1

**Comment by LukeTowers** [comment]
Fixed in Laravel 5.5 (Build 420+) See https://github.com/octobercms/library/pull/178#issuecomment-302836370
