### ISSUE TITLE
Strange error adding new or entering pages 

### ISSUE THREAD

**Issue by Hessel91** [rainlab/pages-plugin#127]
I'm struggling with this strange error. 
After I moved my files from localhost to the liveserver the Pages > "Pages" tab gives me an error: 

"form method="POST" action="http://digenezimmerman.com/site/backend/rainlab/pages" accept-charset="UTF-8" class="layout" data-change-monitor="true" data-window-close-confirm="Do you really want to close the tab? Unsaved changes will be lost." data-object-type="page"><input name="_token" type="hidden" value="tCNtiDtoc7GirXAbckGZA33c8uaryCY8ytl62I79"><input name="_session_key" type="hidden" value="qMSDeUszwhEs4fsf3kJfkOTjPXj3N0DtmutVHpRN"   "Undefined index: type" on line 402 of /var/www/vhosts/digenezimmerman.com/httpdocs/site/plugins/rainlab/pages/controllers/Index.php"

It appaers when I try to create a new static page or edit the existing static "home page" on the pages tab, the menu's snippets etc work correct. I tried to re-install the pluggin but that didn't worked either. 

 Is there anyone who knows more about this issue?

Regards, 

Hessel

**Comment by Hessel91** [comment]
this is the log.file

[error.txt](https://github.com/rainlab/pages-plugin/files/92042/error.txt)

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
