### ISSUE TITLE
[Feature Request] - Placeholders with type image/select

### ISSUE THREAD

**Issue by ghost** [rainlab/pages-plugin#13]
Love the idea of placeholders in the system, and I am sure you are planning to add more types but 2 types I am really in need of at the moment is the ability to set an image placeholder and a select so I am able to set icons for pages etc.

1 way that MODX did selects was to have an input of "name==value||name==value" for the multiple options. Just a thought.

**Comment by JelleNL** [comment]
Would also very appreciate this feature!

**Comment by axomat** [comment]
I am making a lot of use of placeholders and could really do with these two features as well, they are good ideas.

I also need more features in the placeholder editor which is really very basic (no padding on table cells for example is particularly annoying) and the wysiwyg plugin does not affect placeholders.

**Comment by jayalfredprufrock** [comment]
I've been experimenting with placeholders and snippets a lot as well. I think more flexibility could be achieved with a few more snippet field types as opposed to adding the concept of field types to the placeholder feature. In particular, a snippet field type for embedding another snippet would be the ultimate! I'd be curious to hear the feasibility / performance considerations of such an approach.

**Comment by ar7n** [comment]
This will be useful feature

**Comment by JurekRaben** [comment]
+1

**Comment by clone45** [comment]
I would really love to see this feature.  I would like to allow my clients to create marketing landing pages built on a layout.  The Static Pages functionality is so close that I can taste it, but the inability to swap out images gracefully is a show-stopper.

**Comment by ar7n** [comment]
@clone45 this feature already has been added http://octobercms.com/blog/post/building-client-friendly-websites

**Comment by daftspunk** [comment]
Fixed by the media finder custom page field

```
{variable name="banner" label="Banner" tab="Header" type="mediafinder" mode="image"}{/variable}
```
