### ISSUE TITLE
Sensitivity drag&drap in page tree

### ISSUE THREAD

**Issue by abelschooleman** [rainlab/pages-plugin#130]
The drag&drop feature in the page tree is kind of clunky. This has resulted in some occasions in which my editors unintentionally messed up the page structure when they try to put a new page in place.
Is there any chance this will be improved in the future?

**Comment by robinbonnes** [comment]
Indeed, you can't move pages out of their parent within the menu tab.

**Comment by robinbonnes** [comment]
The only way I could find is pin the menu, then drag drop the page, out between the pages outside the pages tab.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
