### ISSUE TITLE
Snippet - Richeditor type option [Bounty]

### ISSUE THREAD

**Issue by mightyhaggis** [rainlab/pages-plugin#132]
Currently the type options are String, Checkbox & Dropdown.
Can a Richeditor option be added and handling of HTML/ markdown code? Not sure whether this links with Inspector or is handled within **pages** 
In-line preview rather than a place holder would be amazing.

Snippets using Richeditor would give **pages** advanced content building blocks capabilities adding to an already impressive plugin and CMS

Thanks

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=30143000)](https://www.bountysource.com/issues/30143000-snippet-richeditor-type-option?utm_source=30143000&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by mightyhaggis** [comment]
Modifying the plugin slightly I have enabled a Text editor option, but looking further it does not appear that Inspector 2.0 supports the editors: richeditor or markdown. So that I was hoping for does not appear to be achievable at the moment ?

**Comment by koorb** [comment]
+1. Also a media browser type. This would let clients build up pages of complex styled blocks.

**Comment by daftspunk** [comment]
I'm failing to see why anyone would need this. Can you give a real world example?

**Comment by koorb** [comment]
There are some plugins to Wordpress (such as http://www.layerswp.com) that allow users to build pages using pre designed widgets or components. What I'd be hoping for is the ability to code components, say sliders, callouts, quotes, video players, image gallery, etc. etc. Then specify content areas, much like the properties on snippets.

The end result then being components a user can drag on to a page so they can build up more complex pages. 

Does that make any sense? Seems like snippets are almost there, just need to allow the user to input more rich content for the components.

**Comment by daftspunk** [comment]
@koorb There is a bounty on this issue, please submit another issue rather than hijack this one.

@mightyhaggis Please can you describe why someone would need a "RichEditor" snippet field, whilst inside a rich editor?

**Comment by mightyhaggis** [comment]
@daftspunk My thoughts behind this are that I would be able to create a snippets of pre-designed/ formatted code that would then allow for the editor to insert the snippet fill in the specified inputs including Rich Editor and more if possible (imgs..), allowing for complex building blocks of site content to be designed for later usage with simple box filling content input. Yet maintaining the look and feel of the site without the need of the Editor to edit code and increasing what and editor can achieve with minimum effort.

**Comment by daftspunk** [comment]
The @koorb solution makes sense. The Rich Editor is a bit confusing. So far we have described snippets, it is a powerful concept, this is already known. 

I need to know a real world example where you would need a WYSIWYG inside a WYSIWYG? It makes not much sense.

**Comment by daftspunk** [comment]
It's difficult to discuss a solution without first understanding the problem. Please, explain the problem itself and not the solution that you have in mind. For more info on presenting your problem see !help. Thanks! Also see http://mywiki.wooledge.org/XyProblem

**Comment by mightyhaggis** [comment]
@daftspunk By this I meant text formatting, bold, headlines... Markdown I guess.
I agree there is no requirement for WYSIWYG.

**Comment by mightyhaggis** [comment]
@koorb has detailed what I am looking for, expansion on snippets capabilities.

I'd like to be able to define snippets such as callouts, quotes etc.. that when added to the page allows population of the predefined fields one of which has the capability of text formatting so I can bold, highlights, italics... apply a pre-defined css class... markdown..
My use of the term Rich Editor has cause the confusion, I agree WYSIWYG is not required.

Building on this to have media capabilities such as selecting/ uploading an image.. In-line rendering of the snippet rather than a place holder, would be amazingly useful.

**Comment by daftspunk** [comment]
Alright, this is making more sense now. This would require improvements to the inspector control itself, since this is what drives the snippet properties. There are several improvements already made to Inspector with the [rebuild that recently occurred](http://octobercms.com/blog/post/inspector-2). There is none that include a media picker option.

This issue #132 in it's current state lacks a clear definition about what needs to be added. Note each new inspector type is a large piece of work and should have it's own issue respectively. So can we clarify these as the requirements:

* Add a media manager inspector type
* Make the new inspector types available to the snippet definition table (where possible)

Will this satisfy the bounty?

**Comment by mightyhaggis** [comment]
@daftspunk Looking at the list of new inspector types [http://octobercms.com/blog/post/inspector-2](url) I see "Text editor" so assuming this has Markdown capabilities as discussed above..

- Adding a media manager inspector type
- Adding new inspector types (where possible) but defiantly a Markdown capable one...

Will satisfy the bounty, I appreciate the work involved so assuming we agree on the above I will add another $25 to bounty.

**Comment by daftspunk** [comment]
There is a bit of a problem with allowing multi line or HTML contents as the snippet property, essentially because the output looks like this:

```
<figure snippet-property="value" />
```

It could lead to corruption and generally poor looking markup. The only solution I can think of in this instance would be to reference a content file:

```
<figure snippet-markup="content.htm" />
```

I assume this isn't the type of UX you are going for, yet, I am still yet to hear your exact usage scenario or real world example. At this point the bounty cannot be satisfied due to the technical limitations above.

**Comment by jochemschulten** [comment]
Hello guys,

I would like to help realise this. A complex example scenario why I need this:

> - Client has a page with multiple richeditors (Froala) to add HTML content to different blocks on the webpage. For this I use the Pages plugin together with page variables: {variable tab="Block 1" type="richeditor" name="block1_content" label="Content"}{/variable}
> 
> - Client wants to add some styled buttons inside the editor. For this I've added a custom class, 'button' on the 'Settings -> System -> Editor Settings -> Markup Classes' for links and added appropriate CSS styling in frontend.
> 
> - Client wants some content blocks to contain 'accordions / collapsibles' and 'popups' with custom HTML content inside, such as links, styled buttons, etc. For this I went for a snippet approach by adding a 'popup'-snippet and 'accordion'-snippet, with a 'title' and 'content' string variable for now. I used this plugin: http://octobercms.com/plugin/toughdeveloper-richeditorsnippets to make the snippets available for all editors.

So the problem i'm facing with this example are the limited snippet options for the 'content' variable. For now I use string. It would be great if this could be of type 'richeditor' with all the toolbar features available as for normal richeditor fields, even adding images from media manager etc.

I understand this will make the richeditor recursive/nested and very complex. But we might want to think of a proper way to show this on screen in the (nested) inspector or any other way around.  Maybe it's an idea to make the popup/accordion HTML content, 'Content'-blocks and reference them in the snippet? So then there would be a snippet option called: 'Content reference'.

**Comment by robinbonnes** [comment]
Hello guys,

I would like to help realise this. A complex example scenario why I need this:

> - Client has a page with multiple richeditors (Froala) to add HTML content to different blocks on the webpage. For this I use the Pages plugin together with page variables: {variable tab="Block 1" type="richeditor" name="block1_content" label="Content"}{/variable}
> 
> - Client wants to add some styled buttons inside the editor. For this I've added a custom class, 'button' on the 'Settings -> System -> Editor Settings -> Markup Classes' for links and added appropriate CSS styling in frontend.
> 
> - Client wants some content blocks to contain 'accordions / collapsibles' and 'popups' with custom HTML content inside, such as links, styled buttons, etc. For this I went for a snippet approach by adding a 'popup'-snippet and 'accordion'-snippet, with a 'title' and 'content' string variable for now. I used this plugin: http://octobercms.com/plugin/toughdeveloper-richeditorsnippets to make the snippets available for all editors.

So the problem i'm facing with this example are the limited snippet options for the 'content' variable. For now I use string. It would be great if this could be of type 'richeditor' with all the toolbar features available as for normal richeditor fields, even adding images from media manager etc.

I understand this will make the richeditor recursive/nested and very complex. But we might want to think of a proper way to show this on screen in the (nested) inspector or any other way around.  Maybe it's an idea to make the popup/accordion HTML content, 'Content'-blocks and reference them in the snippet? So then there would be a snippet option called: 'Content reference'.

**Comment by robinbonnes** [comment]
Because I need this in a hurry, I fixed this quick-and-dirty in this way:

'/plugins/rainlab/pages/classes/Snippet.php' line 473 from:
```
	if (preg_match_all('/\<figure\s+[^\>]+\>[^\<]*\<\/figure\>/i', $markup, $matches)) {
```
to:
```
       if (preg_match_all('/\<figure\s+[^\>]+\>.*\<\/figure\>/i', $markup, $matches)) {
```

'/themes/[themename]/partials/snippets/[snippetname].htm' from:
```
	snippetProperties[content][type] = "string"
```
to:
```
	snippetProperties[content][type] = "text"
```
/plugins/rainlab/pages/assets/js/pages-page add after line 72:
```
        $(document).on('shown.oc.popup', function(e) {
            var $elem = $(e.currentTarget.activeElement)
console.log($elem);
            if($elem.is('textarea')) {
                $elem.removeClass('size-small').addClass('size-large').closest('.modal-dialog').addClass('size-large')
                $elem.parent().richEditor()
            }
        })
```

I know this can be done nicer but it is working for now.

**Comment by LukeTowers** [comment]
I feel like this is stepping into the realm of visual page builders, which is a bit of a different requirement that the inspector isn't necessarily a good fit for.

**Comment by robinbonnes** [comment]
I thought you guys were working on something like that? (https://www.facebook.com/octobercms/photos/a.558200714293396.1073741828.558195297627271/1262916930488434/?type=3&theater)

Maybe that could be the alternative for workarounds like this.

**Comment by robinbonnes** [comment]
I've edited my quick-and-dirty fix above. Now it also supports 'complicated'-HTML content by encoding it to base64 first, and decoding it in the backend editor and frontend.

**Comment by mightyhaggis** [comment]
@LukeTowers @daftspunk 

As @robinbonnes is detailed in his example scenario on the 8th May.
Yes, it is a page builder of sorts but more controlled/ specific. (Is there likely to be any code ported from the upcoming "Landing Pages" plugin?) Would having the HTML/MD stored in a content file be an option? 

OctoberCMS & Rainlab plugins are fantastic, I am just now starting to properly use it/them so appreciate more and more. I'd very much like to reward the $50 to you. So **If you can** work your magic on a HTML Content type in a manner you are happy with and that complements Static Pages I will add another $25 to the current Bounty, maybe @robinbonnes will see fit to contribute... **If not possible** daftspunk's comment on 4 May 2016
> Add a media manager inspector type
> Make the new inspector types available to the snippet definition table (where possible)

Will satisfy the bounty and I'll figure a way around the HTML Content

**Comment by mightyhaggis** [comment]
Thinking about this slightly differently, would it be possible to leverage Static Pages current Custom Field capabilities to achieve some builder like capabilities? (details above)

Currently, with Custom Fields they are defined in the template and used to generate, tabs with input options in the editor. Their content stored in the header of the static page. This is fantastic but can't be used dynamically. As in, a new input option/tab with custom fields added to the page during content editing. 

Could a Partial/Snippet have new capabilities in Static Pages where Markup and Custom Fields are defined? Such that when a "Custom Fields Snippet" is added to a page either a new tab is added in the editor (could get busy quickly) or a modal that behaves similarly to a Custom Fields Tab.

Given the halting of the Landing Pages plugin might this be worth re-visiting? I do not have the knowledge, but I could increase the bounty to $200, should @LukeTowers  / @daftspunk think this worthwhile/ achievable and have the time to facilitate?

**Comment by martinBadin** [comment]
I would also welcome more types of fields for snippets. A good example of this plugin is the ACF plugin for Wordpress. Snippets are fine, but some types of fields are missing as mediafinger, richeditor or repeater. Here is an example of one page that is completely editable by the user. Page builder is created via the ACF plugin. I think that if you do this, OctoberCMS will be a full replacement for Wordpress.

![page-builder](https://user-images.githubusercontent.com/5845264/36353936-793d4e98-14cd-11e8-90ed-e9d4927f0915.png)
![page-builder-add-section](https://user-images.githubusercontent.com/5845264/36353939-81f623e8-14cd-11e8-8d52-3b021d1f7e4c.png)

**Comment by LukeTowers** [comment]
You can already do that with repeater groups @martinBadin http://octobercms.com/docs/backend/forms#widget-repeater

**Comment by claudchan** [comment]
Please implement type image (media finder) and simple rich text editor. This is very useful in real world. Snippet is reusable in any page is very useful but lack of insert image from media finder and also can t code using simple HTML such as styling text heading, bold, italic, lists etc. Please consider it.

**Comment by bennothommo** [comment]
Whilst there is a bounty on this request, it appears to have been abandoned. If the bounty is still available and this request is still required, please feel free to re-open this issue.
- - -
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by interactivespace** [comment]
> 
> 
> Whilst there is a bounty on this request, it appears to have been abandoned. If the bounty is still available and this request is still required, please feel free to re-open this issue.
> 
> Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

What was the reason the implementation of a type image (media finder) never succeeded. Is it not possible or was the bounty too low?

**Comment by LukeTowers** [comment]
@interactivespace bounty was too low to interest anyone in making it happen. Are you interested in sponsoring that feature?

**Comment by interactivespace** [comment]
> @interactivespace bounty was too low to interest anyone in making it happen. Are you interested in sponsoring that feature?

I need some more time to evaluate your cms. When nobody needed this feature in the past four years, there is a good chance that I have a conceptional missunderstand of the use of this feature.

**Comment by mightyhaggis** [comment]
I still have this on my wish list and am in discussions with an OctoberCMS Plugin developer to realise it along with some other ideas. (So it will probably be in the form of a plugin)

Currently, I use _Pages - Custom page fields_ in layouts to achieve most of my requirements.

**Comment by LukeTowers** [comment]
@interactivespace it's probably because there's so many other ways of achieving the same end result. To be fair though, adding mediafinder support to the inspector is something that I have at times wanted for myself, but I'm always too busy with higher priority work so I just haven't gotten around to it yet.

@mightyhaggis are you interested in sponsoring the development of adding it to the core for everyone?

**Comment by mightyhaggis** [comment]
@LukeTowers, as much as I'd like to, given the $50 bounty didn't prove enticing enough, sponsoring is likely out of my reach.

**Comment by LukeTowers** [comment]
@mightyhaggis in an effort to steal people's money, BountySource has just announced that they're going to be keeping any bounties older than two years unless the bounty poster emails them at support@bountysource.com to redirect the bounty to another issue. 

See below that was just emailed out today:

> 2.13 Bounty Time-Out. 
If no Solution is accepted within two years after a Bounty is posted, then the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource. For Bounties posted before June 30, 2018, the Backer may redeploy their Bounty to a new Issue by contacting support@bountysource.com before July 1, 2020. If the Backer does not redeploy their Bounty by the deadline, the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource.

If you would be willing to email support@bountysource.com to redirect your bounty to the Laravel 6 upgrade instead, that would be greatly appreciated: https://www.bountysource.com/issues/75392602-move-to-laravel-6

**Comment by mightyhaggis** [comment]
@LukeTowers I missed the last and they didn't email to tell me... , but I've just had an email from bountysouce saying you have have been awarded the bounty, can you confirm?

Also, you mention sponsoring the feature, can you advise what the cost would look like?

**Comment by LukeTowers** [comment]
@mightyhaggis yes, I've received the bounty now (still waiting for BountySource to transfer the money). 

When you talk about sponsoring the feature, are you referring to a mediafinder field type for the inspector?
