### ISSUE TITLE
Required snippet data attributes being stripped when switching to code view

### ISSUE THREAD

**Issue by grantjames** [rainlab/pages-plugin#134]
When I add a snippet to the richeditor and then switch to the code view, the only data-attribute that's left is the data-snippet one. All the others get stripped out.

If I manually re-add the attributes from the code view, they still get stripped out when going back to code view. However, what's strange is that data-name is one of the attributes, but I can add this attribute to a `<p>` tag and it doesn't get stripped. It's only being stripped from the `<figure>` tag.

EDIT: I have found the following code in plugins/rainlab/pages/assets/js/pages-snippets.js starting on line 179:

    SnippetManager.prototype.syncPageMarkup = function(ev, container) {
        ...
            $snippet.removeAttr('contenteditable data-name tabindex data-inspector-css-class data-inspector-class data-property-inspectorclassname data-property-inspectorproperty data-ui-block')
        ...
    }

So it seems the removal of the attributes is intentional - but it still breaks how the figure is displayed in the richeditor. Perhaps the easiest solution would be to leave in `data-name` and `data-ui-block` but I can't be sure as I'm not sure what the other attributes do.

**Comment by daftspunk** [comment]
This should've been fixed as part of the switch to Froala editor. Post another comment if it is still occurring.
