### ISSUE TITLE
Use a page variable within a menu item

### ISSUE THREAD

**Issue by StuFromDrum** [rainlab/pages-plugin#138]
Each of my static pages have a variable banner image (feature.jpg) and I'm trying to include those as thumbnails for each menu item but I can't for the life of me work out how to do it properly. 

Variable on each page:
`{variable name="banner" label="Banner" tab="Header" type="mediafinder" mode="image"}{/variable}`

I can get it to work if I use the following in the menu item partial where {{banner|media}} gives me '/storage/app/media/' and {{item.title}} is the image folder in the Media Manager.

`style="background-image: url('{{ banner|media }}Feature/{{item.title}}/feature.jpg');"`

This _does_ work ok but only if I put the images inside a folder that is named exactly the same as the menu item title (eg. /storage/app/media/Feature/Menu Item Title 1/feature.jpg).

Ideally what I'm after is to either automatically find the banner variable from the relevant page OR manually add a thumbnail to the menu item. The Blog plugin Featured Image has exactly the right functionality where you can include the image in the post list but the plugin itself doesn't do what I want it to so hence why I'm going down the Static Pages route :)

Any one have any ideas? I'm sure there's an easy way but I think I've been looking at it for too long!

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
