### ISSUE TITLE
Accessing placeholders within static menu's

### ISSUE THREAD

**Issue by ghost** [rainlab/pages-plugin#14]
I have a need to allow clients to set an icon on a static page menu item, and without an image/select placeholder I was going to use the type of "text" for the time being. That being said, I am not sure if there is a way to access that information when outputting the menu item.

Something along the lines of "item.extra.placeholdername" would be awesome. Is it already possible?

Thanks guys.
Jon
##

**Comment by SergeyMiracle** [comment]
Is it still in plan or not? Would be very useful to have this feature.

**Comment by daftspunk** [comment]
The feature is accepted and planned, feel free to submit a Pull Request or create a [bug bounty](http://bountysource.com) to have it implemented sooner.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
