### ISSUE TITLE
Extending validation rules for Page

### ISSUE THREAD

**Issue by seanthepottingshed** [rainlab/pages-plugin#141]
Is there a workaround to extend the validation rules of

`Rainlab\Pages\Classes\Page`

..as you would with a model? When I try the following...

```
Page::extend(function($model) {
    $model->bindEvent('model.beforeValidate', function() use ($model) {
        $model->rules['new_field'] = 'required';
    });
});
```

It obviously fails:

`Call to undefined method Cms\Classes\CmsObjectQuery::extend()`

Any advice would be gratefully appreciated.

**Comment by daftspunk** [comment]
This feature will be coming soon.

**Comment by seanthepottingshed** [comment]
Cheers @daftspunk you are a LEGEND

**Comment by seanthepottingshed** [comment]
Anything to do with Halcyon?

**Comment by daftspunk** [comment]
Yes, Halcyon will enable this exact syntax.

**Comment by seanthepottingshed** [comment]
![images](https://cloud.githubusercontent.com/assets/12046965/13917430/8b7f4d28-ef58-11e5-85b8-b5f4b9529dfd.png)

**Comment by seanthepottingshed** [comment]
Any news on the above @daftspunk?

**Comment by seanthepottingshed** [comment]
Ignore, all sorted ;)
