### ISSUE TITLE
All inserted snippets disappear when deleting text above

### ISSUE THREAD

**Issue by vojtasvoboda** [rainlab/pages-plugin#142]
When I create the new page, write some text, insert one snippet below text and then delete text char-by-char by backspace button, snippet suddenly disappears with the last char.

![snimek obrazovky 2016-03-15 v 19 29 49](https://cloud.githubusercontent.com/assets/374917/13789451/50fa44be-eae4-11e5-984a-2fd7f3483e0e.png)

**Comment by vojtasvoboda** [comment]
I made a video with reproducing the issue: http://tinypic.com/r/2ugibso/9

**Comment by vojtasvoboda** [comment]
I made a video reproducing this issue: http://tinypic.com/r/2jaydd/9

**Comment by msimkunas** [comment]
A similar issue happened to me as well - snippets kept disappearing after deleting all of the text content.

Also, this may or may not be related but I guess it's still worth mentioning. Switching the source/HTML view produces some strange behavior if any snippets are present in the editor. Going back to the HTML view makes snippets disappear and I can only see a loading icon spinning indefinitely in place of the snippets. The number of loading icons does not match the number of snippets though.

**Comment by daftspunk** [comment]
Fixed by https://github.com/octobercms/october/issues/2005
