### ISSUE TITLE
Critical bug: After saving a snippet partial file, all snippet's properties rows are empty

### ISSUE THREAD

**Issue by vojtasvoboda** [rainlab/pages-plugin#143]
I made a video reproducing this issue: http://tinypic.com/r/2ugibso/9

In short: with last OctoberCMS build 317 when you save snippet file, all properties disappear.

**Comment by web2easy** [comment]
+1 same problem

**Comment by daftspunk** [comment]
I noticed it too and fixed it, but can't remember when or where. Please retest using `edgeUpdates` on Build 319+ (available 1st April 2016).

**Comment by vojtasvoboda** [comment]
I tried it with build 319 and it is fixed!

But that issue with [disappearing snippets](https://github.com/rainlab/pages-plugin/issues/142) is still bad.
