### ISSUE TITLE
Importing batch content to pages plugin 

### ISSUE THREAD

**Issue by queengab** [rainlab/pages-plugin#145]
Hi to all,

i'm starting to using this plugin to manage static content and pages. The function sub-pages is a must-have! So i guess if there'a way to batch importing content. I don't know from a csv, better rtf, i'm studying the imort feature for october but is a little dififcult to me. 
The contents a re not stored in a db, inestead in a file, if i correctly understand. 
Have some suggestions or procedure?

Bye
Gabriele

**Comment by queengab** [comment]
Some news?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
