### ISSUE TITLE
Plugin broken after October update

### ISSUE THREAD

**Issue by shina** [rainlab/pages-plugin#147]
After update 322 (It was on 251 before) the \RainLab\Pages\Classes\Page and \RainLab\Pages\Classes\Menu classes are broken because of some properties are now static.

I'm not sure if setting these properties to static is the right solution. So I'll leave it to you.

Plus, when accessing a page created by the plugin, it start to throw Exceptions that I didn't recognise the root of the problem.

**Comment by chesterx** [comment]
+1

**Comment by daftspunk** [comment]
Make sure you are using the latest code base for both October and this plugin. This bug report would appear you are using latest October but old Pages plugin.

**Comment by chesterx** [comment]
it might be something else, i am using 324 build of october and fully updated pages plugin.

Throws this error.

```
Cannot redeclare static Cms\Classes\Content::$fillable as non static RainLab\Pages\Classes\Page::$fillable
~/plugins/rainlab/pages/classes/Page.php line 29
```

**Comment by daftspunk** [comment]
Looks like modules\cms\classes\Content.php is not getting updated? That file looks stale.

**Comment by chesterx** [comment]
Yes its an update problem, my edgeUpdates variable is true but there is no new update.

**Comment by chesterx** [comment]
its about the composer.json file. fixed this after changing it with develop branch's one.

**Comment by shina** [comment]
October's composer.json or Page's?

@daftspunk Is it safe to use the current develop branch's composer.json? Or is it better to wait for an update?

**Comment by chesterx** [comment]
I used October's develop branch composer.json

**Comment by adrenth** [comment]
I've got the same issues here. Using a fresh git clone; followed by installing the Pages plugin.

**Comment by daftspunk** [comment]
Here are your options, until we launch October stable:

- Purely use October gateway to get updates for this plugin, with or without edge updates enabled.

- Use `master` of this plugin repo and `develop` of the October repo.
