### ISSUE TITLE
Changing layout for new Subpage causes it to lose its parent category

### ISSUE THREAD

**Issue by duncanClicksco** [rainlab/pages-plugin#150]
How to replicate:
1. On pages, click "+ Add subpage" to add a child page below a parent
2. Before saving the new page, click to change the layout 
3. Save page and reload/refresh.

Page has been moved from a subpage into the structure root.

**Comment by voveson** [comment]
Is anyone working on a PR for this issue?  We'd like to pitch in if needed.

**Comment by daftspunk** [comment]
Duplicate of #99
