### ISSUE TITLE
Pulling {{ this.page.id }}

### ISSUE THREAD

**Issue by c-andrews** [rainlab/pages-plugin#151]
Is there a way to access this.page.id when using Static Pages?
It currently doesn't do anything :-(

Im trying to update the class name in a layout:
`<body class="page_{{ this.page.id }}">`

**Comment by vojtasvoboda** [comment]
Same problem here. When using Static Pages and layout from Flat UI theme with:

`<body class="page-{{ this.page.id }} layout-{{ this.layout.id }}">`

it renders:

`<body class="page- layout-default">`

**Comment by LukeTowers** [comment]
Bumping this as it is a confirmed bug that should be addressed at some point.

**Comment by bennothommo** [comment]
This is now resolved as of 000007d61d71cec84eefb1de712cd1c24ab409f5. This fix will be released with version 1.2.21 of the Static Pages plugin.
