### ISSUE TITLE
Static menu is not translatable?

### ISSUE THREAD

**Issue by didikz** [rainlab/pages-plugin#152]
translatable is working well in pages using this plugin. But it's seems that translatable doesn't apply for static menu. There is no option for selecting language when create or edit.

Am i missing something or there is such a way to enable translatable in static menu?

Thanks :)

**Comment by daftspunk** [comment]
Menu is translatable, see the [Bonjour theme](https://github.com/rainlab/bonjour-theme) for how this is possible.

**Comment by didikz** [comment]
it's working! thanks for helping...

**Comment by Arekusei** [comment]
For content sites it's not good.
The user will not understand how to create localized in multiple languages menu items.
