### ISSUE TITLE
Menu and dynamic pages

### ISSUE THREAD

**Issue by eisenhorn13** [rainlab/pages-plugin#155]
Does menu in Static Pages plugin works fine with dynamic pages with parameters?

I created books plugin in Builder, than in menu (Static Pages plugin) I added list item and as it`s subitem detail page item. Detail page has parameter - /books/single/:slug. So when I go to single page url in example /books/single/30, list item is not active and detail page item too. But if go to /books/single/default - both are active.

**Comment by jBOKA** [comment]
Dynamic menu items have to be manually injected by hooking into the appropriate events from the pages plugin. I did some work to automate this, right now its waiting as a pull request. 
https://github.com/rainlab/pages-plugin/pull/216

But you can read up on how to generate and inject in the pages plugin's docs. Its pretty detailed.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
