### ISSUE TITLE
Adding snippets doesn't work when using CKEditor

### ISSUE THREAD

**Issue by kikobalco** [rainlab/pages-plugin#157]
Hi, i noticed that adding snippets to static pages is possible only when using native OctoberCMS editor. I prefer it, but my client need CKEditor and i got some functionality based on it.

Is there any way to expand this functionality to CKEditor?
Or to suppress CKEditor on placeholder tab. This would solve that too.

I'm using this plugin:
http://octobercms.com/plugin/shahiemseymor-ckeditor

**Comment by hybridvision** [comment]
I don't think there's an easy way to expand the functionality for CKEditor but you might be interested to see that Redactor is being replaced with Froala Editor as the native editor: https://github.com/octobercms/october/issues/2005

If you really need to keep CKEditor you could try asking the plugin author about suppressing the editor on placeholder tabs...

**Comment by kikobalco** [comment]
Oh, Froala seems like really great news :) Thanks for info. 

Actually, I discovered that other plugin that provides CKEditor (Wysiwyg Editors) is not providing it on placeholder tabs. I think its bug of that plugin but its useful in this case, so its solved for now.
