### ISSUE TITLE
Invalid cursor position on ACE editor while editing txt content

### ISSUE THREAD

**Issue by side-by-side** [rainlab/pages-plugin#159]
Hello. I'm using last 340 buld of October CMS and Static Pages plugin v. 1.2.3.
There is an issue with cursor point position in the ACE editor when editing **txt** content files under ```Pages → Content → any *.txt file```: after click on the one line, cursor points to the below one. The same strange offset is also in horizontal orientation.

Look at the video in the attached archive.
[Sc-001.zip](https://github.com/rainlab/pages-plugin/files/287663/Sc-001.zip)

**Comment by daftspunk** [comment]
I can replicate this too. Will take a look soon. Thanks
