### ISSUE TITLE
[StaticMenu + Translate] Static pages menu URLs is not using current locale prefix

### ISSUE THREAD

**Issue by side-by-side** [rainlab/pages-plugin#167]
Hello.
I'm using ```StaticPages``` and ```Translate``` plugin and ```Locale Picker``` component with ```Force URL schema``` enabled, so my URLs are always prefixed with current language code.

All URLs in menu with **CMS page** items type are successfuly prefixed with current locale.

But in menu with **staic page** type (All Static Pages in my case) the URLs has no any language prefix.
The method ```\RainLab\Pages\Classes\Page::resolveMenuItem``` (https://github.com/rainlab/pages-plugin/blob/master/classes/Page.php#L717) is just not using passed ```$url``` parameter while building items URL.

**Comment by side-by-side** [comment]
This is also true for URLs in breadcrumbs.

**Comment by Kunilt** [comment]
+1

**Comment by davincho** [comment]
+1

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by daftspunk** [comment]
Replicated it!

This was fixed as part of https://github.com/rainlab/translate-plugin/issues/25

**Comment by side-by-side** [comment]
Thank you!
