### ISSUE TITLE
Create two new fields in Pages and create a for each via partial or twig

### ISSUE THREAD

**Issue by CitrinoDeveloping** [rainlab/pages-plugin#170]
Hi,

thanks for rainlab and great jobs for all your plugin. I and a friend of mine are developing our first website in October, It's a strage site with a report area; we are developed for this case the import plugin https://github.com/CitrinoDeveloping. 
Now for static pages we choose your Pages plugin and it s perfect suited. We have another area, the news! For the news is more apprpiate, maybe, rainlabBlog but we don't to use many plugin.
So we want etend the rainlabPages with new fields.

So we have 2 questions:

1) Which is the better way to extend Pages?
Create two variables in the layout of the news:
{variable name="featured" label="Featured" tab="newsProperties" type="checkbox"}{/variable}
{variable name="image" label="Image" tab="newsProperties" type="mediafinder" mode="image"}{/variable}
or create a plugin that extend it?

2) Which is the best way to create a for each to cycle only featured pages to print: title (with the link of the news) and image and then show it on a js carousel? 

I want also to extend the seo properties of the page so how can i extend fields on meta tabs and recall it? with the synthax {{ myproperty }}?

Thanks
Citrino

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
