### ISSUE TITLE
[staticMenu]: Access item.type from the template

### ISSUE THREAD

**Issue by LukeTowers** [rainlab/pages-plugin#171]
I would like to be able to access the the item's type property in my outputting of the staticMenu component. However, that isn't a property of the MenuItemReference class. How would I go about accessing the type property of a menu item in the component outputting; ideally in the form of {{ item.type }}?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by damsfx** [comment]
@LukeTowers 

I am exactly in the situation where I would like to be able to differentiate the header type items from the others in the rendering of my menu.  
But the type is not part of the menu item properties, how can I do this?

**Comment by bennothommo** [comment]
@damsfx Correct me if I'm wrong, but couldn't you use the `viewBag` for this purpose - like you can do with [creating custom fields for the menu](https://github.com/rainlab/pages-plugin/blob/master/docs/documentation.md#custom-menu-item-form-fields). The `viewBag` is for the definition of arbitrary values.

**Comment by LukeTowers** [comment]
@bennothommo it's been a while since I last looked at this but does it work like that? `item.viewBag.type`?

**Comment by bennothommo** [comment]
@LukeTowers I couldn't see why not - the docs for event `pages.menu.referencesGenerated` [give an example](https://github.com/rainlab/pages-plugin/blob/master/classes/Menu.php#L264) of view bag properties being defined on the fly, so I would assume that `type` could be specified in the view bag as well.

**Comment by LukeTowers** [comment]
Right, but is it defined by default out of the box?

**Comment by bennothommo** [comment]
If you mean viewBag is there by default, then yes.

**Comment by LukeTowers** [comment]
@bennothommo no, I mean is the menu item type data available out of box? i.e. `item.viewBag.type` = `item.type`?

**Comment by bennothommo** [comment]
@LukeTowers ah gotcha - no, I don't believe there is. There is a `type` defined with the `MenuItem` instance that's used in the Backend (separate to the view bag), but `MenuItemReference` instances are passed to the frontend, and they don't contain a type, so in this case, it would be safe to insert a type into the viewBag.

**Comment by LukeTowers** [comment]
@bennothommo do you have any concerns with the type being added to the MenuItemReference class?

**Comment by bennothommo** [comment]
@LukeTowers I'm wondering if it's really required when the view bag is already there? The view bag already covers a lot of use cases (including this one), being a completely arbitrary data store, and it separates the mechanics of `MenuItem` instances from what is passed to the view.

**Comment by LukeTowers** [comment]
Only issue I can think of with using the viewBag is that someone could already be using a type value inside of the viewbag for some other purpose.

**Comment by bennothommo** [comment]
@LukeTowers it's a possibility, but that would be the same of all objects that have view bags, like CMS templates. It would just require some careful planning of names, perhaps using some plugin code prefixes for example.

Just to clarify, I'm not against this change if it does solve some use cases.

**Comment by damsfx** [comment]
@LukeTowers @bennothommo 
Sorry I didn't think about ViewBag, I went a bit too fast in my thinking.

I'm wondering about the fact that this difference (of type) between menu and headings has never been reported on the FrontEnd?  
From a design point of view, it's still a benefit.

**Comment by LukeTowers** [comment]
@damsfx I definitely agree with you that the information should be available, after all I did create this initial issue over four years ago 😂 

@bennothommo I think it's an important enough property to make it a dedicated property on the frontend class. Any objections?

**Comment by bennothommo** [comment]
@LukeTowers go for it :)

**Comment by damsfx** [comment]
> 
> 
> ... after all I did create this initial issue over four years ago 😂
> 

I was just passing by the cellar!
