### ISSUE TITLE
Custom Snippet Preview in RTE

### ISSUE THREAD

**Issue by der-On** [rainlab/pages-plugin#172]
It would be great to display a preview for each snippet in the RTE.
When Snippets are created from components this could be done using a custom method on the component: `snippetPreview()' or 'preview()'

I could imagine loading snippet previews additionally at the point where snippet names are currently loaded using AJAX.

If you like I can try to implement this and make a PR.

**Comment by daftspunk** [comment]
It is an interesting idea, although could be a contentious one. If you are up for the challenge, feel free to submit a PR as a proposal to see how it might work from a technical standpoint.

**Comment by hybridvision** [comment]
Sounds great! Even just having more information displayed about each snippet would be nice - particularly when multiple instances of the same snippet are used on a page - it's not possible to differentiate them currently.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by der-On** [comment]
@LukeTowers  Hello again. I'm now trying to solve this. Looking through the code I found out that the placeholders are generated using Javascript and then populated with data-attributes for the properties. I'm currently puzzled where exactly the markup for the placeholders gets popuplated with the property data attributes. Any hints on where this happens would be very helpfull.

Currently I'm trying to implement a "preview property" which value should be displayed in the preview.
Another approach would be to be able to give each snippet instance a custom name using the inspector widget. Any hints on where this could be done would be very helpfull.

**Comment by LukeTowers** [comment]
@der-On sorry, I'm not super familiar with this so I'm not sure what direction to point you. Keep us posted on what you come up with though!

**Comment by der-On** [comment]
@daftspunk @alekseybobkov Looking at the git-blame (actually should be git-praise!) of the JS code I think you might be able to point me to something?

**Comment by LukeTowers** [comment]
@der-On @daftspunk gets a lot of notifications on here and @alekseybobkov doesn't use Github that frequently so you might be better off trying to contact @daftspunk on Slack or IRC

**Comment by der-On** [comment]
@LukeTowers Thank you. I've wrote him on Slack now.
