### ISSUE TITLE
Snippet does not work when it is created using CMS > Partials

### ISSUE THREAD

**Issue by tiagomatosweb** [rainlab/pages-plugin#175]
When I try to create snippet using CMS > Partials, in the the [viewBag] section is shown only snippetCode and snippetName even if I configure the properties.

However, if I go to the file manually and insert the properties by hand I can see it via CMS > Partials, but if I save it using partial my properties are gone.

In other words, I lose my properties if I edit snippets via CMS > Partials.

**Comment by fresswolf** [comment]
Same here. Those rows are not saved

**Comment by fresswolf** [comment]
this works again with the latest october version
