### ISSUE TITLE
Inserting multiple instances of a snippet no longer works

### ISSUE THREAD

**Issue by hybridvision** [rainlab/pages-plugin#177]
Since the Froala editor update, there seems to be quite a serious bug with the component-based snippets that prevents multiple instances of a snippet from being inserted into a page.

The core issue is that snippets do not receive a unique code in the `data-snippet` attribute. This previously worked so it seems to be a bug introduced around the time of the editor change.

Some initial debugging leads me to the `generateUniqueComponentSnippetCode` function in pages-snippets.js ([see here](https://github.com/rainlab/pages-plugin/blob/master/assets/js/pages-snippets.js#L85)). It appears that the editor is not returning the content, so the function never finds the existing snippets on the page and therefore never generates unique codes for each. Instead, it generates the same code every time.

Of course, the code can be manually edited in the HTML but that is only a stop-gap solution.

----

Here's a summary of the issue:

**Expected Behaviour**

When inserting (component-based) snippets, each snippet should receive a unique code, allowing it to function independently of other snippets of the same class on the same page.

**Actual Behaviour**

All snippets are given the same (ID) code. For example, a snippet with the code `imageGallery` will have this code repeated for every instance. This results in the data from the last instance overwriting all others when the page renders.

**Steps to reproduce**

1) Open a static page in the editor
2) Add two or more instances of the same component-based snippet
3) Verify via the HTML code view that each snippet has the same `data-snippet` assigned, causing incorrect rendering.

**OctoberCMS Build**

OctoberCMS build 346 with Rainlab Pages Plugin v1.2.6

**Comment by daftspunk** [comment]
I was unable to replicate this, I appear to get 2 unique IDs:

```
<figure data-component="RainLab\Blog\Components\Post" data-inspector-id="inspectorid-833169124221" data-property-categorypage="404" data-property-slug="{{ :slug }}" data-snippet="blogPost">&nbsp;</figure>


<figure data-component="RainLab\Blog\Components\Post" data-inspector-id="inspectorid-712178190784" data-property-categorypage="404" data-property-slug="23423234" data-snippet="blogPost">&nbsp;</figure>

```

**Comment by hybridvision** [comment]
Thanks for checking it out @daftspunk! I think you might have misunderstood the problem though... It's not the `data-inspector-id` that has the problem, it's the `data-snippet` attribute.

As you'll see in your code above, both have the value `blogPost` but the second one should be `blogPost1` - this is what makes the components unique. If you were to save your page above and view it, both snippets would render the same thing because the second snippet overwrites the properties of the first one due to having the same code/ID.

Does that make sense? In the editor all is working fine and I guess that's because it uses the `data-inspector-id` value. I am quite certain that the `data-snippet` value should be different for each instance because I have pages that were created with the old editor and the multiple snippet instances each have a unique code. Furthermore, manually changing the `data-snippet` value makes the page render as expected...

When it's working, you should get `data-snippet` values of `blogPost`, `blogPost1`, `blogPost2` etc...

Please let me know if you need any more details or explanations. Thanks!

**Comment by daftspunk** [comment]
I think we may need @alekseybobkov to help us with this.

**Comment by daftspunk** [comment]
@hybridvision can you test this 02abd8f2f3199aef208565d6a12b6b2f02ffbd35 change and see if it fixes it for you? It seems to work for me

**Comment by codee** [comment]
@daftspunk Thanks, 02abd8f has solved it for me. Oddly enough, it didn't work until I removed and recreated every single snippet instance.

**Comment by hybridvision** [comment]
@daftspunk - thanks! It works like a charm :)

@codee - it's not so odd that you had to add each snippet again because this code was related to inserting new snippets. If you already had a bunch of snippets with duplicated identifiers, they wouldn't get updated. An easier method for you might have been to manually edit the `data-snippet` attribute in the HTML view to give each snippet a unique code.

**Comment by charles-tainui** [comment]
hello,
wereas data-snippet attributes are unique for 2 instances of the same snippet, i'm facing this issue on OctoberCMS build 446 with Rainlab Pages Plugin v1.2.20

**Comment by boyardnicolas** [comment]
I have the same issue, inserting the same Snippet twice in the page - with different parameters - does not work.
Only difference is that **I do have different data-snippet value,** which is expected behavior (data-property-displayfilters is what differs).
```
<figure data-component="\Boboy\Events\Components\Events" data-inspector-id="inspectorid-1293494741169" data-property-displayfilters="0" data-property-noeventsmessage="No events yet, stay tuned" data-property-nomatchingeventsmessage="There are no events matching your criteria" data-snippet="events1">&nbsp;</figure>
<figure data-component="\Boboy\Events\Components\Events" data-inspector-id="inspectorid-1057415664719" data-property-displayfilters="1" data-property-noeventsmessage="No events yet, stay tuned" data-property-nomatchingeventsmessage="There are no events matching your criteria" data-snippet="events">&nbsp;</figure>
```

Though in the page the component is displayed twice, **both have the filters functionality**.
I first noticed that when trying to have two different `peterhegman-slickslider` in the same page (header + footer), the footer slideshow would overwrite the header slideshow.

**Steps to reproduce:** Insert any component-based snippet twice or more in the same static page, with different configuration, the last config will be applied to all.

I'm using **OctoberCMS build 467** and **pages plugin 1.3.3**

**Comment by LukeTowers** [comment]
@boyardnicolas sounds like a problem with that particular component in that it's probably injecting it's data into the page, and then using that data in the component partial instead of referencing instance-specific data under `__SELF__`. Submit an issue to the plugin's author.

**Comment by boyardnicolas** [comment]
@LukeTowers thanks for the insight. I'm new to OctoberCMS and overlooked the `__SELF__` thing, I've submitted a pull request to the plugin's author.
I've just replaced all the references to `slider` by `__SELF__` like so:
```
- {% if not(slider.slides.slideShows is same as ('no_slider')) %}
+ {% if not(__SELF__.slides.slideShows is same as ('no_slider')) %}
```
Seems to do the trick, thanks!
