### ISSUE TITLE
Cannot redeclare static Cms\Classes\Content::$fillable as non static RainLab\Pages\Classes\Page::$fillable

### ISSUE THREAD

**Issue by vdomah** [rainlab/pages-plugin#180]
Hello!

I got Pages plugin in a project. And same identic project gives error on one server and works fine on another:

`Cannot redeclare static Cms\Classes\Content::$fillable as non static RainLab\Pages\Classes\Page::$fillable`

I didn't find any place in code where $fillable was declared as static. What could it be?

**Comment by daftspunk** [comment]
Sounds like you are still using the RC version of October, update to Stable version and it will go away.

**Comment by xaddict** [comment]
Hi. I'm also having this message but Forcing update of the system does not help. How should I update to the stable?
