### ISSUE TITLE
Users can access Pages even without permission

### ISSUE THREAD

**Issue by jan-vince** [rainlab/pages-plugin#181]
With permissions set to only allow Content access, users still can access and edit Pages.

Icon for Pages is not present in left menu, but when I click on Pages icon in main (top) menu, I get to the list of Pages and I can edit them.

OctoberCMS build: 349
Static Pages plugin: 1.2.8

**Comment by LukeTowers** [comment]
Pinging myself to check this out

**Comment by manuelbua** [comment]
+1, i can confirm i'm experiencing the same issue where i need the client to only edit menus and not pages.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by LukeTowers** [comment]
Fixed in https://github.com/rainlab/pages-plugin/commit/0ea93942df1bd12cb52e9137d8feee31e9429f5e
