### ISSUE TITLE
Static Page drag n drop does not work in Rich Editor for FF and IE

### ISSUE THREAD

**Issue by Madagar** [rainlab/pages-plugin#183]
Hello, my problem is, when you are on the static page and there you change the position of the snippets.
This works in the Safarie and Chrome Browser on a Mac, but under the Firefox and a Window IE11 has no chance to change the position.

Can this Error, please, be changed?

How i can see this, it must be an error in the 
/modules/backend/formwidgets/richeditor/assets/js/build-min.js 
File.

**Comment by daftspunk** [comment]
This is not an error, more than likely it is because the browser used does not support native HTML5 drag and drop. Give it time, these browser will catch up eventually.

- Tested with Firefox in Windows +OK
- Tested with IE Edge in Windows =FAIL
- Tested in IE 11 in Windows =FAIL
