### ISSUE TITLE
[Enhancement] Snippets: Show property value(s) in rich editor beside snippet's name

### ISSUE THREAD

**Issue by codee** [rainlab/pages-plugin#184]
When using multiple instances of a snippet created from a component with different property values, there should be a easy way to tell them apart without having to click on each one to see its property values. As of right now the rich editor only shows the component name, it would be great if there was a way to show some of the key property values there as well, perhaps achieved through a property parameter "showInSnippetDescription" or something along those lines.

Real-life use case: I'm using a snippet that acts as a featured products widget that only shows products from a specified category (for which there's a dropdown property). When there are multiple instances of that snippet on a page I would like to see what category they're pulling from just by glancing through them, e.g. "Featured Products - Shoes", "Featured Products - Socks", "Featured Products - Accessories", instead of just "Featured Products" repeated 3 times over.

**Comment by LukeTowers** [comment]
Related: #172

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
