### ISSUE TITLE
URL with slug

### ISSUE THREAD

**Issue by LaravelNick** [rainlab/pages-plugin#186]
Is there any way in which we can set the URL to something like '/forum/channel/:slug' ?

If so, could we then include the Forum component in a Static Page, using a snippet ?

**Comment by codee** [comment]
I think your answer lies in the extended name of the plugin, Static Pages. Technically a page needing a slug can't really be considered static hence I wouldn't expect such functionality to be supported by this plugin.

**Comment by daftspunk** [comment]
@codee has a point. There are ways around it though, static pages will support GET parameters

/forum/channel?slug=foobar

```
description = "Forum layout"
[staticPage]
[forumChannel]
==
function onInit()
{
    $this->forumChannel->setProperty('slug', get('slug'));
}
==
...
```

Just off the top of my head, not tested or anything

**Comment by ilyaskorik** [comment]
Why then do keep two different and overlapping capabilities?

The Static Pages have menus and breadcrumbs, but there is no url params, and CMS Pages have url params, but there is no menu and breadcrumbs :(

**Comment by ilyaskorik** [comment]
I tried to use the Static Pages for their components, but without this feature, it can be done. As a result, I have to duplicate the code and layouts to realize the dynamic part of using components and static part via Static Pages.

**Comment by codee** [comment]
@ilyaskorik Because the Pages plugin is designed to make your backend more user-friendly for your clients, ie. people who are not necessarily tech-savvy. Personally I've found snippets to be a nice way of encapsulating dynamic functionality while keeping it simple and manageable for our clients.
