### ISSUE TITLE
Component from Partial (AJAX handler Not Found)

### ISSUE THREAD

**Issue by LucasZdv** [rainlab/pages-plugin#187]
Hello, 
when I add an component from Partial to StaticPage this Component not work correctly... 
The handler was not found.
screen here : http://nimb.ws/aYI9qz

I tried it the same with some plugins and I get the same problem.
We forced to use the layout, whose component in the layout worked fine.

**Comment by daftspunk** [comment]
There are some limitation with partials, namely that AJAX is not supported in them because they render too late in the life cycle. See documentation for more details:

http://octobercms.com/docs/cms/partials#life-cycle-limitations

**Comment by LucasZdv** [comment]
Thanks, I understand! sorry I did not read this!
I think it would be good practice to load components in Static Pages, to avoid overloading loading "all" in the layout. 

I Love OctoberCMS, good job ;)!
