### ISSUE TITLE
Control which buttons appear within the WYSIWYG editor toolbar.

### ISSUE THREAD

**Issue by KirbyFox** [rainlab/pages-plugin#188]
Can't find any option to change this anywhere.

**Comment by daftspunk** [comment]
This issue lacks detail, namely why it is needed, real world use case, proposed implementation, etc.

**Comment by mrtomstone** [comment]
+1

I wish to hide the video, audio and file buttons from the WYSIWYG editor. Is this possible?

**Comment by daftspunk** [comment]
Raised https://github.com/octobercms/october/issues/2384 as the solution

**Comment by LukeTowers** [comment]
Support has been added in https://github.com/octobercms/october/commit/dfcf324d008b6c20122a20a2b26b43a22111583f by @Harti
