### ISSUE TITLE
"created_at" and "updated_at" for a page

### ISSUE THREAD

**Issue by mahony0** [rainlab/pages-plugin#191]
Did I missed it or is there a logic for getting created time and last updated time for a static page? I know it's stored on a flat file but is there a way to achieve that?

**Comment by daftspunk** [comment]
`updated_at` should be available as the `mtime` (modification time) attribute. However, the created time is not stored I'm afraid.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
