### ISSUE TITLE
WYSIWYG issues

### ISSUE THREAD

**Issue by grantjames** [rainlab/pages-plugin#193]
I'm having some issues with the WYSIWYG editor.

October CMS version: 365
Rainlab pages version: 1.2.9

To re-produce, create a page and switch to the code view. Firstly, something tries to load worker-html.js but it's trying to load it from: /backend/rainlab/worker-html.js where as the path should be /modules/backend/formwidgets/codeeditor/assets/vendor/ace/worker-html.js

I presume this is because the code editor that's used for the WYSIWYG editor doesn't have the data-vendor-path attribute set and so just tries to look in the current folder, but I can't figure out how to add that attribute to the relevant div.

Secondly, if editing in code view, you have to switch back to WYSIWYG view before saving otherwise your changes aren't saved. I'm not sure if this is related to the fact that worker-html.js isn't being loaded or whether it's a separate issue.

EDIT: I've just noticed that the issue loading worker-html.js doesn't occur when editing content, but the second issue about not saving when in code view is still present so it must be unrelated.

**Comment by daftspunk** [comment]
Both issues mentioned here are fixed in Build 370+

**Comment by LukeTowers** [comment]
I'm now having issues with seeing the code view at all on the latest dev branch of October @daftspunk 

Running off of branch develop, latest commits were:
october/cms (dev-develop 6f4ae6a)
october/system (dev-develop a01f3bc)
october/backend (dev-develop 39a3585)

**Comment by LukeTowers** [comment]
Never mind, looks like the field in question had a size of `''` set in `fields.yaml` from the Builder plugin, so that would be a better issue to raise with the Builder plugin creating those empty strings in the first place or the config handler for using them instead of the defaults
