### ISSUE TITLE
TypeError: null is not an object (evaluating 'this.editor.codeView')

### ISSUE THREAD

**Issue by Hambern** [rainlab/pages-plugin#197]
Hi, I have a strange issue. When I add a snippet to a static page it's first fine. But when I reload the page and tries to change it. I get a javascript error:

`TypeError: null is not an object (evaluating 'this.editor.codeView')`

And the snippet gets stuck on "Loading", not showing the WYSIWYG.

See pictures... What could possibly be the problem? It does not matter which snippet i use. Even empty snippets cause this error.

<img width="840" alt="skarmavbild 2016-10-12 kl 20 31 29" src="https://cloud.githubusercontent.com/assets/3506799/19323284/8b363ccc-90bc-11e6-9519-d2977d85b097.png">
<img width="1008" alt="skarmavbild 2016-10-12 kl 20 31 51" src="https://cloud.githubusercontent.com/assets/3506799/19323283/8b3101c6-90bc-11e6-8c6a-db9e63706480.png">

**Comment by daftspunk** [comment]
This will be fixed in Build 371+

Thanks for helping us with the testing by using edge builds!

**Comment by Hambern** [comment]
No problems, it's more exciting to live on the edge :) Fantastic work!
