### ISSUE TITLE
The partial '_page_links_form.htm' is not found.

### ISSUE THREAD

**Issue by joris-vdlp** [rainlab/pages-plugin#199]
When you want to insert a link thru the richeditor and you click on the magnifying glass (choose link). I get the error that the partial '_page_links_form.htm' is not found.

> "The partial '_page_links_form.htm' is not found." on line 65 of /var/www/framework/modules/system/Traits/ViewMaker.php

Version of plugin is 1.2.9. 
October CMS build 365

**Comment by daftspunk** [comment]
Wasn't able to replicate this. Can you provide step by step instructions on how you arrived at this error?

**Comment by joris-vdlp** [comment]
Made a screen recording. http://g.recordit.co/QoLJF74iq5.gif (the cms is in dutch)

`exception 'October\Rain\Exception\SystemException' with message 'Het sjabloon (partial) '_page_links_form.htm' is niet gevonden.' in /home/*/*/*.nl/releases/20161103135917/modules/system/traits/ViewMaker.php:65
Stack trace:
#0 /home/*/*/*/releases/20161103135917/modules/backend/formwidgets/RichEditor.php(108): Backend\Classes\WidgetBase->makePartial('page_links_form')
#1 [internal function]: Backend\FormWidgets\RichEditor->onLoadPageLinksForm()
#2 /home/*/*/*/releases/20161103135917/modules/backend/classes/Controller.php(510): call_user_func_array(Array, Array)
#3 /home/*/*/*/releases/20161103135917/modules/backend/classes/Controller.php(417): Backend\Classes\Controller->runAjaxHandler('formPage2c8c394...')
#4 /home/*/*/*/releases/20161103135917/modules/backend/classes/Controller.php(227): Backend\Classes\Controller->execAjaxHandlers()`

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
