### ISSUE TITLE
[Question] How to switch all fields to other locale in one click?

### ISSUE THREAD

**Issue by vojtasvoboda** [rainlab/pages-plugin#204]
Is it possible to switch locale for all editable fields in one click? Because when I want to create new page translation I have to switch locale for Title, for URL and finally for Content - three clicks for each page.

**Comment by Eoler** [comment]
>Is it possible to switch locale for all editable fields in one click?

Yes, try CTRL+click.

**Comment by vojtasvoboda** [comment]
Very nice! 👍
