### ISSUE TITLE
Syntax error in lang file

### ISSUE THREAD

**Issue by jeremylemardele** [rainlab/pages-plugin#206]
Hello,

I just updated the plugin, and I found an error in the french lang.php file generating an fatal Exception in my site and backend.

I added the missing comma ',' in /plugins/rainlab/pages/lang/fr/lang.php line 64, to make it work again.

Many best.
Jeremy

**Comment by Wadeck** [comment]
Actually the correction is already proposed by @pvullioud in #200

**Comment by daftspunk** [comment]
Merged, thanks
