### ISSUE TITLE
Menu - Spitting out errors when using static page type

### ISSUE THREAD

**Issue by viacreativedev** [rainlab/pages-plugin#207]
Hi guys,

I have a website that uses the Static Pages plugin, with a menu that has links to several static pages. This has been working until recently when I upgraded the plugin to the latest version.

Now, I'm getting an error saying the `Cms` class doesn't exist (screenshot attached). I can only reproduce this issue when using menu item types `static-page`.

![screen shot 2016-11-02 at 09 21 48](https://cloud.githubusercontent.com/assets/21076632/19923183/27a02bc8-a0de-11e6-8fca-a2cf699087a7.png)

**Comment by viacreativedev** [comment]
This is the line in question:

https://github.com/rainlab/pages-plugin/blob/master/classes/Page.php#L719

**Comment by daftspunk** [comment]
The `Cms` facade was introduced in [Build 362](http://octobercms.com/changelog)

```
Build 362	
Introduce a CMS helper for handling URL generation.
Aug 26, 2016
```

Make sure you are using the latest OctoberCMS code base.

Ref: https://github.com/octobercms/october/commit/c8d8d4e931102a8c4db0469914c2b60a0b0950a2
