### ISSUE TITLE
[Enhancement] More streamlined way to generate static menu items from plugin models

### ISSUE THREAD

**Issue by jBOKA** [rainlab/pages-plugin#209]
Hi,

I think it would really improve the pages plugin, if it would offer some implementation on how to generate dynamic menu items. I found myself repeating the same steps on most of my projects. As described in the Pages plugin's docs, I hooked into the events and generated the menu items. So I ended up with writing a model behavior for simple sluggable models, that use routes like `/itemtype/:slug`.

This is possible with these configuration properties in the implementing model
```PHP
    public $implement = ['Vendor.MenuItemHelper.Behaviors.MenuItemGenerator'];

    public $menuItemName = 'Some custom title'; // Descriptive name for the menuitem type dropdown
    public $menuItemTypeCode = 'vendor-plugin-itemtype'; // some unique item type
    public $menuItemNameField = 'title'; // the model field to use for the menu item title
    public $menuItemSlugField = 'slug'; // the model field to use for the slug
    public $menuItemComponent = 'itemComponent'; // name of component that indicates the page, that is referenced
    public $menuItemComponentSlugProperty = 'slug'; // component property, that indicates which url parameter to use
```

Adding the types at the several hooks on plugin's `boot` function looks like this:
```PHP
        Event::listen('pages.menuitem.listTypes', function() {
            $result = [];
            $result += (new Model)->getMenuItemType();
            return $result;
        });
        Event::listen('pages.menuitem.getTypeInfo', function($type) {
            if ($type == (new Model)->getMenuItemTypeCode())
                return (new Model)->getMenuTypeInfo($type);
        });
        Event::listen('pages.menuitem.resolveItem', function($type, $item, $url, $theme) {
            if ($type == (new Model)->getMenuItemTypeCode())
                return (new Model)->resolveMenuItem($item, $url, $theme);
        });
```

I'd really like to hear some opinions, because I think many people would want to use the Pages plugin for the additional advantages for customer safe content management.

I'd really like to improve this idea, maybe it can be generalized a little more (even more url parameters, like item categories and safe url parsing including queries, which is missing right now), so that there is a "standard way" to tackle dynamic menus.

The implementation (is eventually just taken from the RainLab.Blog plugin) and looks like this
```PHP
class MenuItemGenerator extends ModelBehavior
{
    /**
     * @var array Properties that must exist in the model using this behavior.
     */
    protected $requiredProperties = [
        'menuItemName',
        'menuItemTypeCode',
        'menuItemNameField',
        'menuItemSlugField',
        'menuItemComponent',
        'menuItemComponentSlugProperty',
    ];

    /**
     * Constructor
     */
    public function __construct($model)
    {
        parent::__construct($model);
    }

    public function getMenuItemType()
    {
        return [$this->model->menuItemTypeCode => $this->model->menuItemName];
    }

    public function getMenuItemTypeCode()
    {
        return $this->model->menuItemTypeCode;
    }

    public function getMenuTypeInfo($type)
    {
        $result = [];

        if ($type == $this->model->menuItemTypeCode) {

            $result = [
                'dynamicItems' => true, // would generate new ones
                'nesting' => true
            ];

        }

        if ($result) {
            // get page with 'projects' component
            $theme = Theme::getActiveTheme();
            $pages = CmsPage::listInTheme($theme, true);
            $itemPages = [];
            foreach ($pages as $page) {
                if (!$page->hasComponent($this->model->menuItemComponent)) {
                    continue;
                }
                else {
                    $itemPages[] = $page;
                }
            }
            $result['cmsPages'] = $itemPages;
        }

        return $result;
    }
    
    public function resolveMenuItem($item, $url, $theme)
    {
        $result = null;

        if ($item->type == $this->model->menuItemTypeCode) {

            $modelItems = $this->model
                ->select('id',$this->model->menuItemNameField,$this->model->menuItemSlugField)
                ->get();

            $itemUrls = $this->getPageUrls($item->cmsPage, $modelItems, $theme);

            $result = [
                'url' => $itemUrls[0],
                'isActive' => ($url == $itemUrls[0]),
                'items' => []
            ];

            foreach ($modelItems as $modelItem) {
                $result['items'][] = [
                    'title' => $modelItem->{$this->model->menuItemNameField},
                    'url' => $itemUrls[$modelItem->id],
                    'isActive' => ($url == $itemUrls[$modelItem->id]),
                    'cssClass' => ''
                ];
            }

        }

        return $result;
    }

    protected function getPageUrls($pageCode, $modelItems, $theme)
    {
        $page = CmsPage::loadCached($theme, $pageCode);
        if (!$page) return;
        $properties = $page->getComponentProperties($this->model->menuItemComponent);

        if (!isset($properties[$this->model->menuItemComponentSlugProperty])) {
            return;
        }
        /*
         * Extract the routing parameter name from the category filter
         * eg: {{ :someRouteParam }}
         */
        if (!preg_match('/^\{\{([^\}]+)\}\}$/', $properties[$this->model->menuItemComponentSlugProperty], $matches)) {
            return;
        }
        $paramName = substr(trim($matches[1]), 1);
        $itemUrls = [];
        $itemUrls[0] = CmsPage::url($page->getBaseFileName(), [$paramName => null]);
        foreach ($modelItems as $modelItem) {
            $itemUrls[$modelItem->id] = CmsPage::url($page->getBaseFileName(), [$paramName => $modelItem->{$this->model->menuItemSlugField}]);
        }
        return $itemUrls;
    }


}
```

**Comment by daftspunk** [comment]
This looks pretty good except there are a few too many properties, it might be a better idea to move this to a configuration file that lives with the model instead. Ideally this config would allow the same model to provide multiple menu items, although probably uncommon.

```
protected $menuItemConfig = "menu_items.yaml";
```

Simply include the `ConfigMaker` trait and then you have the ability to load config files in the model behavior. Here is an example: 

https://github.com/octobercms/october/blob/master/modules/system/behaviors/SettingsModel.php#L246

**Comment by jBOKA** [comment]
For a single menu time config I'm almost done.
@daftspunk can you clarify what the `nesting` option does?
I get the `dynamicItems` property, which right now allows for the replace to happen. But the nesting isn't clear to me.

**Comment by jBOKA** [comment]
I find the available possibilities for generating Items with subitems little unintuitive to handle regarding the options to create a menu.

I want to define config types, to allow for different types of menu generation (listing, tree etc)

# 1. Approach (type: list&detail)

As above, if I want to create a menu item type for listing with children pointing to detail pages like so:
```
listing page
    - model instance 1 detail page
    - model instance 2 detail page
    - model instance 3 detail page
```

So when creating the menu item, I would have to gather the following information.

From the user configuring the menu:
- cms page for the listing (can beforehand be filtered by existence of listing component)
- cms page for the detail (can beforehand be filtered by existence of detail component)

From the Behavior user:
- name of the listing component
- name of the detail component
- slug property of the detail component
- slug field of the model
- title field of the model (like titleFrom)

In the current setup, I can only let the user choose one `cmsPage` (let's say detail) and would have to make use of the `reference` field to offer choosing the second necessary `cmsPage` (listing).

This seems hacky.

# 2. Approach (type: detail only)
I could also make the user (configuring the menu) create a cms page entry manually for the listing.

Then I'd have to let the behavior user generate a list of entries, but without a parent. But since the Behavior user cannot force the `replace with children` option by code (only the user creating the menu can check that box), we are left with an empty parent (or if we leave the `url` of the parent empty, it is replaced by the first child's url).

# Solutions
- Misuse the reference field to point to a cmsPage
- Instruct the behavior users to tell the menu users to use replace
- Take a different approach to types of menu items

I already have a multi config setup prepared, but I'm not sure about the types of config to offer to the behavior user. I'm willing to implement multiple, but only with a lasting structure. I think this improves the whole menu thing a lot.

**Comment by LukeTowers** [comment]
@jBOKA is this still something that you want added?

**Comment by jBOKA** [comment]
Still some work to do on that. Unfortunately im involved so much in other stuff right now, I can't make any promises about when to finish this.
Fell free to close. I will open another Issue/PR as soon as I find the time.
I'm using it regularly, so yes, I'll get back to it later to make it ready for production.

**Comment by LukeTowers** [comment]
Alright, I'll close this for now. Please reference this issue when making your PR to make it available for production.
