### ISSUE TITLE
[multilingual] Page title and URL slug generation aren't synced for the localized title

### ISSUE THREAD

**Issue by manuelbua** [rainlab/pages-plugin#212]
With both **1.2.10** and **1.2.11**, in a multilingual context (ie. EN+IT), the URL generation is completely out of sync and will overwrite the URL for the original translation.

#### Subissue 1, page creation
Try to add a new page, specify a title and save it: note the URL is generated fine.
Now switch page title to another locale and edit it, note how it overwrites the original URL slug in the original language and both locales now point to the same URL.

#### Subissue 2, page layout update

If your page has both translations and URLs filled in, switching layout to another one will cause the URL generated from a localized title to be invalid, empty or missing, while the original URL will be replaced by the localized one.

#### Subissue 3, page used inside a menu

With version **1.2.11 only**, if the page is added to a menu within the `Menus`, then the generated frontend link for the translated URL is wrong, pointing to the non-localized version: i also tried this in **1.2.10** and it's not happening there.

**Comment by CptMeatball** [comment]
Regarding Subissue 3:
What kind of page are you referencing? My menu has Static Page references and does translate the URL.

**Comment by manuelbua** [comment]
I'm referencing a static page as well: it looks like this issue is related to server-side caching of some sort, or the order i follow inserting the data in the backend; or this may also be related to the subissue 1 during creation.
In this regard, i found out that specifying an URL before anything else will not cause the problem, but specifying a title first will replicate the problem consistently; i should retry everything with some other order of insertion and retry subissue 3 as well, hope to have the time this week, too much work to do these days o_O

**Comment by CptMeatball** [comment]
It would seem that the Javascript that causes the Title to Slug preset (on the @create action/view) is not unloaded after the save action.

**Comment by daftspunk** [comment]
This issue lacks enough detail or the replication instructions cannot be actioned easily. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Comment by daftspunk** [comment]
Please resubmit each bug as a separate GitHub issue so we can investigate further for each individual case.
