### ISSUE TITLE
Pages using layouts that make use of dynamic syntax (view/editor mode) with a repeater cause errors when switching language before saving

### ISSUE THREAD

**Issue by manuelbua** [rainlab/pages-plugin#213]
Pages using layouts that make use of dynamic syntax (view/editor mode) with a repeater cause errors when switching language before saving.

Creating a new page that uses a layout that defines editor fields with the dynamic syntax feature and a repeater  causes an `HTTP 500` error on the Ajax request when switching language *before* saving.

### Reproduction

1. setup a multilingual site with OctoberCMS
2. add a new language and enable it so that you have two
3. within the demo theme, go to `CMS` backend, create a new layout, add static
pages support and define some custom fields with a dynamic syntax repeater:

```
    description = "New layout"

    [staticPage]
    ==
    <hr>

    {repeater name="content_sections" prompt="Add another content section"}
        <h2>{text name="mytitle" label="My Title"}My Title{/text}</h2>
        <p>{textarea name="content" label="Content"}Content{/textarea}</p>
    {/repeater}

    <hr>
```

4. Go to the `Pages` backend, create a new page, ensure the layout just created is selected, note the additional tab, mine is called `Misc`.
5. Fill-in a title and an URL, switch to the `Misc` tab and choose another language for the widget: an error pops up.

### Expected behavior

No error should popup, it's expected for the widget to just switch to the selected language.

### Observed behavior

An error telling `The requested object was not found.` pops up: as soon as the message dialog is closed, the repeater's language switcher also remains in an undetermined state that's impossible to change without refreshing the page, loosing any data.

### Current solution

The current `workaround` is to save the data **before** switching language: this could also be a perfectly acceptable solution; having the language widgets *disabled* until a save action is performed looks like a sensible option.

**Comment by manuelbua** [comment]
I just noticed that i choose an unfortunate name for the `title` field inside the repeater (now renamed): this causes parameter confusion and will inject an unwanted page title inside the page title name :).

Obviously this is an issue on its own that i didn't intend to expose in this context.

**Comment by KGE** [comment]
+1
