### ISSUE TITLE
content static page rendered twice

### ISSUE THREAD

**Issue by janvandelaar** [rainlab/pages-plugin#214]
When I make a static page and I add a new item to it in the menu the content of the page is rendered twice. It is rendered on the position where it bolongs and it is rendered directly after the _body_ tag. Can't find a solution for that

**Comment by CptMeatball** [comment]
Could you provide exact steps how to reproduce this problem? Sounds like you have the `{% page %}` variable loaded twice.

**Comment by janvandelaar** [comment]
Hallo Antonie

  * I installed the plugin Pages.
  * Then I  created some pages
  * After that I created my menu and added some items. I connected the
    items to the previous made static pages
  * Then i placed the menu-component in the layout, the menu shows and
    when i click link to a cms page the page renders normal, but when i
    click link to a static page the pagecontent is rendered just after
    the body tag

I habe a copy of this site: http://morff.nl/jasmijn.rar


Met vriendelijke groet,

Jan van de Laar

<http://www.vdlwebdev.nl/>
VDL Webdevelopment :: Webprojecten & Webshopfotografie
Athenestraat 14
2034 EB Haarlem
tel 	: +31 (0)23 5356237
mob 	: +31 (0)611 104 650
email 	: j.vandelaar@vdlwebdev.nl <mailto:j.vandelaar@vdlwebdev.nl>
internet 	: www.vdlwebdev.nl <http://www.vdlwebdev.nl/>
linkedin 	: https://www.linkedin.com/in/janvandelaar





Op 11/15/2016 om 11:24 AM schreef Antonie Hogewoning:

**Comment by manuelbua** [comment]
Since you are probably refering to your `minjawi` theme, it looks like your `default.htm` layout file include both a `{% component 'staticPage' %}` and a `inhoud container: {% page %}`.

**Comment by CptMeatball** [comment]
^that

**Comment by janvandelaar** [comment]
Hallo

Ahh.. now I get it! Thank you very much for your quick response.



Met vriendelijke groet,

Jan van de Laar

<http://www.vdlwebdev.nl/>
VDL Webdevelopment :: Webprojecten & Webshopfotografie
Athenestraat 14
2034 EB Haarlem
tel 	: +31 (0)23 5356237
mob 	: +31 (0)611 104 650
email 	: j.vandelaar@vdlwebdev.nl <mailto:j.vandelaar@vdlwebdev.nl>
internet 	: www.vdlwebdev.nl <http://www.vdlwebdev.nl/>
linkedin 	: https://www.linkedin.com/in/janvandelaar





Op 11/15/2016 om 12:20 PM schreef dudez:
