### ISSUE TITLE
Menu Blog Category item.url ( :page ) currentPage problem 

### ISSUE THREAD

**Issue by LucasZdv** [rainlab/pages-plugin#218]
Hello, 
The URL in the menu items, includes the "currentPage" of pagination :page in blogPosts.

the item.url returns the url with currentPage of pagination 

http://mypage.com/blog/example-category/2

`{"title":"Cultural","url":"http:\/\/mypage.com\/blog\/example-category\/2","code":"","isActive":false,"isChildActive":null,"items":[],"viewBag":{"isHidden":"0","cssClass":"","isExternal":"0"}}`

    <nav class="cr-nav">
        <ul>
        {% for item in staticMenu.menuItems %}
           <li {% if item.isActive or item.isChildActive %}class="active"{% endif %}><a href="{{ item.url }}">{{ item.title }}</a>
              {% if item.items %}
                  <ul>
                      {% for subitem in item.items %}
                          <li {% if subitem.isActive %}class="active"{% endif %}><a href="{{ subitem.url }}">{{ subitem.title }}</a></li>
                      {% endfor %}
                  </ul>
              {% endif %}
           </li>
        {% endfor %}
        </ul>
    </nav>

I think that the has be http://mypage.com/blog/example-category/ (Without number current page)

I sorry, i cant fix it and pull request this

**Comment by Johnzero** [comment]
this problem gos to categories model line 276.you can fix the problem here. CmsPage::url

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
