### ISSUE TITLE
How to use variables from child page (subpage)

### ISSUE THREAD

**Issue by WLepelaar** [rainlab/pages-plugin#219]
I'm completely stuck! Can any one please help me?

**The problem**
I want to use the header picture from a subpage (child page) as category image.

**This is the code i'm using right now in my main layout:**
```
{% import _self as nav %}

{% macro render_menu(items) %}
    {% for item in items %}
        {% for subitem in item.items %} 
            
            <div class="col-sm-4">
                <a href="{{ subitem.url }}">{{ subitem.title }}</a>           
                <pre>{{ item | json_encode }}</pre>
            </div>
            
        {% endfor %}        
    {% endfor %}
{% endmacro %}
```

When i'm reading the item object it only displays: 
Title, Url, Code and ViewBag.

**To set the variables in de child pages i'm using this line:**
`  {variable tab="Header" type="mediafinder" mode="image" name="banner1" label="Banner image 1"}{/variable}`

Can anyone please help me?

**Comment by jan-vince** [comment]
It is contained in the viewBag array:

`{{ child.viewBag.banner1 }}`

*And child pages can be traversed like this:*

`{% for child in page.getChildren %}...{% endfor %}`

**Comment by WLepelaar** [comment]
Thank you very much! It works
