### ISSUE TITLE
Binding widgets to controller

### ISSUE THREAD

**Issue by alxy** [rainlab/pages-plugin#220]
I am questioning, why the (form) widgets are not bound to the Index Controller by default. The only piece of code I can find is: https://github.com/rainlab/pages-plugin/blob/master/controllers/Index.php#L589-L598 , but after some investigation I could not find any condition, when this code runs.

My proposal is to move the ``$widget->bindToController()`` to some more prominent place, for example to this method: https://github.com/rainlab/pages-plugin/blob/master/controllers/Index.php#L365

Is there anything that prevents us from doing this?
The advantage is, that from the controller we have now access to the forms and can extend them programmatically.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
