### ISSUE TITLE
(x-post) Theme layout variables limit 

### ISSUE THREAD

**Issue by LukeTowers** [rainlab/pages-plugin#223]
Moved over from octobercms/october#2579.

@robinbonnes:

I attempted to replicate the issue mentioned by using the following template:

```twig
description = "Test octobercms/october#2579"

[staticPage]
==
{variable name="test_1" label="Test" type="text"}{/variable}
{variable name="test_2" label="Test" type="text"}{/variable}
{variable name="test_3" label="Test" type="text"}{/variable}
{variable name="test_4" label="Test" type="text"}{/variable}
{variable name="test_5" label="Test" type="text"}{/variable}
{variable name="test_6" label="Test" type="text"}{/variable}
{variable name="test_7" label="Test" type="text"}{/variable}
{variable name="test_8" label="Test" type="text"}{/variable}
{variable name="test_9" label="Test" type="text"}{/variable}
{variable name="test_10" label="Test" type="text"}{/variable}
{variable name="test_11" label="Test" type="text"}{/variable}
{variable name="test_12" label="Test" type="text"}{/variable}
{variable name="test_13" label="Test" type="text"}{/variable}
{variable name="test_14" label="Test" type="text"}{/variable}
{variable name="test_15" label="Test" type="text"}{/variable}
{variable name="test_16" label="Test" type="text"}{/variable}
{variable name="test_17" label="Test" type="text"}{/variable}
{variable name="test_18" label="Test" type="text"}{/variable}
{variable name="test_19" label="Test" type="text"}{/variable}
{variable name="test_20" label="Test" type="text"}{/variable}
{variable name="test_21" label="Test" type="text"}{/variable}
{variable name="test_22" label="Test" type="text"}{/variable}
{variable name="test_23" label="Test" type="text"}{/variable}
{variable name="test_24" label="Test" type="text"}{/variable}
{variable name="test_25" label="Test" type="text"}{/variable}
{variable name="test_26" label="Test" type="text"}{/variable}
{variable name="test_27" label="Test" type="text"}{/variable}
{variable name="test_28" label="Test" type="text"}{/variable}
{variable name="test_29" label="Test" type="text"}{/variable}
{variable name="test_30" label="Test" type="text"}{/variable}
{variable name="test_31" label="Test" type="text"}{/variable}
{variable name="test_32" label="Test" type="text"}{/variable}
{variable name="test_33" label="Test" type="text"}{/variable}

<p>{{ test_1 }}</p>
<p>{{ test_2 }}</p>
<p>{{ test_3 }}</p>
<p>{{ test_4 }}</p>
<p>{{ test_5 }}</p>
<p>{{ test_6 }}</p>
<p>{{ test_7 }}</p>
<p>{{ test_8 }}</p>
<p>{{ test_9 }}</p>
<p>{{ test_10 }}</p>
<p>{{ test_11 }}</p>
<p>{{ test_12 }}</p>
<p>{{ test_13 }}</p>
<p>{{ test_14 }}</p>
<p>{{ test_15 }}</p>
<p>{{ test_16 }}</p>
<p>{{ test_17 }}</p>
<p>{{ test_18 }}</p>
<p>{{ test_19 }}</p>
<p>{{ test_20 }}</p>
<p>{{ test_21 }}</p>
<p>{{ test_22 }}</p>
<p>{{ test_23 }}</p>
<p>{{ test_24 }}</p>
<p>{{ test_25 }}</p>
<p>{{ test_26 }}</p>
<p>{{ test_27 }}</p>
<p>{{ test_28 }}</p>
<p>{{ test_29 }}</p>
<p>{{ test_30 }}</p>
<p>{{ test_31 }}</p>
<p>{{ test_32 }}</p>
<p>{{ test_33 }}</p>
```
and was unable to replicate it. Please test that template on your system to see if the issue persists, and if it doesn't then please provide more information about your specific implementation and problem. If it does, please provide more information about your setup (configuration, environment, server specs, etc).

**Comment by robinbonnes** [comment]
Thanks for your support.

It has something to do with indentation.

This does not work:

`            {variable tab="Test" type="text" name="test_1"}{/variable}
            {variable tab="Test" type="text" name="test_2"}{/variable}
            {variable tab="Test" type="text" name="test_3"}{/variable}
            {variable tab="Test" type="text" name="test_4"}{/variable}
            {variable tab="Test" type="text" name="test_5"}{/variable}
            {variable tab="Test" type="text" name="test_6"}{/variable}
            {variable tab="Test" type="text" name="test_7"}{/variable}
            {variable tab="Test" type="text" name="test_8"}{/variable}
            {variable tab="Test" type="text" name="test_9"}{/variable}
            {variable tab="Test" type="text" name="test_10"}{/variable}
            {variable tab="Test" type="text" name="test_11"}{/variable}
            {variable tab="Test" type="text" name="test_12"}{/variable}
            {variable tab="Test" type="text" name="test_13"}{/variable}
            {variable tab="Test" type="text" name="test_14"}{/variable}
            {variable tab="Test" type="text" name="test_15"}{/variable}
            {variable tab="Test" type="text" name="test_16"}{/variable}
            {variable tab="Test" type="text" name="test_17"}{/variable}
            {variable tab="Test" type="text" name="test_18"}{/variable}
            {variable tab="Test" type="text" name="test_19"}{/variable}
            {variable tab="Test" type="text" name="test_20"}{/variable}
            {variable tab="Test" type="text" name="test_21"}{/variable}
            {variable tab="Test" type="text" name="test_22"}{/variable}
            {variable tab="Test" type="text" name="test_23"}{/variable}
            {variable tab="Test" type="text" name="test_24"}{/variable}
            {variable tab="Test" type="text" name="test_25"}{/variable}
            {variable tab="Test" type="text" name="test_26"}{/variable}
            {variable tab="Test" type="text" name="test_27"}{/variable}
            {variable tab="Test" type="text" name="test_28"}{/variable}
            {variable tab="Test" type="text" name="test_29"}{/variable}
            {variable tab="Test" type="text" name="test_30"}{/variable}
            {variable tab="Test" type="text" name="test_31"}{/variable}
            {variable tab="Test" type="text" name="test_32"}{/variable}
            {variable tab="Test" type="text" name="test_33"}{/variable}
            {variable tab="Test" type="text" name="test_34"}{/variable}
            {variable tab="Test" type="text" name="test_35"}{/variable}
`

But this does work:

`
            {variable tab="Test" type="text" name="test_1"}{/variable}
            {variable tab="Test" type="text" name="test_2"}{/variable}
            {variable tab="Test" type="text" name="test_3"}{/variable}
            {variable tab="Test" type="text" name="test_4"}{/variable}
            {variable tab="Test" type="text" name="test_5"}{/variable}
            {variable tab="Test" type="text" name="test_6"}{/variable}
            {variable tab="Test" type="text" name="test_7"}{/variable}
            {variable tab="Test" type="text" name="test_8"}{/variable}
            {variable tab="Test" type="text" name="test_9"}{/variable}
            {variable tab="Test" type="text" name="test_10"}{/variable}
            {variable tab="Test" type="text" name="test_11"}{/variable}
            {variable tab="Test" type="text" name="test_12"}{/variable}
            {variable tab="Test" type="text" name="test_13"}{/variable}
            {variable tab="Test" type="text" name="test_14"}{/variable}
            {variable tab="Test" type="text" name="test_15"}{/variable}
            {variable tab="Test" type="text" name="test_16"}{/variable}
            {variable tab="Test" type="text" name="test_17"}{/variable}
            {variable tab="Test" type="text" name="test_18"}{/variable}
            {variable tab="Test" type="text" name="test_19"}{/variable}
            {variable tab="Test" type="text" name="test_20"}{/variable}
            {variable tab="Test" type="text" name="test_21"}{/variable}
            {variable tab="Test" type="text" name="test_22"}{/variable}
            {variable tab="Test" type="text" name="test_23"}{/variable}
            {variable tab="Test" type="text" name="test_24"}{/variable}
`

So when the variables are indented with for example 12 spaces or more, it doesnt work for 35 variables, but it does work for 24 variables.

I will do some more tests and keep you updated.

**Comment by robinbonnes** [comment]
Did some more testing, and the result is:

How more indented spaces before the variables, how less variables the page can handle.

This doesn't work:

```
                                                                                                                                        {variable tab="Test" type="text" name="test_1"}{/variable}
                                                                                                                                        {variable tab="Test" type="text" name="test_2"}{/variable}
                                                                                                                                        {variable tab="Test" type="text" name="test_3"}{/variable}
                                                                                                                                        {variable tab="Test" type="text" name="test_4"}{/variable}
```

Nor does this:

```
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {variable tab="Test" type="text" name="test_1"}{/variable}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {variable tab="Test" type="text" name="test_2"}{/variable}
```

So it has something to do with processing the spaces before the variables. 


Nor does this:

```
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {variable tab="Test" type="text" name="test_1"}{/variable}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {variable tab="Test" type="text" name="test_2"}{/variable}
```


Also this is not working:

```
{variable tab="Test" type="text" name="test_1"}{/variable}
{variable tab="Test" type="text" name="test_2"}{/variable}

                                                                                                                                                                        {{ test_1 }}
                                                                                                                                                                        {{ test_1 }}
                                                                                                                                                                        {{ test_1 }}
                                                                                                                                                                        {{ test_1 }}
                                                                                                                                                                        {{ test_1 }}
                                                                                                                                                                        {{ test_1 }}
```

So it has something to do with processing the spaces before the variables. Ofcourse the most easy solution is removing the indentation, but sometimes the indentation simply gives an easier overview of the code when the html code has many nested divs.

Maybe it has something to do with the parser? (https://github.com/octobercms/library/blob/master/src/Parse/Syntax/Parser.php)

**Comment by LukeTowers** [comment]
Interesting, I'll take a look into this

**Comment by LukeTowers** [comment]
@robinbonnes Could you give me a bit more information about your setup? I've tried with the following as my layout code, which shouldn't be working according to you, but it does.

```
title = "Public Layout"
description = "Default layout for public pages"

[staticPage]
==
                                                                                                                                        {variable tab="Test" type="text" name="test_1"}{/variable}
                                                                                                                                        {variable tab="Test" type="text" name="test_2"}{/variable}
                                                                                                                                        {variable tab="Test" type="text" name="test_3"}{/variable}
                                                                                                                                        {variable tab="Test" type="text" name="test_4"}{/variable}
                                                                                                                                        
<p>{{ test_1 }}</p>
<p>{{ test_2 }}</p>
<p>{{ test_3 }}</p>
<p>{{ test_4 }}</p>
```

Produces the output 
```


                                                                                                                                        
                                                                                                                                        
                                                                                                                                        
                                                                                                                                        
<p>1</p>
<p>2</p>
<p>3</p>
<p>4</p>
```

I'm unable to assist resolving this issue unless I can replicate it myself, so more information about your setup, including build number, general environment, and any plugins installed would be greatly appreciated.

**Comment by LukeTowers** [comment]
@robinbonnes I'm closing this issue now due to inability to replicate it. Please let me know if you are able to replicate it more reliably and I'll be happy to take another look at it.
