### ISSUE TITLE
Is it possible editor css?

### ISSUE THREAD

**Issue by jonnydevv** [rainlab/pages-plugin#225]
Can't find any css/theme to change font-size, color, list-style-type, etc, to make editor content similar to website.

Thanks in advance

**Comment by CptMeatball** [comment]
You can apply custom styling under `Customize Back-end / Styles`. By applying style to elements in the richeditor field you should be able to match the styling of front and backend.

    .field-richeditor p {
      font-family: 'MyFont', sans-serif;
    }
    ...

NB: Haven't tested it myself though

**Comment by LukeTowers** [comment]
@CptMeatball is correct, you can change those settings via the Customize Backend / Styles settings page in the backend of your site.
