### ISSUE TITLE
Required static page variables not validating

### ISSUE THREAD

**Issue by jordanbrierley** [rainlab/pages-plugin#226]
I have assigned some variables to my static page layouts and set them to required eg. ` {variable name="banner_heading" label="Banner Heading" tab="Banner" type="text" required="true"}{/variable} `  and it correctly puts the red dot to indicate which ones are required however it doesn't actually validate and so the user can submit the form without filling out the required fields

Any advice is much appreciated

Thanks in advance

**Comment by LukeTowers** [comment]
@jordanbrierley This is because backend form validation is handled by the model in October currently. The required property of form fields only puts the red dot right now, but proper form validation of required fields irregardless of a model class being behind the scenes or not is coming.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by datune** [comment]
@LukeTowers Has there been any progress? Any plans for this? Any hints as to how we could add it to this plugin? I'd be willing to look into it...

**Comment by LukeTowers** [comment]
@datune we'd need to implement a validation layer on the Form widget on a per-field basis first
