### ISSUE TITLE
Include snippets inline

### ISSUE THREAD

**Issue by mbaxter91288** [rainlab/pages-plugin#227]
Hi,

I think this is more of a request than an issue, but here goes. I have some "company settings" that I allow users to update via a backend Settings menu. This could be things like primary email address or phone number. I then use these settings in my template files, so if the user updates the company number, for example, that data will update throughout the website.

I had the idea of creating a snippet so users creating pages via the pages plugin could simply insert these settings i.e. the contact number. Then, if the setting was updated at a later date, this would update everywhere. I've got this working where I add the snippet then select from a drop-down the setting I wish to insert, but similar to issue #34, when I add a snippet, it breaks out of the `<p>` tag and goes onto a new line. This is what I have so far:

[Before Screenshot](http://thrivelounge.s3.amazonaws.com/screenshots/before.png)
**Generated Code**
```
<p>Be sure to email us at</p>
<figure data-component="\ThriveLounge\Tenants\Components\TenantSettings" data-inspector-id="inspectorid-426037644753" data-property-setting="email" data-snippet="tenant_settings">&nbsp;</figure>

<p>to get in touch</p>
```

However, it would be great if I could achieve something like this:

[After Screenshot](http://thrivelounge.s3.amazonaws.com/screenshots/after.png)
**Generated Code**
```
<p>Be sure to email us at <span data-component="\ThriveLounge\Tenants\Components\TenantSettings" data-inspector-id="inspectorid-426037644753" data-property-setting="email" data-snippet="tenant_settings"></span> to get in touch</p>
```

Hope something like this is possible as I feel this would add some great opportunities. Please let me know if any of the above doesn't make sense.

Cheers,
Mat

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
