### ISSUE TITLE
Rearranging snippets

### ISSUE THREAD

**Issue by acasar** [rainlab/pages-plugin#228]
Is anyone else having an issue with rearranging snippets using drag/drop? For example - I have 3 snippets on this page:

![image](https://cloud.githubusercontent.com/assets/6329543/22389449/d5fe3476-e4e5-11e6-85c1-261122283fe9.png)

And there is no way to get "Breadcrumbs" to the top without editing the source code. Maybe this is an issue of Froala editor and should be opened there?

**Comment by daftspunk** [comment]
Dragging the snippets seems to rely on the cursor for a drop position, since there is no cursor at the start of the document it won't drop there. We'll try updating Froala to latest and see if it fixes it.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
