### ISSUE TITLE
Dynamic Syntax Fields of repeater type produce error with translations in builds > 382

### ISSUE THREAD

**Issue by KGE** [rainlab/pages-plugin#229]
This issues involves october cms core, pages and translate plugin so I'm not sure if this is the right repo for this issue.

**Issue Summary:**

Switching languages ( Back and forth ) in a repeater widget ( added via Syntax Fields in layout ) when creating a new static page causes an unexpected error. ( Error is still there when editing an existing page and switch the repeater language )

**Reproduce Steps**
- Install the latest version of october cms ( Or any > 382 )
- Install static pages and translate plugin
- Configure another language in settings -> Manage Languages ( So that you have 2 languages )
- Create a new layout with a Syntax Fields of repeater type like
   `{repeater name="documents" prompt="Click here to add documents" tab="Documents"}
	{variable type="text" name="title" label="document name" placeholder="Name" }{/variable}
    {/repeater}`
- Add static page component to the layout
- Create a new static page that use the layout.
- Try add an item in the Document repeater
- [OPTIONAL] Save.
- Switch language in the repater widget
- Switch language back
- get the `"Call to undefined method October\Rain\Halcyon\Builder::hasRelation()" on line 776 of /vendor/october/rain/src/Halcyon/Builder.php` error

**expected behavior**
- When creating a new static page using a repeater field added via Syntax Fields in layout you should be able to switch language without getting errors.

**October build**
 396 ( Or any > 382 )

**Pages Plugin**
1.2.13

**Translate Plugin**
1.2.10

**On build 382 works as expected**

**Comment by manuelbua** [comment]
I'm hitting the same problem: any version higher than 382 will produce that error under the same circumstances you describe.

**Comment by KGE** [comment]
Duplicate of [issue # 216 in translate plugin](https://github.com/rainlab/translate-plugin/issues/216).
Seems to work as expected on 398 so I close the issue.
