### ISSUE TITLE
Repeater

### ISSUE THREAD

**Issue by stefanreimert** [rainlab/pages-plugin#230]
In the repeater i have different options and i need to count the arrays.
Is there and easy way to do this?
I only want the counts of the variable...

**Comment by LukeTowers** [comment]
in Twig you can use `|length` to achieve this. http://twig.sensiolabs.org/doc/2.x/filters/length.html

**Comment by stefanreimert** [comment]
Yeah but i need to have the array number like 1,2,3,4,5,6
This only gives me the total lenght

**Comment by daftspunk** [comment]
You probably want the `{{ loop.index }}` variable available inside every `{% for %}` tag. Please read the documentation as it can answer most of your questions.

http://octobercms.com/docs/markup/tag-for
