### ISSUE TITLE
richeditor.isCodeViewActive is not a function

### ISSUE THREAD

**Issue by nerijunior** [rainlab/pages-plugin#232]
```
pages-snippets.js:22 Uncaught TypeError: richeditor.isCodeViewActive is not a function
    at HTMLTextAreaElement.<anonymous> (pages-snippets.js:22)
    at HTMLDocument.dispatch (jquery.min.js?v398:3)
    at HTMLDocument.r.handle (jquery.min.js?v398:3)
    at Object.trigger (jquery.min.js?v398:3)
    at HTMLTextAreaElement.<anonymous> (jquery.min.js?v398:3)
    at Function.each (jquery.min.js?v398:2)
    at n.fn.init.each (jquery.min.js?v398:2)
    at n.fn.init.trigger (jquery.min.js?v398:3)
    at RichEditor.onSetContent (build-min.js?v398:562)
    at HTMLTextAreaElement.dispatch (jquery.min.js?v398:3)
```
The error line:

````
$(document).on('setContent.oc.richeditor', '.field-richeditor textarea', function(ev, richeditor) {
            if (!richeditor.isCodeViewActive()) {
                self.initSnippets(richeditor.getElement())
            }
        })
```

**Comment by yapsr** [comment]
Possible duplicate of https://github.com/octobercms/october/issues/2484

**Comment by nerijunior** [comment]
@yapsr thanks by the fast answer and sorry the duplicated issue.

**Comment by LukeTowers** [comment]
@yapsr and @nerijunior Have you guys updated to the latest versions and does the issue persist?

**Comment by daftspunk** [comment]
I had this issue on an old copy of October, it was because I didn't update the core but updated the plugin. Perform an update and it should be fixed. The `isCodeViewActive` function is a new API in the core.

**Comment by nerijunior** [comment]
@LukeTowers Yep plugin and backend updated, to solve we need to disable the edgeUpdates

**Comment by daftspunk** [comment]
This should no longer be an issue with or without edgeUpdates?

**Comment by yapsr** [comment]
I have updated octobercms with "composer update" and reinstalled the plugin "rainlab.pages" from the backend system updates panel and it looks it is solved now. My config setting "cms.edgeUpdates" is set to false.
