### ISSUE TITLE
Static Pages plugin puts content in Theme folder - very bad CMS practice

### ISSUE THREAD

**Issue by seffw** [rainlab/pages-plugin#237]
The whole point of a CMS is to detach content from theme.

This plugin undoes that. This has no sense. Pages and Content are not layout.

This should be classed as a bug and needs fixing. Any hints on where to start to fix this?

**Comment by daftspunk** [comment]
You could build your own plugin.

**Comment by seffw** [comment]
Closed? 

Sure I can make a plugin. But that doesn't really explain the bad architecture. How can this be by design? You would really prefer content within theme rather than separated? 

As it turns out this is beyond the Static Pages plugin as CMS content is stored in Theme also. This is the wrong approach and goes against the nature of what CMS is.  Most importantly I think it will be hindering the progress of October because many users we jump ship as soon as they discover this (as separating content and code / content and theme is a key CMS selling point)

**Comment by daftspunk** [comment]
Hmmm, it is possible you might be mistaking a theme for a skin. There is a pretty big distinction in October:

- A theme stores the entire front-end structure, including static content.
- A skin defines how that structure should look (Halloween skin, Christmas skin, etc.)

Hopefully this is the source of your confusion. This is closed because it is not acknowledged as an issue, it is by design. It's not a bug, it's a feature and so forth. Please spend some more time with the platform and it should make more sense. I wish I had more time to explain it, sorry.

**Comment by seffw** [comment]
Ok so I'll finish with this post to clarify my point better. As far as I know, a site built which then has the theme removed will lose all content, and changed, the content is not available in the backend to the new theme.

The CMS assumption (in every other system I know) is that content is separated, and changes to themes don't affect backend availibility of content (and if linked to an area which is not part of a new theme or layout, it is not lost but just becomes unlinked). 

There are some really good functional and layout ideas in October, but content preservation and availability within the admin, regardless of actions performed, is vital for any CMS system (of flat file or static site generator).

At least, if by design, make it a thing about October if a really good reason for this can be shown. That might differentiate it, but also make users aware before they discover it at the wrong time. I think October could be a much more popular system with a much more active forum if it was clearer how and why it is so different to the standard CMS approach

**Comment by wildcats1369** [comment]
Pages are supposed to be unique with every theme, even if you have a standard pages chances are you will still edit them to cope with the new design.

however

You can set up your blog post to be pages, just create a page for them in the cmd->pages and you can set 
/:slug on its parameter set the design and you can have pages that have a standard design. 

1. create a new page names pages.htm
2. place the post component on them and edit the theme.
3. set the slug as /:slug
4. I create a pages category in blog and fill it with the pages i want.
5. create the menu pointing to the blog url.

![image](https://user-images.githubusercontent.com/8967830/30921635-85d05b2e-a3d9-11e7-9e99-e409d9e7f4f1.png)

this is not the best workaround but at least it works for me if want to go on that route.
this is the result of that. notice the url of slug is from root.
![image](https://user-images.githubusercontent.com/8967830/30921907-38babe78-a3da-11e7-970b-1526cd966120.png)

**Comment by LukeTowers** [comment]
@daftspunk further to our earlier discussion about storing page content in the database
