### ISSUE TITLE
Head Placeholder

### ISSUE THREAD

**Issue by mbaxter91288** [rainlab/pages-plugin#239]
Hi,

I am trying to include my Zendesk help widget into every backend page and I've achieved this with the below code:
```
Event::listen('backend.page.beforeDisplay', function($controller, $action, $params) {
    $controller->addJs('/plugins/thrivelounge/support/assets/js/zendesk.js');
});
```
I would also like to configure this and as per the [Zendesk documentation](https://developer.zendesk.com/embeddables/docs/widget/zesettings#suppress) I need to include a script like below:
```
<script type="text/javascript">
window.zESettings = {
  webWidget: {
    chat: {
      suppress: true
    },
    helpCenter: {
      suppress: true
    }
  }
};
</script>
```
I've done this by updating the previous code snippet to:
```
Event::listen('backend.page.beforeDisplay', function($controller, $action, $params) {
    Block::append('head', $controller->makePartial('$/thrivelounge/support/partials/zendesk-settings.htm', ['settings' => Settings::instance()->getZendeskOptions()]));
    $controller->addJs('/plugins/thrivelounge/support/assets/js/zendesk.js');
});
```
I would like to be able to use an October settings page to enable and disable features, which is why I am rendering a partial and passing the settings. This is also why I can't use the normal `$controller->addJs...` like I have with the other file. This seems to work for all backend pages, expect this plugin and the Media Library. With some help from @LukeTowers I stumbled across this within the `plugins/rainlab/pages/controllers/index/index.htm` file:
```
<?= Block::put('head') ?><?= Block::endPut() ?>
```
This is also within the Media Library controller page too. Removing this line resolves my issue.

Why is this here, I guess it has a reason? Can it be removed or is there another way to inject a dynamic `<script>` tag to the head of each backend page?

Any help @daftspunk would be greatly appreciated.

Regards,
Mat

**Comment by LukeTowers** [comment]
@mbaxter91288 how did you eventually resolve this?

**Comment by mbaxter91288** [comment]
@LukeTowers by removing the below from the mentioned controller files.
```
<?= Block::put('head') ?><?= Block::endPut() ?>
```
Like I mentioned, not really sure what this did so this was more of a question than anything else?

**Comment by LukeTowers** [comment]
Isn't that going to be replaced on the next update though?

**Comment by mbaxter91288** [comment]
Not sure :-/

**Comment by daftspunk** [comment]
Unfortunately I didn't write this code, it was by @alekseybobkov. It looks like it might be a mistake in the code. Are there any negative consequences from removing it?

**Comment by LukeTowers** [comment]
@daftspunk the only think that I can think of that will happen if we remove it is resources inserted into `head` from plugins in the backend would now be inserted on the mediamanager and StaticPages pages, but that would be the plugin's fault if it conflicted and I'm not sure what exactly what would cause it to conflict

**Comment by daftspunk** [comment]
@alekseybobkov Can you confirm that this line of code was a misprint, or intentionally purposed to null all injected assets from these pages:

- [CMS index view](
https://github.com/octobercms/october/blob/9565565865306b163ab17c6dbb0ddee29d8ed63d/modules/cms/controllers/index/index.htm)
- [Media index view](https://github.com/octobercms/october/blob/9565565865306b163ab17c6dbb0ddee29d8ed63d/modules/cms/controllers/media/index.htm)

Code in question:
```
<?= Block::put('head') ?><?= Block::endPut() ?>
```

**Comment by daftspunk** [comment]
Confirmed with Alexey -- this can be safely removed.

**Comment by LukeTowers** [comment]
@mbaxter91288 could you make a PR for this and the media manager on the dev branch to fix this?
