### ISSUE TITLE
It can't find any layout

### ISSUE THREAD

**Issue by dunets** [rainlab/pages-plugin#241]
It can't find any layout
![image](https://cloud.githubusercontent.com/assets/6217617/23955824/f69edc0e-0992-11e7-894b-e357465306dd.png)

But there are a layout:
![image](https://cloud.githubusercontent.com/assets/6217617/23955856/0c9874de-0993-11e7-9c8c-ec114f719a97.png)

And to use the layout I need to add the code manually:
![image](https://cloud.githubusercontent.com/assets/6217617/23955895/224a61b6-0993-11e7-9f29-04a950247567.png)

And it works... but it's bad for me... because after any change on a CMS it refresh that part of code and removes `layout = "default"`

**Comment by dunets** [comment]
ok... I found how to solve it here:
https://octobercms.com/blog/post/getting-started-static-pages

@daftspunk I'm working with OctobertCMS about a month and I didn't know that site has tutorials.. why do you don't put that on a menu? and some URL to these tutorials on a Documentation of the plugin... you will save the time of many people...

And thanks!

**Comment by LukeTowers** [comment]
@dunets See https://octobercms.com/support/article/ob-22

We could probably add our blog posts to that support article though to make it easier to find.

**Comment by LukeTowers** [comment]
Actually, this would be a better link to use: https://octobercms.com/support/articles/tutorials
