### ISSUE TITLE
Syntax fields fileupload

### ISSUE THREAD

**Issue by Nyorai** [rainlab/pages-plugin#242]
I've been looking a dynamic syntax fields and they are very powerful, but I can't seem to get the fileupload field to do anything. I've added the following to a layout

`{fileupload name="myFile" label="My File" tab="File"}{/fileupload}`

But it doesn't show up when editing a page that uses the layout or when viewing the page. I've had great success using the other field types so I'm not sure what is happening.

**Comment by LukeTowers** [comment]
I'm not sure the fileupload widget is supported, since it works using database attachments and the pages are stored as content files, not database records. You might have better luck with the mediafinder widget instead.

**Comment by Nyorai** [comment]
Ah right, that makes sense. I'll give it a try.

**Comment by Nyorai** [comment]
Perfect. Thanks!
