### ISSUE TITLE
Documentation missing Custom-Page-FIelds Dropdown 

### ISSUE THREAD

**Issue by gbaumeister** [rainlab/pages-plugin#246]
It is possible to create custom-form-fields of type as described here in issue: https://github.com/rainlab/pages-plugin/issues/69

Unfortunately in the documentation it is not described how the options format must look like. 

Hope this is the right spot to request an update in the plugins documentation.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
