### ISSUE TITLE
Snippet from partial is not saved

### ISSUE THREAD

**Issue by tplessis** [rainlab/pages-plugin#25]
Hi guys,

I'm unable to save my freshly created snippet from partial. It says it was saved but my snippet does not appears in the snippets list from the pages backend. :/

**Edit :**

Ok it works if i manually add the minimimum required viewBag part in my partial snippet file,  like this :
```
[viewBag]
staticPageSnippetCode = "services"
staticPageSnippetName = "Services"
```

**Comment by daftspunk** [comment]
This should be fixed now, there was a bug saving partials when no components were added
