### ISSUE TITLE
Nested syntax field repeaters in a layout only render content fields

### ISSUE THREAD

**Issue by MattPurland** [rainlab/pages-plugin#255]
For example if a layout has the following:

```
{repeater tab="Books" name="books" prompt="Add another book"}
    {text name="title" label="Title"}{/text}

    {repeater name="authors" label="Authors" prompt="Add another author"}
        {text name="name" label="Name"}{/text}
    {/repeater}
{/repeater}
```

The inset repeater (authors) only renders a text field, not an actual repeater field containing a text field

**Comment by AugmentBLU** [comment]
I tried the above code and can confirm that the same happens. 

I also tried the following code which nearly works but the secondary repeater has no fields. I tried manually inputting the result in the static page viewBag without luck.

```
{repeater name="panels" prompt="Add another panel" tab="Panels"}
    {variable type="text" name="panel_title" label="Title"}Title{/variable}
    {variable type="repeater" name="ext" prompt="Add secondary panel"}
        {variable type="text" name="ext_title" label="Title"}Title{/variable}
    {/variable}
{/repeater}
```

Nested repeaters would be useful on static pages, they work well in custom plugins so hopefully it can be sorted for this plugin.

**Comment by LukeTowers** [comment]
@MattPurland @AugmentBLU does https://github.com/octobercms/library/pull/235 fix this issue for you?

**Comment by MattPurland** [comment]
@LukeTowers Afraid not, same error:
`A widget with class name 'formPageb60415bb486b3eb849523d114f98317f595d017f8f80eViewBagTeam' has not been bound to the controller" on line 523 of /<path>/modules/backend/Classes/Controller.php`

**Comment by MattPurland** [comment]
Afraid not. Using @AugmentBLU's example the embedded repeater is empty

**Comment by LukeTowers** [comment]
@mattpurland what about using yours?

**Comment by MattPurland** [comment]
@LukeTowers same, unfortunately

**Comment by LukeTowers** [comment]
Ah well, it was worth a shot anyways. Feel free to dig into it yourself and see if you can find the reason why it's not working.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by MattPurland** [comment]
@LukeTowers I'm thinking of looking in to this myself as we're looking into alternatives to WordPress based on Laravel - October is still the closest by far, but nested repeaters are a must for us. Can the lead devs point me in the right direction at all?

**Comment by LukeTowers** [comment]
This is handled by the SyntaxParser class I believe. See http://octobercms.com/docs/services/parser#dynamic-syntax-parser

Called in RainLab.Pages here, the code for it will be in https://github.com/octobercms/library
https://github.com/rainlab/pages-plugin/blob/master/classes/Page.php#L443

That'd be great if you could provide a PR @MattPurland!

**Comment by datune** [comment]
@MattPurland Any progress by chance?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by tok3** [comment]
is this fixed in the meanwhile, I can't find any solution for it ?

**Comment by w20k** [comment]
@tok3 don't think so was abandoned. You could provide a PR to fix it.
