### ISSUE TITLE
Stored dropdown values from a inserted snippet contains index

### ISSUE THREAD

**Issue by TimFoerster** [rainlab/pages-plugin#257]
When printing a dropdown value in a snippet, the variable contains the index, but not the value.

### Create snippet
```
[viewBag]
snippetCode = "snippet"
snippetName = "name"
snippetProperties[a][title] = "a"
snippetProperties[a][type] = "dropdown"
snippetProperties[a][default] = ""
snippetProperties[a][options][] = "a"
snippetProperties[a][options][] = "b"
snippetProperties[a][options][] = "c"
snippetProperties[a][options][] = "d"
snippetProperties[a][options][] = "e"
==
{{ a }} 
```
### Create page and include snippet
select a value 'e', result:
```
[viewBag]
title = "a"
url = "/a"
is_hidden = 0
navigation_hidden = 0
==
<figure data-property-a="4" data-snippet="snippet">&nbsp;</figure>
```

## Expected behavior

After requesting page '/a' you should see 'e' as value.

## Actual behavior

You see '4' on the page.

## Reproduce steps

See above

## Version

Pages: 1.2.16
Ocms: dev branch

**Comment by TimFoerster** [comment]
Additional question to it, should the included snippet contains the value or the index?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
