### ISSUE TITLE
Adding a locale picker when using Rainlab.Translate

### ISSUE THREAD

**Issue by priitperna** [rainlab/pages-plugin#258]
It not very user-friendly if the language of the fields must be changed one at a time (or even with the CTRL modifier).

One solution would be to add a native language picker in case Rainlab.Translate plugin is enabled.

Something like this:
![image](https://cloud.githubusercontent.com/assets/2284196/25944869/81da09c4-364d-11e7-9edf-d1032e53d7af.png)

The quickest solution would be to just fire a view event in the page form so the form view could be extended with a custom locale picker.
For example adding this in the _form_page.htm file after the form open tag:
`<?= $this->fireViewEvent('rainlab.pages.extendPageFormView') ?>`

Then at some point maybe the picker is added to the Rainlab.Translate plugin. Meanwhile it would be possible to create ones on picker.

**Comment by LukeTowers** [comment]
Good idea, although I think a better place for extensibility would simply be to grant access to the FormWidget that gets built for the page, that way we can just hook directly into that FormWidget's events and other extensibility features.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
