### ISSUE TITLE
Create a connection between static pages with a dropdown

### ISSUE THREAD

**Issue by stefanreimert** [rainlab/pages-plugin#266]
What i want to do is to be able to create a dropdown field that shows all my pages in the static pages plugin.

When i select a page i need to be able to get all the content from the selected page...

Is something like this possible with static pages?

**Comment by jeremymouton** [comment]
Here's an unofficial branch with this implementation.
https://github.com/aspendigital/pages-plugin/tree/page-picker-widget

There might be a few other things in that branch that haven't been merged with the official release yet, but you can look at the last commit to see how it's done. https://github.com/aspendigital/pages-plugin/commit/cc459c584fe57915b364280e7ae4675bd809a53a

`{variable name="page_dropdown" label="Link" type="staticpagepicker"}{/variable}`

**Comment by LukeTowers** [comment]
See https://github.com/rainlab/pages-plugin/pull/259, if you have any input on that pull request, please add it as a comment to the pull request.
