### ISSUE TITLE
Creating a menu : CMS pages aren't being loaded into 'All Blog Categories'

### ISSUE THREAD

**Issue by gtmeteor** [rainlab/pages-plugin#268]
When creating a Menu, I can see my CMS pages when I create a link directly to CMS page:
![image](https://user-images.githubusercontent.com/11475514/27324362-a98f49dc-55ad-11e7-92e3-adbec322665d.png)
However, when I try to do the same for All Blog Categories - the CMS page list is empty:
![image](https://user-images.githubusercontent.com/11475514/27324389-c438b87c-55ad-11e7-9d9f-c520e57e1509.png)
Is it something I'm doing wrong or... ?

**Comment by jan-vince** [comment]
I guess you probably don't have blogCategories component in your CMS page.

**Comment by LukeTowers** [comment]
You need to have a `blogPosts` component setup with a category filter that will pull information from a URL parameter on a CMS page before that CMS page will be eligible to be displayed in that list. https://github.com/rainlab/blog-plugin/blob/master/models/Category.php#L125-L128

Think about it this way, how is this menu item supposed to pass information about it wants to be displayed to the CMS page if the CMS page isn't configured to listen to that information first?
