### ISSUE TITLE
Removing the Content box

### ISSUE THREAD

**Issue by tillathenun** [rainlab/pages-plugin#270]
Apologies if this has been mentioned before - I couldn't find an issue here relating to it - but I'd really like to disable/hide/move the Content box so it's less prominent.

I have Custom Page Fields set up as normal textareas so my client can't muck up the design so the Content box isn't required (and just confuses my client, really).

I'm sure there's a way of doing this by creating a custom plugin or something but I'm struggling to find documentation.

Many thanks in advance.

**Comment by jan-vince** [comment]
You are looking for ````useContent```` property.

*Pages documentation in [plugin page](http://octobercms.com/plugin/rainlab-pages) is not in sync with version on [GitHub documentation](https://github.com/rainlab/pages-plugin#static-pages).*

**Comment by tillathenun** [comment]
Perfect! I didn't have edgeUpdates on so I wasn't seeing it in the version I had. Thanks!
