### ISSUE TITLE
Error after saving and breaks plugin and website

### ISSUE THREAD

**Issue by kevinvermeulenn** [rainlab/pages-plugin#274]
Hi, 

I was busy to create content for my website in this plugin. 
I added two new items within my menu and have given them the structure of a URL menu item.

While saving it gave me an error. I refresh my page and now I am getting this message back when I want to open the plugin: 
`Indentation problem at line 12 (near " }").`

```
$data[] = substr($this->currentLine, $newIndent);
            } elseif (0 == $indent) {
                $this->moveToPreviousLine();
  
                break;
            } else {
                throw new ParseException('Indentation problem.', $this->getRealCurrentLineNb() + 1, $this->currentLine);
            }
        }
  
        return implode("\n", $data);
    }
```

I don't know what happened but it also breaks my website too with the same message:
http://2017.bmichecken.nl/

Need some help to fix this.

**Comment by jan-vince** [comment]
Check ````meta/menus/main_menu.yaml```` file in you theme folder.

It can be corrupted.

**Comment by kevinvermeulenn** [comment]
@jan-vince I've removed the file in the theme folder as you mentioned. 
The website is working right now but the backend isn't yet.

**Comment by jan-vince** [comment]
What error you get?

**Comment by kevinvermeulenn** [comment]
@jan-vince The same error as I mentioned above.

**Comment by jan-vince** [comment]
Try to move .yaml files from meta folder - this can lead you to the one that is corrupted.

**Comment by kevinvermeulenn** [comment]
Unfortunately, it is still not working.
As you can see the website is working. Even with the navigation of blog categories. 
The main navigation is removed in the meta folder right now.

**Comment by jan-vince** [comment]
Can you post last error from /storage/system.log?

**Comment by kevinvermeulenn** [comment]
Hi @jan-vince ,
I've placed the complete log file here: http://2017.bmichecken.nl/system-log
Because I don't know what error you search for.

**Comment by jan-vince** [comment]
Looks like a problem right in ````static-pages.yaml````.

Have you tried to move this file out from a ````meta```` directory? 

*Or maybe try to rename ````meta```` directory and create new one empty.*

**Comment by kevinvermeulenn** [comment]
@jan-vince Thank you! 
It solves the problem. Only thing I've to do is to create all the build pages and menus again. Lucky this one was in the development stage.
