### ISSUE TITLE
Syntax Fields not appearing when layout is in a directory

### ISSUE THREAD

**Issue by eleohner** [rainlab/pages-plugin#280]
I noticed that the variables don't appear client-side in the Pages tab when the layout is nested in a directory.

For example, they appear fine if they're like follows: layouts/page-layout.htm

however, they don't when they are like: layouts/main-pages/page-layout.htm

I couldn't find any other references to this problem, so I'm assuming it's a bug.

Thanks!

**Comment by LukeTowers** [comment]
@fuchsli does October itself support sub-directory layouts?

**Comment by fuchsli** [comment]
It doesn't throw an exception when I make sub-directory layouts, so I'm assuming making them is valid.

**Comment by fuchsli** [comment]
Here's an image for verification: 

![sublayouts-screenshot](https://user-images.githubusercontent.com/17093330/29745927-b35601b8-8a96-11e7-891d-b0e2133f11d6.png)

**Comment by LukeTowers** [comment]
Just because it doesn't throw an exception doesn't mean it's actually supported. 

What are the steps you take to create a layout in a sub directory?

**Comment by fuchsli** [comment]
That is an entirely fair point. But it creates directories for it just as it does in all of the other CMS items.

![layout-directory](https://user-images.githubusercontent.com/17093330/29832649-e3da9bb0-8cb6-11e7-8a00-f070fa7a0ea8.png)

Saving this produces a nested layout and makes things much easier in terms of organization.

I can access the nested layouts just fine in the Pages plugin. It's just the variables don't get passed over.

For instance, say I want clients to be able to edit contents on the homepage with the static pages plugin. The only option to do that is to copy the CMS page code into a layout and throw in the pages component. Now multiply that by about 5 or 10 for custom pages that I want the the user to be able to control with variables. Being able to nest these layouts against a layout the client would use frequently (something like 'generic-page-layout') would be valuable.

**Comment by LukeTowers** [comment]
So you're saying that when you have page specific layouts that you would like to organize in sub directories the Static Page variables don't get saved correctly to them?

**Comment by fuchsli** [comment]
That's exactly it. 

{variable name="stuff"...}{/variable} works in just "new-layout" but does not show up at all in "layout-directory/new-layout"

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by bennothommo** [comment]
Verified working as of October build 451 and RainLab Pages Plugin release 1.2.20.

Please feel free to re-open this issue if the problem still persists.
