### ISSUE TITLE
Does not display the available templates

### ISSUE THREAD

**Issue by coder1coder** [rainlab/pages-plugin#285]
I installed the plugin. When creating a new page does not display the available templates.

_classes\Page.php (354 string)_
**if (!$layout->hasComponent('staticPage')) {**
```
public function getLayoutOptions()
    {
        $result = [];
        $layouts = Layout::listInTheme($this->theme, true);

        foreach ($layouts as $layout) {
            if (!$layout->hasComponent('staticPage')) {
                continue;
            }
```

**Comment by LukeTowers** [comment]
Do you have any available templates? Only templates that have the staticPage component included on them are actually able to be used by this plugin.

**Comment by coder1coder** [comment]
Yes, of course, the available templates there. Pay attention to the condition. Continue to run code if the template does not have component.

**Comment by LukeTowers** [comment]
No need to be snarky. This code is doing what it is supposed to. `continue;` tells PHP to ignore the rest of the code in this iteration of the loop and skip to the next iteration; therefor passing over the current template as invalid to use. http://php.net/manual/en/control-structures.continue.php

**Comment by jan-vince** [comment]
@coder1coder Can you put here your layouts files?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
