### ISSUE TITLE
"Invalid argument supplied for foreach()" on line 129 of PageList.php

### ISSUE THREAD

**Issue by zooks** [rainlab/pages-plugin#287]
I got this error in backend when I tried to delete a page:

> "Invalid argument supplied for foreach()" on line 129 of …/public_html/plugins/rainlab/pages/classes/PageList.php

I've just found what causes this unhandled error: it's ```blog: null``` in static-pages.yaml

**Comment by daftspunk** [comment]
Not sure how you managed to get a null value in there but an expression has been added to account for it.
