### ISSUE TITLE
{{ ''|page }} does not work on static pages

### ISSUE THREAD

**Issue by alan-derua** [rainlab/pages-plugin#289]
I need a full url for OpenGraph's `og:url`. `{{ ''|page }}` works for cms pages, but not for static pages. 

I read the plugin doc and couldn't find anything about getting full url. Any suggestions?

**Comment by jan-vince** [comment]
Try ````|staticPage````.

**Comment by alan-derua** [comment]
@jan-vince Doesn't work at all on both types

**Comment by jan-vince** [comment]
When I create Static page with name 'test' and URL ````/test````

* this ````{{'test'|staticPage}}```` gives me a full URL
* and this also ````{{page.id|staticPage}}````

Can you give it a try?

**Comment by alan-derua** [comment]
Thanks for the `{{page.id|staticPage}}` hint! 

`{{ (''|page == "") ? page.id|staticPage : ''|page }}` solved my problem.
