### ISSUE TITLE
Menu item dosen't work after I add a subitem to it

### ISSUE THREAD

**Issue by Sifizu** [rainlab/pages-plugin#291]
Hello! I work on a project in October CMS. I'm a newbie in this CMS, and my problem is, when I add a submenu item to an item in my menu, the original menu item become unable to open by left click. I can only open it by mouse wheel click and open it a on a new page. Can anybody help me with this?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
