### ISSUE TITLE
Snippet overrides not working properly

### ISSUE THREAD

**Issue by trnikon** [rainlab/pages-plugin#295]
When adding 2 or more snippets of the same type on the same static page, the `data-snippet` alias changes. This breaks the template override because the app is looking for a folder that isn't there. As a result, only the first snippet renders using the override and the others use the default template.

EDIT: This only seems to happen with snippets coming from components, as when adding multiple snippets coming from partials on the same page does not change their `data-snippet` property.

**Comment by LukeTowers** [comment]
Are you able to dig deeper into this and see if you can make a PR to fix the issue?

**Comment by trnikon** [comment]
I think it has to do with the way OctoberCMS core uses aliases to refer to component instances. I will look into it but I don't think there is a simple solution

**Comment by LukeTowers** [comment]
@trnikon I believe there is an issue somewhere for allowing aliased components to still pull overrides from the default component override partial folder, so it's not entirely a lost cause.

**Comment by LukeTowers** [comment]
A solution could be one of two things:
1. The RainLab.Pages plugin ignores the alias set automatically by having more than one snippet on a page and pulls from the original override instead (perhaps still allowing some way to ignore that)
2. OctoberCMS itself does the same as above. I'm not a fan of this, as it could be a breaking change.

**Comment by Rike-cz** [comment]
@LukeTowers Was there any move to solve this issue since?

**Comment by LukeTowers** [comment]
@Rike-cz nope. Generally if it's not an issue that I experience in my usage of October and no one feels like paying for me to address it I'm not likely to investigate any further or write any code to implement it unless it's a major issue.

I'm always willing to review PRs or implement stuff in exchange for bounties however.

**Comment by Rike-cz** [comment]
@LukeTowers ok, thanks. I solved it with `MyComponent::onRender` where the same theme partial is called regardless of current component alias. Change current behavior is easy, it's only about [this line](https://github.com/octobercms/october/blob/2dbc56aead2ef2355135349b83860457f48f6235/modules/cms/classes/ComponentPartial.php#L104). But sensible solution needs deeper philosophical changes about partials rendering.

**Comment by Rike-cz** [comment]
@LukeTowers Draft of my idea: https://github.com/Rike-cz/october/commit/afd4045a44609b16e5baa9adac62f6b6b71c202f

**Comment by mrdrarek** [comment]
```
public function defineProperties()
    {
        return [
            'template_alias' => [
                'title'             => 'partial_override_alias',
                'description'       => '',
                'default'           =>  '',
                'type'              => 'string'
            ]
        ];
    }

public function onRender()
    {
        ($this->property('partial_override_alias')) ?  $this->alias = $this->property('partial_override_alias') : '';
   }
```

**Comment by Rike-cz** [comment]
@mrdrarek I also tried this but overriding alias directly causes that [this code](https://github.com/octobercms/october/blob/2dbc56aead2ef2355135349b83860457f48f6235/modules/cms/classes/Controller.php#L989) is looking for the same component twice and more (how many times is this component used in the same page).

**Comment by damsfx** [comment]
> As a result, only the first snippet renders using the override and the others use the default template.

Exactly the same problem !  
A component declared as snippet, used several times in the same page, only the first iteration takes care of the theme's partial dedicated to the component, the following ones use the default partial of the component.

Do any of you have a solution, even a temporary one, to correct this problem?

**Comment by LukeTowers** [comment]
@damsfx the temporary one would be to duplicate your override folder for each of the snippet aliases used.

**Comment by damsfx** [comment]
@LukeTowers ...  So simple that I missed it. Shame on me.   ¯\\\_(ツ)\_/¯

On the other hand we agree that it is really the worst solution, it does not offer any dinamysm to the final user, unless he has access to the CMS part of the backend.

**Comment by damsfx** [comment]
@LukeTowers   
On a customer's project I created snippets from component for a view on an organisational chart model.  
I created 6 symlinks in my partials folder thinking I was safe.  
Well no, the customer used the snippet 7 times in the page; as a result I got a call to ask why a simple addition didn't have the same effect on the page.

From the point of view of considering the CMS part of OctoberCMS as a reserved domain for the developer, and to leave only one access to the Pages plugin for the customer; it doesn't work with the same flexibility anymore.

I can no longer keep this solution, I will modify my component in the same way as @mrdrarek to take into account an additional property to define the value of the partial to be used.

**Comment by daftspunk** [comment]
This is fixed in the latest version of October CMS where the alias and the default alias are both checked. However, keep in mind overriding partials have a very limited set of use cases. Read the documentation to learn more: https://docs.octobercms.com/3.x/cms/themes/components.html#customizing-default-markup
