### ISSUE TITLE
Single URL (in multiple languages) with Rainlab.Translate?

### ISSUE THREAD

**Issue by nephthys** [rainlab/pages-plugin#299]
Hi,

I have two languages: EN (default) and FR.

I choose the URL "test-en" in English, and in a second time I choose the URL "test-fr" in French.

This is the last registered URL ("test-fr") that overwrites the previous URL in English. Is this normal behavior? Because for me it looks like a bug.

It might be more interesting to change the language of the form in one breath, now there you have to change the language of the title, then the URL, then the content.

Thanks.

**Comment by LukeTowers** [comment]
Feel free to dig deeper into this and make a PR

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
