### ISSUE TITLE
Problem with Menu

### ISSUE THREAD

**Issue by retep007** [rainlab/pages-plugin#30]
There is a problem after clicking add button in menu addition. Maybe problem with escaping

![screen shot 2015-03-07 at 20 56 47](https://cloud.githubusercontent.com/assets/6537500/6543054/99388032-c50c-11e4-8374-3fd990f086ac.png)

**Comment by lgt** [comment]
I have the same issue and seems to be related to the new october commits 
```/modules/backend/widgets/Form.php``` line 917 
```list($model, $attribute) = $this->model->resolveAttribute($htmlArray)```

seems like the ```RainLab\Pages\Classes\MenuItem``` needs some changes

```Call to undefined method RainLab\Pages\Classes\MenuItem::resolveAttribute()"```

**Comment by daftspunk** [comment]
Fixed in Build 221
