### ISSUE TITLE
Variable repeater fileupload error

### ISSUE THREAD

**Issue by davethepottingshed** [rainlab/pages-plugin#302]
The following error is thrown when trying to add a item to the repeater field.

<img width="482" alt="screen shot 2017-10-23 at 14 50 00" src="https://user-images.githubusercontent.com/29524195/31892674-8dede682-b801-11e7-8f4a-8e4e705b5153.png">

```
{repeater name="hero-images" prompt="Hero Images" tab="Hero Banner"}
    {fileupload name="hero-image" label="Hero Image"}{/fileupload}
{/repeater}
```

It works correctly if you change the `fileupload` field with the `mediafinder` field

**Comment by LukeTowers** [comment]
@davethepottingshed this is fundamental to how the fileuploader works (i.e. using database relations). You will have to use the `mediafinder` field instead. 
See https://github.com/octobercms/october/issues/2708, https://github.com/octobercms/october/issues/2196, https://github.com/octobercms/october/issues/1846
