### ISSUE TITLE
Suggestion: reduce the number of partials for staticmenu to one

### ISSUE THREAD

**Issue by xNok** [rainlab/pages-plugin#303]
## Actual behaviour
Currently the component `staticmenu` containts two partials

* default.htm
* items.htm

This code splitting remove the ability to use efficiently the fork option in the OctoberCMS. In other words when you select the `staticmenu`  and click on the fork icon you get the following code:

```
{% if staticmenu.menuItems %}
    <ul>
        {% partial staticmenu ~ "::items" items=staticmenu.menuItems %}
    </ul>
{% endif %}
```

Then you need to go on github to find the staticmenu/items.htm to properly customise those menus.

## Desire behaviour

When clicking on the fork option all the markup appears. This could be avoided buy having all the code in staticmenu/default.htm

## General recommendation

keep a unique markup files for components as much as possible, such that when using the fork option in the CMS editor all the markup appears.

**Comment by LukeTowers** [comment]
This would break existing installations that override the items.htm partial.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
