### ISSUE TITLE
Change text to Content blocks in multiple languages

### ISSUE THREAD

**Issue by panakour** [rainlab/pages-plugin#308]
Clients don't have access to the Content blocks for multilingual sites. Let's assume we have text content on top header:

top-header.txt
top-header.ru.txt
top-header.el.txt
...

![image](https://user-images.githubusercontent.com/12927166/32148498-a3dea9d2-bd00-11e7-8d65-a798ba785d47.png)

Only the default language they can edit.

**Comment by LukeTowers** [comment]
@panakour Could you dig deeper into the code and submit a PR to fix this?

**Comment by panakour** [comment]
@LukeTowers I will try when I wil be free.

**Comment by panakour** [comment]
@LukeTowers The problem is not actually in the static-pages plugin but to [translate-plugin](https://github.com/rainlab/translate-plugin) specifically there is a method called [pruneTranslatedContentTemplates method](https://github.com/rainlab/translate-plugin/blob/e603c487fa0c1c4a9ca31cd6c1a9305ea2364389/classes/EventRegistry.php#L208) that is called on the [controller ](https://github.com/rainlab/pages-plugin/blob/1e98218e88dd7bc6fc4c901d28cecd11f62957d1/controllers/Index.php#L671)of pages-plugin. Do you have any idea of how to fix this in an efficient way?

**Comment by LukeTowers** [comment]
@panakour not really, I'm not sure what the original purpose of that method was.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
