### ISSUE TITLE
Placeholder tabs no longer showing in the editor

### ISSUE THREAD

**Issue by hybridvision** [rainlab/pages-plugin#31]
Hi Alexey and Samuel,

First of all, thanks for all your amazing work on October CMS :)

Now to the problem - the placeholder content tabs are no longer displaying when editing static pages. I just did a fresh install of the latest build (225) and the only plugin I added was Static Pages (v1.0.10).

I have an older install of October elsewhere running *build 211* and *v1.0.8* and it is working as expected there so this problem has occurred sometime since then. Could you please take a look?

My setup is Laravel Homestead / Vagrant on OS X 10.9.4.

Many thanks,

Stephen

**Comment by jamiegrand** [comment]
I have the same problem but a different setup, but plugin and build the same

**Comment by hybridvision** [comment]
Thanks Samuel!

Confirmed it is working on this end :+1:

**Comment by SergeyMiracle** [comment]
Missing again... build 270

**Comment by hybridvision** [comment]
@SergeyMiracle - this issue is now closed and I can't reopen it so you should probably submit a new issue and reference this one... I haven't had a chance to test the new build yet but I will do that later.

**Comment by hybridvision** [comment]
I've confirmed this is broken again in build 270 so I'll open a new issue...
