### ISSUE TITLE
Cannot delete last menu item in Static Menu

### ISSUE THREAD

**Issue by jan-vince** [rainlab/pages-plugin#310]
Last menu item can be (visually) deleted but after save and page reload that deleted item is still present in menu.

Can anyone (@LukeTowers, @daftspunk) confirm that this is a bug and not an intended behavior?

*When a new Static Menu is created and immediately saved, it will contain no items. So there should be a way how to revert existing Static Menu with items to the same (empty) state.*

*I can imagine use case when an empty menu is a condition in ````if```` statement for not to display menu in front-end.*

If this is a bug I can try to find a fix for it.

![octobercms-pages-plugin-delete-menu-item](https://user-images.githubusercontent.com/1104383/32412948-4e621574-c206-11e7-8b4f-878a36e7c458.gif)

### Versions

OctoberCMS build: 426
Static Pages plugin: 1.2.18

**Comment by LukeTowers** [comment]
I'd consider this a bug, if you could make a PR to fix it that would be great @jan-vince! Thanks!

**Comment by MateThemes** [comment]
Hello everyone!

What is about this bug? Will it be fixed? I have the same problem.

Thank you!!!!

**Comment by LukeTowers** [comment]
@MateThemes see previous answer. You can either fix it yourself and provide a PR or offer a bounty for someone to fix it for you

**Comment by bennothommo** [comment]
@jan-vince @MateThemes This should now be fixed: https://github.com/rainlab/pages-plugin/commit/b4c29707da2d0cb479cd764f0260a0a2a3996707
