### ISSUE TITLE
compact menu tree and minimize all items (feature request)

### ISSUE THREAD

**Issue by plyusninva** [rainlab/pages-plugin#311]
If there are more than 100 pages with an nesting level greater than 4, it becomes difficult to maintain the content

Please consider the possibility to make the menu more compact and with the ability to collapse all menu items with a single click

To achieve compactness I have to use the following css:
```
/*STATIC PAGES - TREE PAGES*/ 
/*active tree item*/
.control-treeview ol > li.active > div {
    background: #f1cdad;
}
.control-treeview ol > li.active > div:after {
    width: 8px;
}
/* 1 level */
.control-treeview ol > li > div {
    font-size: 13px;    
    background-color:rgb(255, 255, 255);
}

.control-treeview ol > li > div > a {
    padding: 5px 45px 10px 55px;
    line-height: 100%;  
    font-weight: 900;    
}

.control-treeview ol > li > div:hover {
    background-color: rgb(88, 182, 247) !important;
}

/* 2 level */
.control-treeview ol > li > ol > li > div{ 
    background-color:rgb(245, 245, 245);
}
.control-treeview ol > li > ol > li > div > a{ 
    font-weight: 600;
}
.control-treeview ol > li > ol > li > div:hover{ 
    background-color: rgb(88, 182, 247) !important;
}

/* 3 level */
.control-treeview ol > li > ol > li > ol > li > div {
    background-color:rgb(235, 235, 235);
}
.control-treeview ol > li > ol > li > ol > li > div > a {
    font-weight: 300;
}
.control-treeview ol > li > ol > li > ol > li > div:hover {
    background-color: rgb(88, 182, 247) !important;
}

/* 4 level */
.control-treeview ol > li > ol > li > ol > li > ol > li > div {
    background-color:rgb(225, 225, 225);
}
.control-treeview ol > li > ol > li > ol > li > ol > li > div > a {
    font-weight: 100;
}
.control-treeview ol > li > ol > li > ol > li > ol > li > div:hover {
    background-color: rgb(88, 182, 247) !important;
}
```

results
before :-( 
![image](https://user-images.githubusercontent.com/25381948/32601412-5aa30724-c564-11e7-89b4-c6a35fea7abb.png)

after :-) 
![image](https://user-images.githubusercontent.com/25381948/32601525-c150342e-c564-11e7-889f-6d7b36b88f1e.png)

**Comment by abelschooleman** [comment]
I was just about to open this topic! I agree, we're running a site which has about 190 pages nested 3+ levels deep. Especially reordering has become a real issue. Oftentimes the page structure needs to be repaired by editing the yaml file manually because reordering pages through the frontend has messed things up.
I did notice some effort to improve in an update recently but the effect was marginal. Are there any plans to provide better ways to sort pages in the future? We're currently discussing making an extension dedicated to doing just that.

**Comment by LukeTowers** [comment]
@abelschooleman I wouldn't be opposed to a pull request to improve the interface

**Comment by abelschooleman** [comment]
Got it @LukeTowers Will see if we can start working on this

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by plyusninva** [comment]
it is still relevant!

**Comment by LukeTowers** [comment]
@plyusninva note the

> If this is still something that you would like to see through to fruition 

part. 

We currently don't have time to look into this for you, so your options are either implement it yourself and make a PR or offer a bounty to pay for someone's time to implement it for you.

**Comment by bennothommo** [comment]
@plyusninva Would you please be able to take your code from your initial post and [make a pull request](https://github.com/octobercms/october/compare) in the October CMS core where the tree view control styling is defined? This way, we can properly review the changes anddetermine if it conflicts with any other changes made recently.

**Comment by plyusninva** [comment]
I also do not have time to understand the October CMS core, you have more experience with it. I shared with you the experience of using your plugin and the disadvantages of the user interface. I suggested a way to eliminate these shortcomings. If you do not want to improve the UI, you can leave everything as it is.

**Comment by LukeTowers** [comment]
@plyusninva that's fine, we'll leave it as it is then. The project is free and supported by the community, if a particular issue / enhancement isn't worth anyone's time to implement then it just doesn't get implemented and that's just the way it works.
