### ISSUE TITLE
Recommended way to customize HTML from staticBreadcrumbs?

### ISSUE THREAD

**Issue by richardwo** [rainlab/pages-plugin#312]
Hi,

Is there a recommended way to customize the HTML generated by staticBreadcrumbs component?
I want to use with Bootstrap 3 and add some CSS classes to the elements.
Thanks.

**Comment by jan-vince** [comment]
You can create your own partial based on default staticBreadcrumbs component code.

Default markups are [mostly examples](https://octobercms.com/docs/cms/components#customizing-default-markup).

**Comment by richardwo** [comment]
Thanks - that does exactly what I want.

For anyone else that runs into this:
- copy `plugins/rainlab/pages/components/staticbreadcrumbs/default.htm` into `themes/yourtheme/partials` and rename as `breadcrumb.htm`
- in your layout replace `{% component 'staticBreadcrumbs' %}` with `{% partial 'breadcrumbs.htm' %}`
- you can now edit `breadcrumb.htm` as necessary
