### ISSUE TITLE
Add permissions for changing layouts and URL

### ISSUE THREAD

**Issue by LucasAbella29** [rainlab/pages-plugin#313]
Hey! I was working with October and when i use the permissions that this plugin has, the administrator that can manage static pages can also set the layout and the url for the page. I want to give permissions only to manage the content for the page and nothing else, is that possible?

Thanks in advance!

**Comment by LukeTowers** [comment]
You could do that yourself via a custom plugin, or you could make a PR to add that functionality yourself to this plugin directly.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
