### ISSUE TITLE
staticpagepicker and subpages

### ISSUE THREAD

**Issue by Alainy** [rainlab/pages-plugin#314]
When using the staticpagepicker widget for subpages it converts the url /test/testsubpage to /test-testsubpage.
I'm using Pages version 1.2.18 and October build 428.

**Comment by LukeTowers** [comment]
The staticpagepicker widget does not return URLs, it returns filenames, which are not nested like URLs.

**Comment by WLepelaar** [comment]
What is the best way to convert '-' to '/' ?
When i use ` | replace({'-': '/'}) ` it also converts all '-' in the slug urls.

Is there a way to get a page id or the page url?

**Comment by LukeTowers** [comment]
@WLepelaar Please explain exactly what you are trying to do.

**Comment by WLepelaar** [comment]
@LukeTowers : I’m trying to make a homepage layout with 3 dynamic buttons (links) It must be verry easy to select a target page.

Now i’m using the menu component. But that is not the way I want it to be, because clients Can make sub items.

**Comment by LukeTowers** [comment]
Could you please explain your code and what isn't working?

**Comment by WLepelaar** [comment]
When using the staticpagepicker widget for subpages it converts the url /test/testsubpage to /test-testsubpage.

Is there a way to recive a url? Or a way to convert it to a url?

**Comment by LukeTowers** [comment]
How does it convert it? It should just return the filename of the selected page, not even a URL.

**Comment by WLepelaar** [comment]
I’m replacing the - with a /
But when my cliënt uses a space in the pagetitel october automaticly replaces the space with a - also.

**Comment by LukeTowers** [comment]
Show me your code

**Comment by WLepelaar** [comment]
`{variable type="staticpagepicker" name="url" label="Select a page"}{/variable}
<a href="{{ url | theme | replace({'-': '/'}) }}">My Link Text</a>
`

**Comment by LukeTowers** [comment]
@WLepelaar The staticpagepicker widget returns a page's filename, not a url that can be processed by the `| theme` filter. Use the `| staticPage` filter instead: https://github.com/rainlab/pages-plugin#linking-to-static-pages

**Comment by WLepelaar** [comment]
Great. It works!
Thank you very much

**Comment by LukeTowers** [comment]
Not a problem!
