### ISSUE TITLE
Rainlab.pages update only the viewbag parameter when a page is renamed

### ISSUE THREAD

**Issue by CitrinoDeveloping** [rainlab/pages-plugin#319]
Hi,

working with rainlab pages noticed a behaviour that, probabily is wanted, but maybe sometimes is not usefull.

I try to explain:

I create two pages
test1.htm with url /test1
test2.htm with url /test2

Now inside /subdomains/octest/httpdocs/themes/demo/meta/ folder of the team we have a static-pages.yaml
static-pages:
    test1: {  }
    test2: {  }

And inside /themes/demo/content/static-pages
test1.htm
test2.htm

Now i need the same contents of test1.htm, for example, but i want to rename it to give the same name of a menu item that changed.

So i rename test1.htm in test1renamed.htm

Inside /themes/demo/meta/static-pages.yaml, nothing has changed
Inside the /themes/demo/content/static-pages folder we found always test1.htm and test2.htm

But if i open test1.htm i have this:
`[viewBag]
title = "test1renamed"
url = "/test1renamed"
is_hidden = 0
navigation_hidden = 0
robot_index = "index"
robot_follow = "follow"
==`

So if we have a website with 20 pages, example, and i rename some of these, well i have to remember that the updating history is available only on the original file, while it could be better if when i rename a file on the rainlabpages dashboard, then the file will be changed on the filesystem and yaml file will be updated?

It's only a suggestion. We encounterd a problem cause we create a cycle to have all pages navigation item of a menu and we wanted to cycle all pages but we lost the pages that were renamed.

Bye

**Comment by LukeTowers** [comment]
I'm not really sure what the issue you're describing is, could you be a bit clearer?

**Comment by CitrinoDeveloping** [comment]
Hi Luke,

it's not an issue but, imho, a not correct behaviour.
In this case we lost persistence of data.
I will try to explain better in a more coincise way, excuse me for my wafull english :)

I create a new page in rainlabpages
Then i decide to rename it and change the url. 
This changes are available only in the viewbag of the page renamed, but on the filesystem the physical name of the file it's not the same and in statics-page.yaml the referement to static content remain the first inserted.

This is only a conceptual thinking. If i rename a page, i expect that also the name of the htm file change and consequently the reference in the yaml file.

We hope now is a little bit clear.
Thanks Luke

Bye

**Comment by LukeTowers** [comment]
Why does it need to change the filename and the reference in static-pages.yaml?

**Comment by CitrinoDeveloping** [comment]
I'm a the content manager of a website.
I have 20 pages created on rainlab.pages
I find a a page must have a different title and url. I will not create a new page but i will rename it and change url. 
Some months later...
The page will continue to work cause the title and url are stored in the [viewbag] of the page. 

On the filesytem, perhaps, the page will continue to have the previous name, so there is no correspondence beetween the title of the page and physical name of the page.
And also in the yaml file is cited the previous page.

Imagine now i cycle all 20 pages, and i cycle it getting the reference of the menu or reading the content folder (which i love, cause i love the speed of the flat file philosophy). What happens? Maybe the page renamed will not load inside the cycle.

Repeat, the olny thing strange to me is the fact that in the plugin i can change the title and the url of a page, but then to me, the page have to physical be updated with the new title to have a correspondence.

Thanks for your time! 
Bye.

**Comment by LukeTowers** [comment]
Feel free to make a PR with the functionality you're requesting

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
