### ISSUE TITLE
Support Markdown Editing

### ISSUE THREAD

**Issue by sqwk** [rainlab/pages-plugin#322]
The blog plugin already allows for markdown parsing. Is this possible for the main content field of the pages plugin as well?

Alternatively, can placeholders be parsed as markdown text? (Probably more of a feature request for  October CMS instead for this specific plugin.)

**Comment by LukeTowers** [comment]
The blog plugin registers its own custom formwidget: BlogMarkdown. In theory you could have a custom field that you use instead of `type="RainLab\Blog\FormWidgets\BlogMarkdown"` and then hide the main content field and render that custom field instead.

**Comment by sqwk** [comment]
@LukeTowers Is there a way of copying that class into a separate file in order to not have to install the blog plugin? (Not needed for this project)

**Comment by LukeTowers** [comment]
@sqwk you'd essentially be forking it but yes. Your responsibility to maintain it within your own plugin though

**Comment by bennothommo** [comment]
@sqwk I'm going to say that this is not going to be possible in the core Pages plugin. Page content is stored as HTML in a CMS object in the filesystem, so if one were to use the Markdown editor, it would have to be rendered to HTML when stored in the file which would make it impossible to review the original Markdown if you were to go back and edit the page.

In addition, the Markdown would have to support handling snippets which is not possible currently in the Markdown editor.

As @LukeTowers indicated, this would be more in the realm of responsibility of a custom plugin.
