### ISSUE TITLE
How to sort PageList class

### ISSUE THREAD

**Issue by ghost** [rainlab/pages-plugin#324]
How can i sort items form the PageList class? I like to sort all items by something link CreatedAt or the page ordering in de Pages tab.

Here is the code i'm using right now:
`function onStart() {
    $theme = Cms\Classes\Theme::getEditTheme();
    $pageList = new RainLab\Pages\Classes\PageList($theme);
    $this['pagesList'] = $pageList->listPages();
}`

I hope someone can help me out

**Comment by w20k** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
