### ISSUE TITLE
Form tag removed by toggling 'code view' button

### ISSUE THREAD

**Issue by richardwo** [rainlab/pages-plugin#325]
In Settings / Editor Settings / Markup Tags, 'form' is listed in the allowed tags section.
However when editing the content of a static page, putting some HTML with a form tag in the Code View then toggling the Code View button causes the form tag to be removed and a bunch of p tags added.

I pasted in this example code:
```
<form action="/action_page.php" method="get">
  First name: <input type="text" name="fname"><br>
  Last name: <input type="text" name="lname"><br>
  <input type="submit" value="Submit">
</form>
```
and it ended up as
```
<p>First name:
  <input type="text" name="fname">
</p>

<p>Last name:
  <input type="text" name="lname">
</p>

<p>
  <input type="submit" value="Submit">
</p
```

**Comment by LukeTowers** [comment]
Froala needs to be updated and is being worked on by @daftspunk, perhaps that will fix the issue. Does it still remove form if you remove the action and method attributes and leave it just as `<form>`?

**Comment by richardwo** [comment]
Removing action and method attributes makes no difference, the form tag is still removed and p tags are added.

**Comment by bennothommo** [comment]
@richardwo An issue has been set up in the core October CMS repo for the tag stripping issue in the richeditor widget. You can monitor any further progress and comment here: https://github.com/octobercms/october/issues/3305
