### ISSUE TITLE
Writing a quote in a richeditor can break the site

### ISSUE THREAD

**Issue by Fl0Cri** [rainlab/pages-plugin#327]
I wrote some text in a richeditor. This text contained contained a string between quotes, followed by a line break. When I saved the page, I got this error in a dialog box:
```
"syntax error, unexpected '"' in Unknown on line 12
" on line 23 of .../vendor/october/rain/src/Parse/Ini.php
```

Tried to reload the page (backend), and the same error appears (not in a dialog box this time, the static page backend is broken).
The front-end is also broken (with the same error).
Note that the backend (except static pages) is working fine.

## Steps to reproduce
1. Create a CMS layout with the following content:
```HTML
description = "test INI bug"

[staticPage]
useContent = 0
==
{variable type="richeditor" name="testEditor"}{/variable}
<!DOCTYPE html>
<html>
    <body>Layout</body>
</html>
```

2. Create a new static page based on the previously created layout
3. Type the following in the richeditor. The line break after the quoted string must be a Shift+Enter (new line), not a simple Enter (new paragraph):
```
"Test"
test
```

4. Save the page... Congratulation, you broke your site :p

## How to fix
The only way to make the site work again is to clear the bad text via FTP: go to `/themes/[your_theme]/content/static-pages/[your_page].htm`. Delete the lines that broke the site, in my example I delete these lines:
```INI
testEditor = "<p>\"Test\"
	<br>test
	<br>
</p>"
```

## What's going wrong
The exception is thrown by the php parse_ini_string() function [here](https://github.com/octobercms/library/blob/master/src/Parse/Ini.php#L23)
Static pages saves the content of richeditors in multiline format (the output of Froala I presume), but multi-lines values are not valid in ini format (not sure there is a standardized ini format anyway).
parse_ini_string() allows multi-line values by continuing to read the value until it finds the next quote, but it seems to not respect the escaping backslash when the following quote is the last character of the line.

## Maybe some ideas to fix the problem
Trying to tweak the string to make it equivalent but valid, I figured out that a double double quote `""` is skipped by parse_ini_string(), even when it's at the end of a line. For example:
```INI
testEditor = "\"Test\"""
test"
```
would be correctly rendered as
```
"Test"
test
```

I was thinking at doing a replace of all `\"` by `\"""` at end of lines before parsing, but it would break if the ini value is realy finishing by a backslash. For example: `test = "Test\"` is valid ini and outputs `Test\`, but `test = "Test\"""` makes a syntax error.

An other solution I saw (but I don't like) is to replace the quotes by a hardly predictible symbol. For example Joomla replace all quotes in ini values by `_QQ_`.

Or maybe static pages could "minify" the output of Froala to strip (or replace) newlines.

**Comment by LukeTowers** [comment]
Minification could work to fix this, but it would break HTML values that had <pre> tags in it. I think the best solution probably is to do a string replacement in the Parser library itself. That way we don't have to store weird sequences and we can also fix multiline escaped quote parsing for anything that uses the Ini Parser at the same time. 

Could you make a PR to the octobercms/library repo to add that functionality?
