### ISSUE TITLE
Mobile Nav menu not showing on Static Pages

### ISSUE THREAD

**Issue by malachiman** [rainlab/pages-plugin#329]
Never had this issue before.  My layout works perfectly on CMS pages, it is only on Static Pages that the problem appears.

When viewing the site on a mobile device, the hamburger menu appears, but once you select that it disappears and no menu shows.

I have rebuilt it a couple of times and the same issue.  It works as an HTML only site, works on every CMS page, its just Static Pages its refusing to display.  Has anyone else had this issue?

**Comment by LukeTowers** [comment]
Sounds like you're missing something on the layout that you're using for your Static Pages

**Comment by malachiman** [comment]
It is weird.  Have tried removing parts of the layout to see if there is something conflicting or broken.  The layout for both the Static and CMS are identical.

**Comment by LukeTowers** [comment]
Identical code wise or literally the same file?

**Comment by malachiman** [comment]
Identical, seperate files.

**Comment by LukeTowers** [comment]
Why not try making them the same? Put the staticpage component on the CMS layout and remove the staticpage specific layout entirely

**Comment by malachiman** [comment]
Ok,  I haven't tried that.  Will give it a go, thanks.

**Comment by malachiman** [comment]
Wow thanks, that working now!

The only thing thats different is the layouts are not nested in a folder.  Im not sure why that would make a difference. But its working.  Brilliant, thanks again for the suggestion.

**Comment by LukeTowers** [comment]
I don't think layouts are supported being in a nested folder @malachiman

**Comment by malachiman** [comment]
Oh well that explains it, and many hours of trying to figure it out, only to have it be something as simple as that.  Thanks again

**Comment by Eoler** [comment]
>I don't think layouts are supported being in a nested folder

They are, tested it earlier today:
https://github.com/Eoler/oc-ui3kit-theme/blob/master/pages/styleguide/uikit3.htm#L3

**Comment by LukeTowers** [comment]
@Eoler does the static pages plugin support it?

**Comment by LukeTowers** [comment]
@Eoler note, this is in regards to **layouts** being in a nested folder, not pages

**Comment by Eoler** [comment]
> this is in regards to layouts being in a nested folder, not pages

Yes, the link above shows page referencing nested layout...

**Comment by LukeTowers** [comment]
Ah, I see. Odd; not sure what the issue was then
