### ISSUE TITLE
group subpage variables by "tab" attribute in staticPage->getChildren()

### ISSUE THREAD

**Issue by JurekR** [rainlab/pages-plugin#330]
Hi,

if I get a list of static subpages of a static page using code similar to the following:
```javascript
<?php
function onStart() {
   $staticPage = $this->page->apiBag["staticPage"];
   $this["subpages"] = $staticPage->getChildren();
}
?>
==
{{ dump(subpages) }}
{% for staticpage in subpages %}
    {{  staticpage.viewbag.url }}
    {{  staticpage.viewbag.variable1 }}
    {{  staticpage.viewbag.variable2 }}
    <img src="{{  ('mediadir' ~ staticpage.viewbag.variable3)|media }}" />
{% endfor %}
```

The containing static subpage objects hold the variables in the viewbag sub object on the root level, even if the variable was defined using a sub group / tab, like this:
```javascript
{variable name="headline" label="Headline" tab="subgroup" type="text"}{/variable}
```
Maybe it would be helpful, if these variables inside the viewbag were also accessible in subarrays, grouped by the group/tab-name. Also what happens, if there are two variables using the same name but a different tab?

Also a grouping of the contents by put-area would be helpful. Currently the normal contents only seem to be available thru staticpage->original->code, and then only with put-twig-statements inside.

**Comment by LukeTowers** [comment]
I'm not sure what would happen, why don't you give it a try? I'm guessing it won't work because tabs are purely for presentation.

**Comment by JurekRaben** [comment]
It was more meant as a rhetorical question, but I hope you get the idea, using the subpages mechanic to quickly build list views from the variables inside the subpages.

**Comment by LukeTowers** [comment]
What's your issue with having the fields for a page being stored on that page and not in a sub grouping by tab?

**Comment by JurekRaben** [comment]
More convenient to build a lister page? Let's say I have a parent lister page and subpages which have the tabs "main content" and "overview content". In the overview content there is the preview image for the list and the headline, in the main content the real news content. Now I would like to display preview image, headline and a part of the real content in the list per entry. I would say that some functionality for structures like this would be very helpful, e.g. staticSubPage->getContent("overview content")->variable1... Or similar. Currently this kind of access looks pretty raw to me.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
