### ISSUE TITLE
Please add native page duplication action

### ISSUE THREAD

**Issue by Jurek-Raben** [rainlab/pages-plugin#331]
Hi,

it would be very helpful for the clients, if you could duplicate a static page in the backend, e.g. providing a base page, which should be duplicated by the client. Also this would be nice the the normal cms pages.

**Comment by LukeTowers** [comment]
Make a PR with screenshots of your proposed changes

**Comment by JurekRaben** [comment]
Ok, here it is:
<img width="363" alt="bildschirmfoto 2018-03-13 um 20 10 17" src="https://user-images.githubusercontent.com/239679/37364652-6296e2ea-26fb-11e8-806c-4fce58dc02fb.PNG">
Result:
<img width="356" alt="bildschirmfoto 2018-03-13 um 20 11 39" src="https://user-images.githubusercontent.com/239679/37364661-6958e600-26fb-11e8-9b8e-b98f8782496e.PNG">

**Comment by LukeTowers** [comment]
I'd support that being added; make a pull request implementing that feature (or sponsor someone else to do it for you) and I'll review and merge it when it's ready.

**Comment by maraerben** [comment]
What is the progress? That's exactly what I would need...

**Comment by LukeTowers** [comment]
@maraerben nothing's been done on it as far as I'm aware, feel free to implement it yourself or provide a bounty for someone else to do it for you if you would like.

**Comment by daftspunk** [comment]
Add this to list of improvements to consider. Thanks! 🙏
