### ISSUE TITLE
Change title via resolveItem event

### ISSUE THREAD

**Issue by witul** [rainlab/pages-plugin#334]
I want to ask for the best way to change menu item title. 
For now i added something like this to Menu class:
```php
if (!$item->replace && isset($itemInfo['title'])) {
    $parentReference->title = $itemInfo['title'];
}
```
In apiResult handling. 
I can make a pull request if it makes sense.

**Comment by LukeTowers** [comment]
Why do you need to change the title in code? What are you trying to do exactly?

**Comment by witul** [comment]
I have to use a different title if user is logged in for the same link.

**Comment by bennothommo** [comment]
I think this would be best done as a conditional in your theme.
