### ISSUE TITLE
Unknown "dump" function in "getTwigNodeTree"

### ISSUE THREAD

**Issue by SeriousKen** [rainlab/pages-plugin#337]
I have a debugging layout that uses the dump function to output the Twig variables, but this layout does not work with the Static Pages plugin giving the above error. I presume the Static Pages plugin is using a different instance of the Twig parser which does not have the dump function registered.

**Comment by SeriousKen** [comment]
Sorry, should have said this error occurs in the backend when trying to edit a page, not when viewing the page.

**Comment by SeriousKen** [comment]
Seems to be related to this block of code in the main October CMS code which doesn't add the debug extension to the Twig environment.

https://github.com/octobercms/october/blob/8ba63dd428b425a3722fb18c6ce5e58f03be5314/modules/cms/classes/CmsCompoundObject.php#L401-L419

**Comment by SeriousKen** [comment]
Seems to be because the CmsCompoundObject doesn't add the debug extension when it creates the Twig environment.

https://github.com/octobercms/october/blob/8ba63dd428b425a3722fb18c6ce5e58f03be5314/modules/cms/classes/CmsCompoundObject.php#L401-L419

**Comment by LukeTowers** [comment]
@SeriousKen it does add them, it just seems to not be doing it properly in your case. See https://github.com/octobercms/october/blob/8ba63dd428b425a3722fb18c6ce5e58f03be5314/modules/cms/classes/CmsCompoundObject.php#L415 and https://github.com/octobercms/october/blob/master/modules/system/twig/Extension.php#L46

**Comment by SeriousKen** [comment]
It does not add the DebugExtension, compare with how Twig is newed up in the controller https://github.com/octobercms/october/blob/8ba63dd428b425a3722fb18c6ce5e58f03be5314/modules/cms/classes/Controller.php#L508-L514 particularly lines 512-514

This is the only place the DebugExtension is referenced. To be honest, shouldn't the responsibility of creating the Twig environment be moved to the container? We seem to have code repetition and a hard dependency on Twig otherwise.

**Comment by SeriousKen** [comment]
Another look over the code and I'm wondering whether getTwigNodeTree should actually be on the CmsCompoundObject at all. It's not used in the core of OctoberCMS and is only called in the Pages plugin (in the plugins I have installed anyway).

**Comment by LukeTowers** [comment]
@SeriousKen I'm reopening this issue until octobercms/october#3575 is merged, thanks for submitting that!

**Comment by daftspunk** [comment]
Fixed in OCMS v2.0.20
