### ISSUE TITLE
Implement collapseByDefault on Repeater FormWidget

### ISSUE THREAD

**Issue by zlobec** [rainlab/pages-plugin#338]
How would one tackle the problem, to load all variables (like repeaters and other fields) on page open, to a collapsed state?

Example: I have a gallery with a repeater and + 20 images... and when they all load not collapsed, it takes a while to get to the end of page to add a new image.

Any suggestions?
Regard,
Darjan

**Comment by LukeTowers** [comment]
@zlobec for now probably some JS is your best bet, or we could add a property to the repeater form widget that loads it in a collapsed state, something like `collapseByDefault`. Make a PR if you'd like to see that behaviour

**Comment by zlobec** [comment]
@LukeTowers thanks for the response. I haven't got enough experience to start developing solutions for all my problems :D I'll try to find a JS or CSS solution as a quick fix for this.

**Comment by LukeTowers** [comment]
@zlobec give it a try, you'll probably learn lots :)

**Comment by zlobec** [comment]
For the time website is not in production, I added the class "collapsed" to the _repeater.htm partial in line 7. Crude, but it sorta works for my needs now :smile:

**Comment by LukeTowers** [comment]
@zlobec you might be able to add it in the attributes property

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
