### ISSUE TITLE
Snippets mess up html

### ISSUE THREAD

**Issue by CptMeatball** [rainlab/pages-plugin#34]
Using snippets to add inline images doesn't work. The snippet strips the surrounding ```<p>``` or places it in new ```<p>```. If desired effect is typed in the HTML mode, same behaviour occurs.

Is there any other way to add images to the Rich editor?

![screen shot 2015-04-09 at 11 36 32](https://cloud.githubusercontent.com/assets/1681727/7064248/78ae6fba-dead-11e4-970b-00b3ae7d6c6e.png)
![screen shot 2015-04-09 at 11 43 09](https://cloud.githubusercontent.com/assets/1681727/7064268/9fd2c9ec-dead-11e4-964a-988ded9849bd.png)

**Comment by hybridvision** [comment]
There is now - see the media manager feature that was just released!

https://octobercms.com/blog/post/introducing-media-manager

**Comment by daftspunk** [comment]
This should no longer occur and has been solved by media manager.
