### ISSUE TITLE
Script included three times

### ISSUE THREAD

**Issue by Synairgis** [rainlab/pages-plugin#342]
Hey there, I'm currently using Peter Hegman's slideshow plugin together with your plugin and I've stumbled upon a weird glitch. You see, I created a very basic slideshow and then imported it inside a static page... and ended up with a couple javascript errors. Upon further investigation, I found out that my page had three identical 

`$(document).ready()`

All of them are actually identical and happen to be the content of the components/slider/default.htm file from the slideshow plugin.

Now I'm not entirely certain if the problem resides with you or with him, but I opened an issue on his github too in hope that it gets resolved.

**Comment by LukeTowers** [comment]
@Synairgis the issue would be with the slideshow plugin, for a temporary workaround use component override files to modify the code as required for your project.
