### ISSUE TITLE
How to get only url of image variable in Syntax Field

### ISSUE THREAD

**Issue by Ladylain** [rainlab/pages-plugin#344]
Hi, 

I'm using Pages plugin, and i've put a syntax field for a mediafinder, but i want to get back only the url of the media, not the image tag. Could you tell me if it's possible ? 

what i'm using is : 
`{variable name="banner" label="Banner" tab="Header" type="mediafinder" mode="image"}{/variable}`

what i'm getting back : 
`<img src="{{banner|media}}" />`

what i want to retrieve : 
`{{ banner|media }}`

thanks

**Comment by LukeTowers** [comment]
What do you mean you're getting back `<img src="{{banner|media}} />`? `banner` should just be available as a variable anywhere on the page.

**Comment by Ladylain** [comment]
Hi, 

it's not really what i get back. 

my code is like that 
```        <style>
        #layout-header{
            background-image:url({variable name="banner" label="Banner" tab="Image Header" type="mediafinder" mode="image" placement="primary"}{/variable}) !important;  
        }
        </style>```

And so, no image is showing up.

**Comment by LukeTowers** [comment]
@Ladylain don't do that, do this:
```html
{variable name="banner" label="Banner" tab="Image Header" type="mediafinder" mode="image" placement="primary"}{/variable}

<style>
        #layout-header{
            background-image:url({{ banner | media }}) !important;  
        }
</style>
```

**Comment by Ladylain** [comment]
oh ok, thanks a lot :+1:

**Comment by LukeTowers** [comment]
No problem!
