### ISSUE TITLE
Missing preview vars for pages

### ISSUE THREAD

**Issue by loopezz** [rainlab/pages-plugin#345]
Unlike the Blog plugin Pages doesn't have a function to access variables like excerpt or featured_images. I'm trying to access a static page by it's filename and load some variables of it. This would be very useful to render a preview of a static page on another static page (for example: featured services or products on the home page).

These featured static pages are dynamically selected by the customer with the following code:
```
{repeater name="services" tab="Services" prompt="Add service"}
    {variable name="image" label="Image" type="mediafinder" mode="image" imageWidth="360"}{/variable}
    {variable name="title" label="Title" type="text"}{/variable}
    {variable name="text" label="Content" type="text"}{/variable}
    {variable name="link" label="Link" type="staticpagepicker"}{/variable}
{/repeater}
```

Is it possible to integrate this into Pages or could this be achieved by a different approach?

**Comment by LukeTowers** [comment]
@loopezz you'd have to create a custom component that could be passed a static page (from the pagepicker formwidget) in it's properties and then load that page with the classes/Page class and access the relevant ViewBag properties. You may have to do some debugging with `dump()` and / or `dd()` on the loaded Page object to figure out the exact properties you need to target but it should be doable to get that data for displaying as a preview.

**Comment by loopezz** [comment]
Thanks for the reply. I wasn't able to follow your approach, beause of my lack of knowledge. However, I found another way to get the desired result.

I have added this code to my home.htm layout:
```
<?php
use RainLab\Pages\Classes\Page;
 
function onStart() {
    $previewServices = [];

    foreach($this->page->apiBag['staticPage']->viewBag['services'] as $service) {
        $fileName = $service['link'];
        $previewService = Page::load($this->theme, $fileName);

        if($previewServices && !$previewService->viewBag['is_hidden']) {
            $previewServices[] = $previewService->viewBag;
        }
    }

    $this['preview_services'] = $previewServices;
}
?>
```

**Comment by LukeTowers** [comment]
@loopezz glad you were able to figure it out! Doing it my way would be delving into creating your own plugin for the problem, so I'm glad you were able to accomplish it in a way that worked best for you!
