### ISSUE TITLE
Nested pages not listed in References search

### ISSUE THREAD

**Issue by nizzac** [rainlab/pages-plugin#348]
When you go to add a new menu item, and use the "Search all references" to find a page. The results only include the top level static pages.

So if you have a page structure like this.

![image](https://user-images.githubusercontent.com/12571713/43317890-a936a2d4-9196-11e8-8c2a-fe9fd97945ab.png)

If you try and add service one as menu item by using the search references, searchinig for **"Service One"** the service one page isn't in the results.

![image](https://user-images.githubusercontent.com/12571713/43317862-81479120-9196-11e8-8258-33d2735834a6.png)

I'd expect to be able to add any pages as a menu item, not just the top level pages.

**Comment by bennothommo** [comment]
I've confirmed this issue still exists in the latest version of the plugin (1.2.21).

**Comment by bennothommo** [comment]
This is now fixed as of 1b2d4ed.
