### ISSUE TITLE
Way to use theme.options in static pages

### ISSUE THREAD

**Issue by asystemg** [rainlab/pages-plugin#349]
Hi,
Is there a way to use strings and images that are set in theme options in static pages page?
Something like `{{this.theme.who_are_we_content | raw | _}}`
Best regards.

**Comment by LukeTowers** [comment]
@asystemg What exactly do you need to do that for / what would that look like?

**Comment by bennothommo** [comment]
@asystemg You would probably want to use a Snippet created from a partial to achieve this, as you can use `this.theme` in the partial. For steps on how to do this, have a look at https://octobercms.com/plugin/rainlab-pages, click on the *Documentation* tab and look at the *Snippets* section.
