### ISSUE TITLE
Real path of a static-page ?

### ISSUE THREAD

**Issue by GrCOTE7** [rainlab/pages-plugin#351]
Hi, all,

I'm looking for the way to get the real path of a static-page's file...

Exemple:
If the page has url **http://localhost/myProject/aide**, but the corresponding file is:

**myLocalServer/myProject/themes/myTheme/content/static-pages/faq.htm**, how to get **faq** ?

(I tried to use fragment, but unsuccess...)

Thanks for your help.

http://prntscr.com/kupaud

**Comment by GrCOTE7** [comment]
Re

If that can help, I found the value of the fileName with that:

http://prntscr.com/kurug9

```
  $myDebug = debug_backtrace();

  echo '<pre>';
    var_dump($myDebug[0]['object']['page']['fileName']);
  echo '</pre>';
```

Of course, that not the best way...

Do you know how to get this same data, properly ?

**Comment by LukeTowers** [comment]
@GrCOTE7 what do you need the filename for? That will help determine the best solution for you.

**Comment by GrCOTE7** [comment]
Hi, Luke...

Thanks for your answer. I appreciate a lot, knowing you're a very busy (I read all your actions in the repository...)... And I'm sure you know the power of using git :-) !

But lots of people as me don't understand very well english... So, understand, and even, use the Git isn't evident...

That's because I'm doing a websit, in wich each page of the documentation will have 2 buttons linking the github repository of it. 1 for the project, and another for the direct link of the page.

So, construct the path is easy, if I know the file name....

Hoping you're can understand me...

**Comment by LukeTowers** [comment]
@GrCOTE7 what context are you in / what data do you have access to when you need to get the page filename? Are you running PHP code in the page itself? Do you only have the URL and are running in a completely context? Are you running PHP code in a component that's attached to the page?

**Comment by GrCOTE7** [comment]
In fact, I'm currently only with static pages... 

But, I can put a snippet, or developp a component for that.

What is the best  way to have the filename of the static-page ?

**Comment by LukeTowers** [comment]
Could you show me the entire file where you currently have your workaround?

**Comment by LukeTowers** [comment]
@GrCOTE7 I would recommend creating a component to access the page file name, something like
```php
$this->controller->getPage()->fileName
```

**Comment by GrCOTE7** [comment]
Ok, I proceed, Thanks, Like, and to soon ! :-) !



Lionel.
Écris ta Vie & Vis-la !

c57.fr : LA réponse !

Avec l'aide du Monde, Créée TON Monde !

-----------------------------------------

Write your Life & BE ALIVE !
www.NewNRJ.com



Le lun. 17 sept. 2018 à 17:39, Luke Towers <notifications@github.com> a
écrit :

**Comment by GrCOTE7** [comment]
Thanks, Luke ;-)...


I proceed and tell you soon the conclusion...

**Comment by GrCOTE7** [comment]
Hi, Luke..

I added registerPageSnippets() in Plugin.php
```
 public function registerPageSnippets() {
    return [
      'GrCOTE7\C57\Components\GithubPageLink' => 'githubPageLink'
    ];
  }
```

and my GithubPageLink php file if:

```
<?php namespace GrCOTE7\C57\Components;

use Cms\Classes\ComponentBase;

class GithubPageLink extends ComponentBase {

  public $githubPageLink;

  public function componentDetails() {

    return [
      'name'        => 'GithubPageLink',
      'description' => 'Get the github link of the page.'
    ];
  }

  public function defineProperties() {

    return [
    ];
  }

  public function onRun() {
    // GOAL: Can obtain *** (Filename of the static-page to construct this above link)
    // https://github.com/c57fr/c57/edit/master/themes/mdb/content/static-pages/ *** .htm
    
    $this->githubPageLink =$this->controller->getPage()->fileName;
    
    dump("githubPageLink value", $this->githubPageLink);
  }

}
```
I succeeded to add the snippet in my static-page, and the default.htm of this comopnent render well, but the $this->githubPageLink value is null...

What do I forget still...?

(Thanks again for your patience...)

**Comment by GrCOTE7** [comment]
Re, Luke...

I obtain the good file name, with this line of code:

```php
$this->githubPageLink = $this->controller->getPage()->apiBag["staticPage"]->fileName;
```

Is that a good way ?

**Comment by LukeTowers** [comment]
@GrCOTE7 that works well enough, one thing that I would be concerned with is if someone uses the staticPage component with an alias, but if that works for you and you control the definition of the staticPage component then I would say that looks good to go

**Comment by GrCOTE7** [comment]
Thank you for your comment.

To next.
