### ISSUE TITLE
Snippets not working in custom tabs created with Syntax Parser tab="x"

### ISSUE THREAD

**Issue by blissleh** [rainlab/pages-plugin#352]
Generally, snippets don't seem to work in custom tabs. They work fine in the main content section. Anything in custom tabs will just display as "figure" tag on the frontend. Am i just too stupid?

`{richeditor name="androgen_content" size="large" tab="Androgenindex"}{/richeditor}`

then add the Snippet to "Androgenindex" tab on the static page and it will echo as 

`<figure data-component="Blissmedia\Gallery\Components\SingleView" data-inspector-id="inspectorid-348312408616" data-property-gallery="1" data-property-thumb_height="200" data-property-thumb_width="200" data-snippet="singleView">&nbsp;</figure>`

**Comment by LukeTowers** [comment]
No, snippets are only processed in the main area. There's a plugin in the marketplace to support them in other places though: https://octobercms.com/plugin/inetis-richeditorsnippets

**Comment by LukeTowers** [comment]
Sure, it's worth consideration, I'm just letting you know that the support doesn't currently exist in the core plugin, so if you want to add it go ahead and submit a PR or sponsor the issue for someone else to do it for you.

**Comment by bennothommo** [comment]
The work that will be done to fix #336 will also resolve this issue. Feel free to add any further discussion there.
