### ISSUE TITLE
Translation adds other field when swithing

### ISSUE THREAD

**Issue by Ladylain** [rainlab/pages-plugin#353]
Hi , 

We have discover a new bug related to translate use. 

-We have a static page with repeater fields. 
-We configure all our French fields and we switch to English configuration of the same page,
-We configure the english part but when we switch again to French translation, It appears extras field like if the english is copied to french if the field doesn't exist. 

French version with some fields
![image](https://user-images.githubusercontent.com/5721178/45753117-0857aa00-bc18-11e8-8d88-b2219dbd0c84.png)

English version with some fields
![image](https://user-images.githubusercontent.com/5721178/45753161-31783a80-bc18-11e8-96f3-686e66bc00e6.png)

Reswitching to French version
![image](https://user-images.githubusercontent.com/5721178/45753193-4f459f80-bc18-11e8-8fec-dc3e63901785.png)

As you can see on last screenshot, 
-"Titre" Field has been removed
- Second "Contenu" field has been added

Do you have any idea ? 

Thanks

**Comment by LukeTowers** [comment]
@osmanzeki is this something you've come across?

**Comment by osmanzeki** [comment]
@LukeTowers Yes this is something I've seen in the past with repeaters. It happens with nested repeaters but I wonder if the cause is somewhat the same?

See this issue for info about nested repeater adding fields bug:
https://github.com/rainlab/translate-plugin/issues/307

**Comment by LukeTowers** [comment]
I'm not currently planning on working on a fix, so it would be up to the community (including yourself) to propose a fix before I would get involved with reviewing and merging it.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
