### ISSUE TITLE
Show static menu name in preview

### ISSUE THREAD

**Issue by ajmanco** [rainlab/pages-plugin#354]
How can i show my static menu name in  theme preview ?
I want to show this as a menu title in my template . like this :
```
{% if __SELF__.menuItems %}
<h4>menu name</h4>
<ul class="latest-changes-list rtl list-unstyled">
    {% partial __SELF__ ~ "::items" items=__SELF__.menuItems %}
</ul>
{% endif %}
```

**Comment by bennothommo** [comment]
The menu name is not available through the Static Menu component currently. If you would like to see it added, please submit a PR to add it in.
