### ISSUE TITLE
snippets  nested in snippet

### ISSUE THREAD

**Issue by Darkrogua** [rainlab/pages-plugin#355]
Is it a bug or an opportunity ??if possible, how do I specify the location in the parent element where the child should enter?
![snippets](https://user-images.githubusercontent.com/21284531/45927187-3dc60580-bf40-11e8-9f2a-631a0eb9ae80.jpg)

**Comment by LukeTowers** [comment]
@Darkrogua that looks like a bug to me, I don't think nested snippets are supported, I don't even know how that would work...

**Comment by Darkrogua** [comment]
> @Darkrogua that looks like a bug to me, I don't think nested snippets are supported, I don't even know how that would work...

It seems so, but in order for it to work quite simply, you need to specify in each snippet where the child element will be added and all

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
