### ISSUE TITLE
Perform changes on Custom Menu Item before rendering

### ISSUE THREAD

**Issue by paishin** [rainlab/pages-plugin#356]
I am creating a new custom Plugin and for this I have created a new Menu Item Type. 

For this menu item type I want to be able to alter the Title and Class properties of the item programmaticaly before rendering.

I thought I would be able to perform these changes using 

`Event::listen('pages.menuitem.resolveItem', function($type, $item, $url, $theme) { 
    $item->title = "New title here";
 }`

but altering the $item properties here doesn't seem to have any effect, 

Anyone could point out how I can properly do this?

**Comment by daftspunk** [comment]
You may need to set the event priority to -1 so it comes last in the chain. Or perform the adjustment in the CMS template.

More documentation on this can be found here: https://docs.octobercms.com/3.x/element/form/widget-pagefinder.html
