### ISSUE TITLE
Please Help & Guide me

### ISSUE THREAD

**Issue by Akif-dev** [rainlab/pages-plugin#359]
Hi,

i have site having two languages, i am using this plugin, and i want to display two menus, one for first language and the other one for 2nd language, menus i am using custom developed.

i want to know the way to differentiate "div->ul->li->a" codes to use on both URLs via using activeLocale

i displayed the images on both site by the following code and it worked.

```
<img src="{{ ('assets/css/style_' ~ activeLocale ~ '.css')|theme }}" rel="stylesheet">
<img src="{{ ('assets/images/chatBanner_' ~ activeLocale ~ '.jpg')|theme }}">
```
how can i use "activeLocale" or any other trick to use div codings and that sits on both language site.

any if/else condition, switch condition, or via localization attribute etc.

for instance my code is:

```
code for 1st site OR 1st language localization attribute (en) :
<div>
 <ul>
  <li><a href="#">Link 1</a></li>
</ul>
</div>

code for 2nd site OR 2nd language localization attribute (fr):
<div>
 <ul>
  <li><a href="#">Link 1</a></li>
</ul>
</div>
```
and both of the codes will be used on same page, just let me know the way to set the code so that they work on their own languages sites

please let me know if i am not clear

**Comment by LukeTowers** [comment]
@munxar is this something you can answer?

**Comment by munxar** [comment]
@LukeTowers @Akif-dev Yes I can!

I do it like this:
create a menu with a code that has your locale as a suffix, e.g.
**main_de** and **main_en**. 
now in your layout place the menu like this:
```php
[localePicker]
forceUrl = 1

[staticMenu]
==
<html>
<head>
    <meta charset="UTF-8">
    <title>Test</title>    
    {% styles %}
</head>
<body>
    {% component 'localePicker' %}
    {% component 'staticMenu' code='main_' ~ activeLocale %}
    {% page %}
    <script src="{{ ['@jquery']|theme }}"></script>
    {% framework extras %}
    {% scripts %}
</body>
</html>
```

be careful to remove the **code** in your config section (above the ==), or it will overwrite the code in the component below.
