### ISSUE TITLE
"Blocks" as default tab

### ISSUE THREAD

**Issue by maraerben** [rainlab/pages-plugin#362]
Hello,
is it possible to set Blocks (or any other tab) as default? Now the first tab is opened by default. I want to find out the best way, how to open specific tab by default. Any ideas?

**Comment by bennothommo** [comment]
@maraerben Unfortunately there is no way to specify a default tab via the template at this stage, it will always default to showing the first tab available. If you wish for a specific tab to be visible first, you will need to assign the tab first, noting that if the "Use page content field" checkbox is ticked in the Static Page component, the "Content" tab will always be first.

![image](https://user-images.githubusercontent.com/15900351/56464920-3dceab00-6426-11e9-9509-79df78f0cca7.png)
