### ISSUE TITLE
Translate Custom Fields in StaticPages

### ISSUE THREAD

**Issue by MateThemes** [rainlab/pages-plugin#366]
Hello everyone!

Is it possible to translate custom fields in staticpages that are defined in a yaml? 

I did not get it managed or is it currently not supported?

**Comment by MateThemes** [comment]
I see there is no translation possible?

**Comment by LukeTowers** [comment]
@datune @vannut one of you know the answer to this?

**Comment by MateThemes** [comment]
I have to make clear. I mean custom fields that are created with in a Theme with a yaml file!

**Comment by daftspunk** [comment]
Hey @MateThemes 

This should be possible with the multisite feature that arrived in v3.1: https://docs.octobercms.com/3.x/cms/resources/multisite.html

Feel free to get in contact with the team if you need help setting this up:
https://octobercms.com/contact

Thanks!
