### ISSUE TITLE
Need to change font color

### ISSUE THREAD

**Issue by suraj2209** [rainlab/pages-plugin#371]
I am using Static page plugin it works fine but want to know is there is any way to change font color from the editor. Please help me how i can add color option in my editor

**Comment by LukeTowers** [comment]
You would need to make a plugin that extends the page fields config to modify the richeditor field to add the color option to the toolbar: https://octobercms.com/docs/backend/forms#widget-richeditor

**Comment by suraj2209** [comment]
Thanks for the Help luke
