### ISSUE TITLE
Colour Picker Available Colours

### ISSUE THREAD

**Issue by timmarner** [rainlab/pages-plugin#373]
Cant seem to set the available colours for the colour picker on a layout. it simply loads the defaults. if anyone can help

{variable type="colorpicker" name="background_colour" span="left" label="Background Colour" availableColors=1|2|3}{/variable}

**Comment by bennothommo** [comment]
@timmarner Would you mind providing the actual variable line you are using so we can test your exact scenario?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by damsfx** [comment]
@bennothommo I'm facing the same issue.  
Can't add `availableColors` property to the field.`

Code use in layout for field declaration
````
{variable
    name="banner-color"
    label="Banner color"
    tab="Extras"
    type="colorpicker"
}{/variable}
````
Can there be an issue with the [`FieldParser->processParamsRegex`](https://github.com/octobercms/library/blob/07663137e4f04061e5d372c007ad847d183387f3/src/Parse/Syntax/FieldParser.php#L335) !?

**Comment by mjauvin** [comment]
I don't believe colorpicker is a supported type.

**Comment by bennothommo** [comment]
@mjauvin It is - I have used it before. :)

@damsfx Thanks for letting me know. Do you have an example of a particular value you use for `availableColors` that does not work in the variable tag?

**Comment by damsfx** [comment]
@bennothommo I've tried
`availableColors="#FFFFFF"`  NOK

and based on [syntax-supported-tags](https://octobercms.com/docs/services/parser#syntax-supported-tags) dropdown options `options="One|Two"`
`availableColors="#FFFFFF|#000000"`  NOK

Maybe I've missed something in the syntax.

**Comment by bennothommo** [comment]
@damsfx Thanks for that. Fixed as of https://github.com/octobercms/library/commit/778cbb37a5ace8d49c27811b0f26369a4d58a61a.
