### ISSUE TITLE
Filter down staticpagelist or dynamic variables in static pages

### ISSUE THREAD

**Issue by maartenmachiels** [rainlab/pages-plugin#376]
Hi,

My webprojects rely heavily on the Pages Plugin. Features like variables are of incredible value! I've recently discovered the variable type staticpagepicker:

`{variable name="topic" label="Topic" tab="Topic" type="staticpagepicker" }{/variable}`

Above variable creates a dropdown of all the pages, including their hierarchy, which is already very nice.
I'm now looking to filter this list and to only display the children of a specific page. I recognize this is a specific question, so I was wondering wether it's possible to generate the options of a variable with type dropdown dynamically. I've already tried several things, but I cannot get it to work.

I was thinking along the lines of the following example. My layout looks like this:

```
description = "Course"
[staticPage]
useContent = 1
default = 0
==
<?php
function onStart() {
    $topics = RainLab\Pages\Classes\Page::load(\Cms\Classes\Theme::getEditTheme(), 'topics.htm')->getChildren();
    $this['topics'] = '';
    foreach($topics as $topic) {
        $this['topics'] .= $topic->id.':'.$topic->title.'|';    
    }
   $this['topics'] = rtrim($this['topics'],'|');
}
?>
==
{variable name="topic" label="Topic" type="dropdown" tab="Topic" options=topics}{/variable}
{% partial 'header' %}
<main>
{% page %}
</main>
{% partial 'footer' %}
```
Don't laugh at me for the above code :-). This obviously cannot work. But I'm sure there is a way to prepare the statement in such a way that it executes at the right time.

So my question is: how can we manipulate the options of static page variables via the PHP section of layouts? And: is it possible to filter down the variable with type staticpagepicker?

I'm excited to get your viewpoints. Thanks again for producing this lovely CMS.

**Comment by LukeTowers** [comment]
@maartenmachiels your best bet would probably be to look at extending the fields of the page form on the backend through the use of the backend.form.extendFields event or similar methods to dynamically set those options yourself with a plugin.

**Comment by maartenmachiels** [comment]
Hi Luke, thank you for your answer and your tips. I've been looking at:
[https://octobercms.com/docs/api/backend/form/extendfields](https://octobercms.com/docs/api/backend/form/extendfields)

Is there some more documentation on how to implement this into a static page?
Might you have some examples?

Should this be placed into the function onStart() {} block of the layout?
Or should this stand by itself in the PHP section?

Thanks for your comments.

**Comment by LukeTowers** [comment]
@maartenmachiels you'd have to build your own plugin that would either extend the RainLab.Pages controller or do some reading of the code to figure out how you could bind to the Form widget that actually displays that dropdown in the backend.

**Comment by maartenmachiels** [comment]
I've pushed through and found it. By adding the parameter `'cssClass' => 'secondary-tab',` the right styling is applied to my new dynamic field. 👍 

```
                $form->addFields([
                    'viewBag[subject]' => [
                        'tab' => 'Subject',
                        'label' => 'Subject',
                        'type' => 'radio',
                        'span' => 'full',
                        'cssClass' => 'secondary-tab',
                        'options' => $topic_options,
                    ]
                ],'secondary');
```
I've seen that `addFields` can be used aswel, as long as you also define `secondary` as an extra parameter. I hope this can be useful to others aswel.

**Comment by maartenmachiels** [comment]
Damn, I was too quick. There seems to be a bug in a repeater field I've set up in the same layout. My newly generated field now shows up in two places. In the tab "Subject", but also just below each instance of my repeater. It isn't a styling issue, the HTML is generated two times. Is this a known bug?
