### ISSUE TITLE
Bugs with snippet editing on low screen resolutions

### ISSUE THREAD

**Issue by p2d0** [rainlab/pages-plugin#380]
![image](https://user-images.githubusercontent.com/8457664/51708939-34f05800-2036-11e9-9d92-27ca6bd09f3d.png)
![image](https://user-images.githubusercontent.com/8457664/51709410-5998ff80-2037-11e9-8289-9ce1c64b3f4e.png)

**Comment by Patriot720** [comment]
![image](https://user-images.githubusercontent.com/8457664/51711394-12157200-203d-11e9-8b8e-842b432a5b05.png)

**Comment by Patriot720** [comment]
![chrome_2019-01-25_00-52-18](https://user-images.githubusercontent.com/8457664/51711431-2b1e2300-203d-11e9-8cf1-b0d0fa835546.png)

**Comment by w20k** [comment]
@Patriot720, what version of the framework you use and plugin? Seems like it's a bug in octobercms (https://github.com/octobercms/october).

**Comment by Patriot720** [comment]
@w20k plugin: 1.2.20,
System build: 446

**Comment by daftspunk** [comment]
This is fixed in OCMS v3.4
