### ISSUE TITLE
Default values in repeaters not used

### ISSUE THREAD

**Issue by helmutkaufmann** [rainlab/pages-plugin#385]
I have included a repeater in my layout

`{repeater name="xxx" groups="themes/mercator-minimal/repeater/repeater.yaml" tab="Elements" prompt="Add Eelement" }
  {# parser fail if there is noting between open and close tag #}
{/repeater}`

In the YAML, I have specified default values for individual fields but they are ignored. I would have expected the fields to be pre-populated with default values. This is especially annoying as I have hidden fields that I would like to allocate default values.

Can this be fixed, please.

**Comment by LukeTowers** [comment]
What build and plugin versions are you using?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
