### ISSUE TITLE
One click to show subitems menu

### ISSUE THREAD

**Issue by exaline-ru** [rainlab/pages-plugin#386]
At the moment I need to click 2 times in the menu item to show the submenu items. It is necessary - 1 time to click and see the submenu items. Here is the menu code:

<nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar">

    
    <a class="navbar-brand" href="/">NavBar </a>

    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="true" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if staticMenu.menuItems %}
        {% set items = staticMenu.menuItems %}        
        
        <ul class="navbar-nav mr-auto">
            {% for item in items %}
                <li class="nav-item {{ item.isActive or item.isChildActive ? 'active' : '' }}
                    {{ item.items ? 'dropdown btn-group' : '' }}"
                >
                    <a class="nav-link {% if item.items %}'dropdown-toggle' {% endif %}"
                            {% if item.items %} id="dropdownMenu{{ item.title|replace({' ':'-'}) }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"{% endif %}
                       href="{{ item.url }}"
                    >
                        {{ item.title }}

                        {% if item.items %}<span class="sr-only">(current)</span>{% endif %}
                    </a>

                    {% if item.items %}
                        <div class="dropdown-menu dropdown" aria-labelledby="dropdownMenu{{ item.title|replace({' ':'-'}) }}">
                            {% for child in item.items %}
                                <a class="dropdown-item" href="{{ child.url }}">{{ child.title }}</a>
                            {% endfor %}
                        </div>
                    {% endif %}
                </li>
            {% endfor %}
        {% endif %}
           </ul>
         
        
         <form class="form-inline" method="GET" action="{{ searchForm.resultPage|page }}">
         <input class="form-control mr-sm-2" name="search" type="text" placeholder="Поиск" aria-label="Search">
         {% if searchForm.categoryFilter %}
        <select name="cat[]">
        {% for key,cat in searchForm.categories %}
        <option value="{{ key }}">{{ cat }}</option>
        {% endfor %}
        </select>
        {% endif %}
        <button class="form-control mr-sm-2" >{{ 'Search'|_ }}</button>
        </form>

        <div>           
               <a class="nav-item" href="">1</a>            
                <a class="nav-item" href="">2</a>          
                 <a class="nav-item" href="">3</a>            
          </div>
             
   </div>
    
</nav>

**Comment by w20k** [comment]
@exaline-ru could you provide a gif or screenshots of what you mean and what you want?

**Comment by exaline-ru** [comment]
**Status now:**
```
Item 1
Item 2 (**2 click to open sub items**:  --- Item 2.1....)
   --- Item 2.1
   --- Item 2.2
Item 3
...  
```
I would like to:
```
Item 1
Item 2 (**1 click to open sub items:**  --- Item 2.1....)
   --- Item 2.1
   --- Item 2.2
Item 3
...  
```

**Comment by LukeTowers** [comment]
> could you provide a gif or screenshots

Help us help you.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
