### ISSUE TITLE
Saving static page settings in Database

### ISSUE THREAD

**Issue by tfprado** [rainlab/pages-plugin#387]
I just need a point in the right direction here.

I am currently working on a new OctoberCMS project and relying heavily on static pages. I created two layouts, one with a sidebar and one without. Using a plugin I was able to use

```
 Event::listen('backend.form.extendFields', function($widget) {
```
to add extra fields to the static page settings (like picking a sidebar menu code). This has worked great in development, and by saving the menu code in the page viewBag and using that in the layout everything seemed to be working fine. The problem now arises when deploying to production and having editors test out different site features. The page settings seem to be getting lost when multiple content changes happen (sidebar ends up using a default menu code instead of the one previously set).

I noticed you guys are working on a branch to add a database layer for CMS objects (#3908), but since the website will be going to production soon I am leaning towards creating a plugin to save static page settings (meta title and descriptions and other custom settings). Something similar to [Page Settings Plugin](https://octobercms.com/plugin/isswp101-pagesettings).

These are the events used in that plugin to save settings:
```// Frontend
        Event::listen('cms.page.beforeRenderPage', function ($c, $page) use ($pageSettings) {
            $pageSettings->fillPage($page);
        });

        // Backend
        Event::listen('cms.template.processSettingsAfterLoad', function ($c, $template) use ($pageSettings) {
            if ($template instanceof Page) {
                $pageSettings->fillPage($template);
            }
        });

        // Backend
        Event::listen('cms.template.save', function ($c, $template) use ($pageSettings) {
            if ($template instanceof Page) {
                $pageSettings->save($template);
            }
        });

        Event::listen('cms.template.processSettingsAfterLoad', function ($c, $template) use ($pageSettings) {
            if ($template instanceof Page) {
                $pageSettings->setOriginalFileName($template->getFileName());
            }
        });
```

Does static pages use similar events? Would I just check for `instanceof \RainLab\Pages\Classes\Page`?

**Comment by LukeTowers** [comment]
Your best bet would probably be to use https://octobercms.com/plugin/axmit-storage until the core changes are ready. It would help speed them along if you could test them though
