### ISSUE TITLE
Perform changes on Pages item before rendering in backend

### ISSUE THREAD

**Issue by tfprado** [rainlab/pages-plugin#388]
So I am trying to make a plugin to save static page properties to a database table. I am using the `pages.object.save` event and I am able to save all the viewBag properties without an issue (both the regular ones like layout, title, etc and my custom ones as well).

I am getting hung up on how to add these back to the static page. Could someone point me to what event is triggered when a static page is opened in the backend?

Edit:
I am looking for something like [cms.template.processSettingsAfterLoad](https://octobercms.com/docs/api/cms/template/processsettingsafterload)

**Comment by bennothommo** [comment]
@tfprado What you could use depends on how you want to use the static page properties on opening the page. If you are wanting to insert the data into the model before displaying the page for example, you could extend the `\RainLab\Pages\Classes\Page` class and bind to the `model.afterFetch` event.

```
\RainLab\Pages\Classes\Page::extend(function($model) {
    $model->bindEvent('model.afterFetch', function() use ($model) {
        // ...
    });
});
```

There is currently no event that is comparable to `cms.template.processSettingsAfterLoad` for Static Pages. If you would like to see one, feel free to submit a PR of the intended event.

There is also work being done on a database layer for Static Pages objects here as part of a larger effort to introduce a database layer across all CMS objects. 
https://github.com/rainlab/pages-plugin/pull/368

**Comment by tfprado** [comment]
I will look into submitting a PR for a new event if this doesn't work out but for now it seems to meet my requirements.

If anyone else needs to change some static page variables (like adding settings from a database):


Bind new event to StaticPage model (Plugin.php)

```php
$pageSettings = new PageSettingsFacade();
StaticPage::extend(function($model) use ($pageSettings) {
            $model->bindEvent('model.afterFetch', function () use ($model, $pageSettings) {
                $pageSettings->fillPage($model);
            });
});
```

Add database settings to the page (classes/PageSettingsFacade.php)

```php
/**
     * Get settings from the database and merge them to a page.
     *
     * @param StaticPage $model
     */
    public function fillPage($model)
    {
        $key = $model->attributes['fileName'];
        $pageSettings = PageSettings::findByKey($key);
        if ($pageSettings) {
            $targetSettings['settings']['viewBag'] = array_only($pageSettings->settings, $this->getPageAttributes());
            $model->getViewBag()->setProperties($targetSettings['settings']['viewBag']);
        }
    }
```
This is my starting point for now, thanks for the help and feel free to close this issue

**Comment by bennothommo** [comment]
@tfprado Not a problem :)
