### ISSUE TITLE
Custom Styles / Paragraph Formats

### ISSUE THREAD

**Issue by sqwk** [rainlab/pages-plugin#390]
The rich editor for the pages plugin allows Heading 1, 2, 3 etc. Is it possible to tweak this list, to add or remove some?

Also, there is a button for a `blockquote` element. Is it possible to add buttons for other block level elements like, for example, `aside` or `section`?

At the moment I am using custom backend CSS to at least indicate to the user that certain block level elements are being used, but am entering them by hand in the code view. Halfway there.

    .field-richeditor aside {
        display:block;
        border: 1px dotted lightgrey;
        padding: 0 1em;
        margin: 1em 0 0 0;
        position: relative;
    }

    .field-richeditor aside:before {
        content: 'Aside';
        position: absolute;
        top: -0.75em;
        left: 0.75em;
        display: inline-block;
        background: white;
        padding: 0 0.5em;
        font-size: 0.75em;
    }

**Comment by bennothommo** [comment]
@sqwk There is currently no way through October CMS to add additional block-level elements to the rich editor "Paragraph Format" menu. However, if you go to **Settings -> System -> Editor Settings** in the backend and click on the **Markup Classes** tab, you can add additional classes to the "Paragraph Style", which you can then apply to your `<p>` tags and target in your stylesheet.

**Comment by LukeTowers** [comment]
@sqwk @bennothommo actually I believe you can extend the RicheEditor through JS that is loaded after the main build-min.js. See https://github.com/octobercms/october/issues/2078#issuecomment-310062139 for an example of extending the richeditor and https://www.froala.com/wysiwyg-editor/docs/concepts/custom/button for the docs on creating custom buttons
