### ISSUE TITLE
Duplicate textarea ids when adding new page

### ISSUE THREAD

**Issue by Rike-cz** [rainlab/pages-plugin#394]
October version: 454
Pages plugin version: 1.2.21

I have troubles with duplicity of textarea ids under RichEditor formwidget.

### Steps to reproduce
Add in RainLab.Pages two new pages and take a look on ids of generated hidden textarea elements. They are same.
![ids](https://user-images.githubusercontent.com/4247582/57837416-0d7af200-77c3-11e9-8795-8deb9d722536.png)

Froala does not have problem with this, but CKEditor finds textarea by id, so duplicate ids kill his instances.

**Comment by bennothommo** [comment]
@Rike-cz Whilst that does sound like a bug, we only officially support Froala. I presume you are using a plugin to implement CKEditor, is that correct?

**Comment by Rike-cz** [comment]
I have got own solution/plugin for CKEditor, not official plugin. But duplicate element ID is not correct with [HTML5 specification](https://www.w3.org/TR/html5/dom.html#element-attrdef-global-id) I think.

**Comment by w20k** [comment]
@bennothommo it's definitely a bug. CMS page does provide you with a unique Id, where Pages - not. Html5 also doesn't support duplicated Ids.

**Comment by bennothommo** [comment]
Thanks @Rike-cz and @w20k. I will review it soon.

**Comment by w20k** [comment]
@bennothommo could be this commit -> https://github.com/rainlab/pages-plugin/commit/eee885c0c7c136665af40b6e68e3f59f749eea5f

**Comment by bennothommo** [comment]
@w20k Probably, but it was removed for a reason. It's likely that we'll have to tweak the Pages plugin to generate some unique form aliases for each page tab.

**Comment by iboved** [comment]
It seems that the bug has been fixed in this commit -> https://github.com/rainlab/pages-plugin/commit/60a22613cbc88ce0c750bb634a8371c7ae83ce4b

**Comment by bennothommo** [comment]
Thanks for pointing that out @iboved.
