### ISSUE TITLE
Static menus broke

### ISSUE THREAD

**Issue by GinoPane** [rainlab/pages-plugin#398]
After the latest update for October CMS and for this plugin static menus on my theme (and on any other themes) stopped working.
I've tried to clean cache, re-add menus, switch themes and add new menus there. But with no luck. `__SELF__.menuItems` are always empty for the `StaticMenu` component.

UPD:

syncing with DB by `theme:sync` did not help, though the static menu YAML file was synced.

**Comment by GinoPane** [comment]
Ah, ok, found the solution in other issues. 
It would be good to hotfix the broken functionality asap, it is almost a week like the issue is still present.

**Comment by w20k** [comment]
@GinoPane comment or ping where you found the solution to fix it :) There is too many issues to track them all.

**Comment by GinoPane** [comment]
@w20k the fix is here: https://github.com/octobercms/october/pull/4362

I'm not happy with changes in this plugin. It behaves like a part of the core now.

**Comment by w20k** [comment]
@GinoPane there is a set of plugins that Devs use in pair with the core. I'd say they were meant to be `like the core`, but not exactly :) Not sure what you mean by that.
