### ISSUE TITLE
Seems like in 1.3.0 menu stop working

### ISSUE THREAD

**Issue by rizhenkov** [rainlab/pages-plugin#399]
After updating to 1.3.0 static menu not working. 

Quick debug shows that [`$menu->generateReferences($this->page)`](https://github.com/rainlab/pages-plugin/blob/master/components/StaticMenu.php#L80) in the StaticMenu component **always returning `[]`**;

After downgrading plugin version to 1.2.21 its working again.

`composer remove rainlab/pages-plugin`
`composer require rainlab/pages-plugin:1.2.21`
`php artisan plugin:refresh Rainlab.Pages`

**Comment by bennothommo** [comment]
@rizhenkov please see #396. This has been resolved and the fix should be available with the next release of October.
