### ISSUE TITLE
Error "Call to a member function property() on null" 

### ISSUE THREAD

**Issue by renderlife** [rainlab/pages-plugin#401]
https://github.com/rainlab/pages-plugin/blob/b1c6882f0ba8665d0b19566c85b1c444e300e029/controllers/Index.php#L535

![image](https://user-images.githubusercontent.com/9404857/60319739-42b95900-9999-11e9-9d89-62dae56b28b2.png)

**Comment by bennothommo** [comment]
As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/.github/CONTRIBUTING.md#reporting-an-issue-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by renderlife** [comment]
well, i will try

**Comment by renderlife** [comment]
reproduced the problem

![bag](https://user-images.githubusercontent.com/9404857/60323414-dbed6d00-99a3-11e9-8202-3738b89e9f43.gif)

**Comment by bennothommo** [comment]
@renderlife Thanks for that, but that is not a bug. If you remove the static page component from a layout, that layout cannot be used for static pages anymore.

**Comment by renderlife** [comment]
May provide a warning instead of a line number error?

**Comment by bennothommo** [comment]
@renderlife I've added in a workaround if the static page component is missing. See 27183f19.
