### ISSUE TITLE
Add event 'pages.object.delete' when items are deleted.

### ISSUE THREAD

**Issue by 2mt-heuser** [rainlab/pages-plugin#402]
There is a nice **'pages.object.save'** inside onSave() after the object wa saved, but onDelete() is missing something similar.

I thought it would be nice to have **'pages.object.delete'** in there as well to plug custom code in after the object is deleted.

**Comment by w20k** [comment]
@2mt-heuser you could create a PR to support it. Feel free!

**Comment by 2mt-heuser** [comment]
Hrm, sure. It's no big deal but I kinda wanted to ask first :) 

Maybe there's a reason why it isn't in there yet.

**Comment by w20k** [comment]
@2mt-heuser probably wasn't needed, or not considered. Can't tell for sure 😉

**Comment by 2mt-heuser** [comment]
@w20k There ya go, opened a PR for it.

**Comment by bennothommo** [comment]
@2mt-heuser @w20k I would imagine that most people have used the model `beforeDelete` and `afterDelete` events up to this point. :)

**Comment by w20k** [comment]
@bennothommo probably, haven't send pages plugin events ever)) Thought, they didn't exist)

**Comment by 2mt-heuser** [comment]
Well I kind of read top-down in the octoberdocs about extending plugins and event::listen. 
Always liked event-driven stuff so hooked myself into the save event of pages... 
Only to realize afterwards that the delete counterpart is missing. That's how it and me ended up here 😄

**Comment by daftspunk** [comment]
Closing because PR is closed
