### ISSUE TITLE
The menu cache is not cleared after saving the Page

### ISSUE THREAD

**Issue by iboved** [rainlab/pages-plugin#404]
OctoberCMS Build: 455
RainLab.Pages version: 1.2.21 

When I change the Page "Title" or "URL", the Menu does not change on frontend until I clear the cache via `php artisan cache:clear` command.

The problem is that when putting data to the cache, the plugin generates the cache `key` using the **frontend locale**. It also uses the **frontend locale** to get the data from the cache. **BUT** the plugin uses the **backend locale** to clear the Menu cache after saving the Page.

For example, the plugin puts the data to the cache by this key: `-1565638439static-page-menu-en`
But after saving the Page it clears the cache by this key: `-1565638439static-page-menu-en-gb`

There is a [getMenuCacheKey](https://github.com/rainlab/pages-plugin/blob/master/classes/Page.php#L676) method which fires the `pages.page.getMenuCacheKey` event to generate the menu cache key. The RainLab.Translate plugin listens to this event [here](https://github.com/rainlab/translate-plugin/blob/master/Plugin.php#L106-L109) and uses `Lang::getLocale()` to generate the menu cache key.

Here is the problem. If we save the Page, the plugin tries to clear the Menu cache but uses the wrong key (e.g. `-1565638439static-page-menu-en-gb`). Since `Lang::getLocale()` is called in the Backend area, it returns the Backend locale (in my example it is `en-gb`). But when the plugin puts/gets the data to/from the cache, it uses a different cache key (e.g. `-1565638439static-page-menu-en`). Since `Lang::getLocale()` is called in the Frontend area, it returns the Frontend locale (in my example it is `en`).

**Comment by LukeTowers** [comment]
@iboved could you review / test https://github.com/rainlab/translate-plugin/pull/496 and provide feedback?

**Comment by mjauvin** [comment]
@LukeTowers can you update and close this one? Has been resolved in RainLab.Translate

**Comment by LukeTowers** [comment]
Fixed by #496
