### ISSUE TITLE
media library outputs absolute url's for inserted assets in static pages

### ISSUE THREAD

**Issue by Iterl0** [rainlab/pages-plugin#405]
Hello,

I am experiencing an awkward problem related to Static Pages. If on a static page we insert an image via media manager, the resulting link will be an absolute link. If later, for example, a developer starts to use an external domain, (maybe CDN) to populate images on the site, and also this domain will likely get changed in the future, it's getting unclear how to efficiently manage such a transition in this existing case where image links are already hardcoded into static pages with a concrete domain.

This issue, for instance, doesn't arise on October cms regular pages thanks to twig `|media` filter, that will always output the relevant path to an image, based on the active media storage configuration in `config/cms.php` and `config/filesystems.php`.

It would be really handy to have a similar piece of twig functionality on static pages as well. Or maybe this issue already has an existing workaround in this current context.

Thank you for your attention in advance

**Comment by bennothommo** [comment]
@Iterl0 unfortunately there's no way currently to dynamically add the URL to media items in the visual editor that the Static Pages plugin provides, as the content is just straight HTML and is not run through a Twig parser.

**Comment by Iterl0** [comment]
@bennothommo thanks for confirming this case. Would there be any suggestion how to solve an issue like this? I know we can inject php logic into static pages via registering an arbitrary partial as a snippet, and attach it to a static page of our choice. But that kind of approach often breaks the overall integrity of the pages and may not prove to be appropriate in each particular case.

**Comment by LukeTowers** [comment]
@Iterl0 @bennothommo theoretically we could override what Froala uses for URLs to make them output relative URLs with some sort of flag to indicate that they should be parsed and then have an accessor on the page objects to parse that; although it would be difficult to also support the image previews in the richeditor itself at the same time because we'd have to tell it to display an image from one URL but store a completely different URL

**Comment by bennothommo** [comment]
@Iterl0 I generally work around it by keeping the rich editors as purely for textual content, and using [Dynamic Syntax Parser tags](https://octobercms.com/docs/services/parser#dynamic-syntax-parser) in the layout file to specify areas for images and other media (using the `{mediafinder}` tag allows us to generate the URL to the image through the `|media` filter as you stated). It's great for client websites as it prevents them from breaking the layout too much :)

@LukeTowers yeah I had thought of some sort of system like that too, however, I recall it being a pain to make Froala play nice with such a system. We can definitely look into it at some point.

**Comment by Iterl0** [comment]
yeah, its a good overall approach, thought of that too, but since the client would want to add images in the richeditor itself, we get back to the same problem again.

**Comment by Iterl0** [comment]
as for now I came up with only one idea to mimic the `|media` filter in static page content. I put a relative link to the image as `<img src="/storage/app/media/...">` and include the following rule in my .htaccess file
`Redirect permanent /storage/app/media http://some-cdn.com/storage/app/media`
from that point everything regarding assets seems working as expected. For now, I'm not sure if this could be considered as a clean solution, so anyone`s insight would be helpful

**Comment by Iterl0** [comment]
I am now looking for a way to read the cdn domain variable from .env file in .htaccess, so that everything regarding cdn config would reside in one place. Still not sure how to accomplish this, and would be glad if someone could give a hint here :)

**Comment by bennothommo** [comment]
@Iterl0 I'm not sure that's possible - you could potentially use real environment variables if you have control of the hosting service. That would basically replace the `.env` file entirely.

**Comment by bennothommo** [comment]
Re: your `.htaccess` rewrite, that should be fine as long as the media configuration settings are set up to store the files on the CDN as well.

**Comment by LukeTowers** [comment]
@bennothommo perhaps we could repurpose the snippet system somehow to make media uploads turn into snippets and then also do some work on the display of snippets?

**Comment by Iterl0** [comment]
> @Iterl0 I'm not sure that's possible - you could potentially use real environment variables if you have control of the hosting service. That would basically replace the `.env` file entirely.

you are right, thats the solution. I just created my env variable in `.htaccess` and later use it in cms config files via php `getenv()` method

**Comment by bennothommo** [comment]
@LukeTowers Hmm, the snippet system uses a `<figure>` tag in the rich editor to represent the snippet, so I think that might cause issues with the content display in Froala.

How I would approach it would be to do the following:
- If an image or file is added to the rich editor from the media finder, add an attribute to the element to note this: ie. `data-media`.
- Before save, find any elements in the content with `data-media` and prepend some form of tag or placeholder where the root URL will be added, ie. `%%URL%%`, replacing any other root URL provided.
- When passing the content through the model, rewrite `%%URL%%` as the current root URL where the media is stored.

This is making a big assumption: the folder where there media is stored is the same on both sources, and it's only the root URL which is changing. Perhaps some metadata will need to be stored with the page determining where the media was stored at the time of saving the content.

**Comment by LukeTowers** [comment]
Hmm, certainly a tricky situation with lots to consider. I can see lots of edge cases that could pop up. I'm going to say that for now an official solution to changing the domain serving assets to a CDN would be to use the htaccess until there's more demand to look into a more robust solution.

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/ccb2c372bb1fb3980c1240ffb2f7aeef5e786dae. Media library will no longer force absolute URLs unless `cms.linkPolicy` is set to `force`.
