### ISSUE TITLE
Featured image for Page

### ISSUE THREAD

**Issue by kutups** [rainlab/pages-plugin#407]
How do I make a featured image on a static page? Just like the blog.

**Comment by jeremymouton** [comment]
See Custom page fields https://github.com/rainlab/pages-plugin#custom-page-fields

In your layout:

```
[staticPage]
==

...

{{ featured_image | media }}

...

{variable name="featured_image" label="Featured Image" type="mediafinder" mode="image" tab="Featured Image" imageWidth="400"}{/variable}
```

**Comment by kutups** [comment]
Thank you @jeroennoten i will try it now

**Comment by kutups** [comment]
Hey @jeremymouton 

Hi, I couldn't find where to add this. Can you help?

**Comment by jeremymouton** [comment]
@kutups it needs to go inside one of the layout files in `/themes/<your theme name>/layouts/`.

The new featured image field will appear in the Pages backend when you select the layout.

**Comment by kutups** [comment]
![Ekran Resmi 2019-09-02 16 14 51](https://user-images.githubusercontent.com/13905793/64117072-d134c700-cd9c-11e9-85a3-dbc310ef2fd3.png)
 Thank you @jeremymouton

**Comment by w20k** [comment]
@kutups could you close the issue if it's resolved?! Thank you ;)
