### ISSUE TITLE
request: please provide a pages.menuitem.generateReferences event

### ISSUE THREAD

**Issue by Deracination** [rainlab/pages-plugin#408]
The pages.menu.referencesGenerated event only has access to MenuItemReference objects which have very little metadata.

The documented 'viewBag' mechanism assumes that filter criteria can be set on each menu item manually.

To make it possible to dynamically manipulate the menus (particularly filtering by user groups) please provide an event::fire at the top of Menu.php::generateReferences which receives a copy of $this->items for modification.

**Comment by LukeTowers** [comment]
Such an event would be called `pages.menu.beforeReferencesGenerated`, feel free to submit a PR for it

**Comment by daftspunk** [comment]
In the latest version, `PageLookupItem` is a model object, so support for dynamic attributes is available as requested.
