### ISSUE TITLE
Class 'Cms\Classes\Meta' not found

### ISSUE THREAD

**Issue by Bulmer** [rainlab/pages-plugin#413]
Whenever I try to access the home page after installing this plugin I get a "Class 'Cms\Classes\Meta' not found /octobercms/public/plugins/rainlab/pages/classes/Menu.php line 16" error. I can't seem to find anything about it.

**Comment by LukeTowers** [comment]
@Bulmer you need to update your core OctoberCMS installation. The latest version of this plugin requires Build 456 at least (but you should really always have the latest).

**Comment by Bulmer** [comment]
Thanks, that was it!

**Comment by chrisvidal** [comment]
having the same `Class 'Cms\Classes\Meta' not found` with October build 464

**Comment by LukeTowers** [comment]
@chrisvidal sounds like your code base isn't actually using 464, it might just be telling you that it is though.

**Comment by chrisvidal** [comment]
I can sense that ~ so, what is the best course of action here?

**Comment by chrisvidal** [comment]
can I change manually the Build in the table `system_parameters` to a previous version, and run the updates from the backend again? would that do the trick?

**Comment by bennothommo** [comment]
@chrisvidal You can try a "force update" and see if that resolves it. I believe that should re-download the latest modules.

**Comment by chrisvidal** [comment]
it worked ~ thanks so much
