### ISSUE TITLE
problems with the editor at rainlab.pages

### ISSUE THREAD

**Issue by arielandino** [rainlab/pages-plugin#414]
I have the following proble:
![img](https://i.ibb.co/74m8Ljb/2019-09-19-08-12-41-templates-Explorer-HCI-NOTE175-gardoino-Users.png)

It is the first time that happens to me, and I have been using it for 2 years.
Any idea why this happened?

**Comment by alxy** [comment]
Does this happen in other browsers as well? Does the JS console show any errors? Apart from that, you should specify which browser (version) and OS you are using, and which version of the plugin and OCMS you are using.

**Comment by arielandino** [comment]
This occurs in shared host, with php 7.2
I see it igal in chrome and firefoz. This is the error that occurs in the console:
![img](https://i.ibb.co/frmSsVC/2019-09-19-08-12-41-templates.png)

**Comment by bennothommo** [comment]
@arielandino Couple of things to check: 
- Does the issue occur just on that page, or does it occur on all pages?
- Have you made any changes to the Editor Settings in the Settings area of the Backend?
- Have you installed any plugins that add additional functionality to the Rich editor (Froala)?

**Comment by arielandino** [comment]
258/5000
This problem occurs only with the editor of this rainlabpage plugin, and I don't have any other plugin, I disabled them all.
There are no settings either.
It occurs to me that it is related to some component of PHP, although I do not think that one is missing.

**Comment by bennothommo** [comment]
@arielandino PHP *shouldn't* have any bearing on the rich editor. Just to eliminate some common issues, would you mind running `php artisan cache:clear` and `php artisan october:util compile assets` in your command line in the root folder of your project, and let us know if this resolves the issue?

**Comment by bennothommo** [comment]
@arielandino The fix provided in https://github.com/rainlab/pages-plugin/pull/421 might resolve the issue for you. Would you mind giving it a test and let me know if this is the case?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
