### ISSUE TITLE
The title field is required error appears sometimes even if I already have a title

### ISSUE THREAD

**Issue by MaTToX3** [rainlab/pages-plugin#419]
If I create a page and save it then I want to add another one, I get the following error even if I have a title that is required:

![image](https://user-images.githubusercontent.com/4114411/66115991-3fee8580-e5d2-11e9-8856-ee0a258be7f7.png)

Basically, I have to refresh the backend everytime I want to add a new page. 

The same issue appears if I enter the title then url then select a layout but this time the URL is marked as "required" - then I have to refresh again and select "Layout" first.

**Comment by bennothommo** [comment]
@MaTToX3 Which version of OctoberCMS and the Pages plugin are you running?

**Comment by bennothommo** [comment]
@MaTToX3 Would you mind testing the fix in #421 and let me know if this resolves the issue for you?

**Comment by MaTToX3** [comment]
Hey, thank you for all the effort!

I will begin testing now and be back to let you know. :)

**Comment by MaTToX3** [comment]
I still have to select "Layout" first otherwise I get the "URL is required" error if I enter the title and URL first.

However I don't have to refresh the backend anymore so this part seems to be working.
