### ISSUE TITLE
СhildPages component does not works with multilingual

### ISSUE THREAD

**Issue by VdomaNet** [rainlab/pages-plugin#425]
My solution is change in `plugins/rainlab/pages/components/ChildPages.php:43`
`$viewBag = $childPage->settings['components']['viewBag'];`
to
`$viewBag = $childPage->viewBag;`
It works for me

**Comment by LukeTowers** [comment]
@VdomaNet please provide more information about what exactly the problem is that you're encountering.

**Comment by VdomaNet** [comment]
I have multilingual site (En/Uk) and use the Pages and Translate plugins
In СhildPages component I always get Pages list (url, name) on the main language version (En)
and never get it in another language, (when I switch to Uk). 

so, СhildPages always shows pages list in En (in my default language) and never in Uk, when I switch to Uk I got En too

**Comment by LukeTowers** [comment]
@mjauvin are you able to look into this and test the fix?

**Comment by sagjatome** [comment]
The same Problem

**Comment by mjauvin** [comment]
@VdomaNet I'm not even getting the child pages list in the default language... how do you actually use this component?
