### ISSUE TITLE
How to define field for selecting arbitrary plugin model records

### ISSUE THREAD

**Issue by Nvironmental** [rainlab/pages-plugin#428]
Hi there, 

I can't seem to find any documentation for this or think straight, how can get my plugin records populated in the static page content area. So what I am looking for is, something like a record finder field where I can connect, say Users Plugin, and then select the User through the record finder. 

Please guide me to a starting point or documentation I may have missed.

**Comment by LukeTowers** [comment]
@Nvironmental you should be able to use `{variable type="recordfinder" list="$/rainlab/user/models/user/columns.yaml" useRelation="false" modelClass="RainLab\\User\\Models\\User"}`

**Comment by Nvironmental** [comment]
Hi @LukeTowers the above code works just what I intended to. However it only outputs the ID of the record not the record itself. 

How can I get actual record from the selection ? Would I have to fetch them via page initialisation functions like `onInit` or `onStart` ? 

Is there any other direct way to fetch them that I may be missing ?

**Comment by LukeTowers** [comment]
@Nvironmental you would have to fetch them in the page code functions you mentioned.

**Comment by maartenmachiels** [comment]
Hi Luke, just came across this and it works perfectly. Is there any way to have the recordfinder select multiple records? I could just put the recordfinder in a repeater, but this seems a little less elegant. Thanks in advance.

**Comment by LukeTowers** [comment]
@maartenmachiels no, the recordfinder is designed for selecting only one record. If you'd like a better interface for dealing with relationships with many records, then you should be looking at using the relationcontroller, although that would probably be tricky to make work with static pages. Depending on how many records you have you might also be able to use something like a checkboxlist to select multiple records.

**Comment by maartenmachiels** [comment]
Hi Luke, thanks for your clear answer. I did try to create a prepopulated checkboxlist, but it seems that the field "checkboxlist" doesn't work in Static Pages. I've used the following syntax:

`{variable name="mycheckboxlist" label="Select your option" tab="Options" type="checkboxlist" options="A:Test 1|B:Test 2|C:Test 3"}{/variable}`

But then the following error gets thrown:

`The model class RainLab\Pages\Classes\Page must define a method A:Test 1|B:Test 2|C:Test 3() returning options for the 'viewBag[mycheckboxlist]' form field.`

It would be nice if we were able to use all available October CMS fields in the Static Pages. Would you like me to create a separate issue for this or am I overlooking something?

**Comment by LukeTowers** [comment]
@maartenmachiels hmm, that should have worked. Something must be broken with how the options are getting parsed that is leading it to believe you specified a method name instead of an array of options. @bennothommo or @jaxwilko could one of you look into that?

**Comment by bennothommo** [comment]
@LukeTowers will have a look now.

**Comment by JaxWilko** [comment]
@bennothommo error thrown in: modules/backend/widgets/Form.php:1298

It looks like the handling for https://octobercms.com/docs/backend/forms#field-dropdown which is shared by checkboxlist is assuming a callable or a method to call on the current model. Any chance dropdown's logic changed and this is a side affect?

**Comment by bennothommo** [comment]
Thanks @JaxWilko - I don't recall anything recently changed with the option handling - your PR still hasn't been merged yet and that's the only thing I recall changing it, but will start looking there.

**Comment by bennothommo** [comment]
@JaxWilko @LukeTowers @maartenmachiels Got it! Fixed in https://github.com/octobercms/library/commit/bb6d88a0f8b33b535de71101ea281245ebe7267c.

**Comment by maartenmachiels** [comment]
Thanks @bennothommo for your very swift solution!!
