### ISSUE TITLE
External links in the menu not opening in new window

### ISSUE THREAD

**Issue by DavidOoms** [rainlab/pages-plugin#430]
- OctoberCMS Build: 464
- RainLab Pages Plugin Version: 1.3.2
- PHP Version: 7.4

### Description:
I tried adding external links in my website's menu (URL menu item with checkbox "External link" checked); These links should be opened on a new window according to the help text that is next to the checkbox, but the links are opening in the same window because the attribute target="_blank" isn not added in the generated HTML code. Is anyone else experiencing this?

I have the latest version of October CMS and the plugin installed (forced update again just to be 100% sure), didn't alter anything in the plugin code.

### Steps To Reproduce:
Follow steps described above.

**Comment by LukeTowers** [comment]
@DavidOoms how are you rendering the menu? Are you using a custom partial or the default `{% component staticMenu %}`?

**Comment by d-ooms-asugoconsulting-com** [comment]
Hi Luke. You're quite right to ask that question. I re-checked the website code and the partial that is used is PanaKour's Extend Translate plugin so the problem should be in there somewhere and not in the standard partial.
