### ISSUE TITLE
Cms\Classes\Meta not found

### ISSUE THREAD

**Issue by JortJacobs** [rainlab/pages-plugin#431]
- OctoberCMS Build: 464
- RainLab Pages Plugin Version: 1.3.2
- PHP Version: 7.3

### Description:
I get the error Cms\Classes\Meta not found.
/public_html/plugins/rainlab/pages/classes/Menu.php line 16

**Comment by LukeTowers** [comment]
@JortJacobs are you positive you're using Build 464? Do the contents of modules/cms/classes match the github repo?

**Comment by JortJacobs** [comment]
Hi @LukeTowers . 

Somehow I managed to see Build 464 on the backend as well as on the php artisan october:util set build. But I double checked and indeed the build was not 464. No clue.

Nevermind, I updated now via composer and for sure I am now really on build 464 and everything is running fine. Sorry for false reporting!

**Comment by LukeTowers** [comment]
No worries @JortJacobs that's just a byproduct of how the `october:util set build` command actually works. We've got plans to improve it in the future but for now it's not really reliable when it comes to determining the actual build being used.

**Comment by JortJacobs** [comment]
Good to know! Do you probably also know why the Build version is not yet shown anymore in /backend/system/updates?

**Comment by LukeTowers** [comment]
@JortJacobs if you update via composer then the build number wouldn't show there unless the `php artisan october:util set build` command was called as a part of the updating process as it is in the current composer.json file.

**Comment by chrisvidal** [comment]
I think I am having the same case.
I just updated a one year old project, and System Settings shows OC Build 464,
but I have `Class 'Cms\Classes\Meta' not found` when I navigate to the Pages Menu and my front-end theme.

**Comment by bennothommo** [comment]
@chrisvidal Might be an outdated record in the cache. Try `php artisan cache:clear` and see if that works.

**Comment by chrisvidal** [comment]
thanks @bennothommo 
same, clearing the cache didnt solve it

**Comment by bennothommo** [comment]
@chrisvidal Does the `modules/cms/classes/Meta.php` file exist in your install?

**Comment by chrisvidal** [comment]
no such class

**Comment by bennothommo** [comment]
@chrisvidal What has potentially happened is that October has run `php artisan october:util set build` which has set the build for your install without actually upgrading the files? Did you install October via the wizard, or using Composer? If using Composer, would you mind pasting your `composer.json` in here for us?

**Comment by chrisvidal** [comment]
it is an install with the Wizard from last year, around January 2019 I would say.
Hence I have no `composer.json`

**Comment by tarunhere** [comment]
Even I have just now updated year old october cms and now getting same error!
Cache clear didn't worked!? What next could I try. This is production site. Please help

**Comment by tarunhere** [comment]
when I do ````composer update```` from terminal, I get composer version 2 warning and also 
mmap() failed: [12] Cannot allocate memory

this error

**Comment by bennothommo** [comment]
@tarunhere Composer v2 support is still only partially working. You'll need to download Composer 1 for older sites and run that directly: you can [download Composer 1](https://github.com/composer/composer/releases/download/1.10.19/composer.phar) into your project folder, then run `php composer.phar` to run Composer 1 for the project only.

Then do a `composer update` and check that the `modules/cms/classes/Meta.php` file exists.

**Comment by tarunhere** [comment]
Thanks @bennothommo for timely reply. I was just abt to upgrade to composer 2. Phew... (due to prod, under pressure)
Ok, I don't see Meta.php and I had fixed swap error with composer install. But it is not working fine. Not sure what is latest laravel version used, in my application I see laravel as ````Laravel Framework 5.5.42````. Is ths correct or I need to completely update the codebase!?
Thanks for your support

**Comment by tarunhere** [comment]
Also, ````composer install```` or composer update - both command are taking too long time and then I am out of ssh session. Not sure why!
Any pointer to fix such issues?

**Comment by bennothommo** [comment]
@tarunhere If you are on the 1.0.x branch, which it sounds like you are, then Laravel 5.5.42 is fine.

Unfortunately there isn't anything I can suggest about the SSH timeout. You'll need to ask your server admin about that.

**Comment by tarunhere** [comment]
Thanks again for reply @bennothommo . I don't recall if I installed via git or via installed an year ago! 
 If I do composer install, it take long time and then gets killed automatic. Not a clue why!!
ok for branch 1.0.x - do I need to upgrade that? Is it required? or it is fine as it is.

**Comment by bennothommo** [comment]
@tarunhere Given you're trying to do this on a production site, I would stay on 1.0.x for the moment, and just run `composer update`. We are only supporting 1.1.x with new features and updates, but 1.0.x is still receiving security fixes as required.

Unfortunately, you will need `composer update` to work in order to correctly update though, as there may be changed required in the Composer dependencies.

**Comment by LukeTowers** [comment]
I would personally recommend that you upgrade to composer 2.0 & October v1.1 (Laravel 6)

**Comment by tarunhere** [comment]
For now, I have just copied Meta.php and site is up now. I am not able to see what build currently is working. I will definitely work on upgrade. Thanks for all help.
