### ISSUE TITLE
Error This URL is already used by another page

### ISSUE THREAD

**Issue by edermonteiro** [rainlab/pages-plugin#433]
When synchronizing my project my pages disappeared from my Pages MENU and I get this error when trying to create it again. "This URL is already used by another page." 
In fact the page exists because when using the browser I can see the page but in the backend in the pages menu it does not.

**Comment by LukeTowers** [comment]
@edermonteiro check your /meta/static-pages.yaml file, did it get corrupted?

**Comment by edermonteiro** [comment]
it seems not.
this file /meta/static-pages.yaml does not list the pages.
but the pages exist in /content/static-pages folder

**Comment by edermonteiro** [comment]
this is the file

![Capturar](https://user-images.githubusercontent.com/9534485/73871383-508f6080-483d-11ea-8b32-df7cf435773c.PNG)

**Comment by LukeTowers** [comment]
@edermonteiro if that file doesn't list the pages that's why they're not showing up. I don't know how you're "synchronizing your project" but check the original file and make sure they match or just add the missing pages directly following the same format.

**Comment by edermonteiro** [comment]
@LukeTowers The synchronization is with the Project ID of the october portal. but I no longer have the original file but I will add the missing pages. thanks alot

**Comment by LukeTowers** [comment]
Hmm. Let me know if it happens again and the exact steps you're taking to trigger it
