### ISSUE TITLE
Safe mode prevents translation of placeholder content

### ISSUE THREAD

**Issue by hallosascha** [rainlab/pages-plugin#434]
- OctoberCMS Build: 464
- RainLab Pages Plugin Version: 1.3.2
- RainLab Translate Plugin Version: 1.6.7
- PHP Version: 7.2

### Related to:
issue #174  

### Description:
When in safe mode, I cannot edit the translations of placeholder content (using the RainLab Translate Plugin). I can edit the content and its translations. I can edit the placeholder content of the default language. But editing placeholder content of another language gives me the warning "Safe mode is currently enabled. Editing the PHP code of CMS templates is disabled."

### Steps To Reproduce:
- Use StaticPages and Translate Plugin. 
- Define a language that is not default. 
- Create a static page with a layout which defines a placeholder.
- Edit the placeholder content for the non-default language.

Thanks for looking at the issue! (should this issue also be opened for the Translate Plugin?)

**Comment by bennothommo** [comment]
@hallosascha This should be fixed with this commit to the Translate plugin: https://github.com/rainlab/translate-plugin/commit/610aa791368448d29a217ff54aec0330534364bd

**Comment by hallosascha** [comment]
Wow, that was quick! Thanks a lot!
