### ISSUE TITLE
Snippet property shown twice in inspector

### ISSUE THREAD

**Issue by kavishdahekar** [rainlab/pages-plugin#440]
- OctoberCMS Build: 465
- RainLab Pages Plugin Version: 1.3.3
- PHP Version: 7.4.5

### Description:
After adding a snippet to a static page, when you double click to view its properties in inspector, a property is shown twice.

### Steps To Reproduce:
Bug is reproducible in Rainlab Relax theme as well as locally using custom theme. Reproducing will be easy using rainlab relax.
- Install rainlab relax theme.
- Go to page "Home" in static pages and click "Client Area" tab to see the Client Area snippet already added to the page.
- Double click the snippet to open inspector.
- Although the snippet should have only one property "Redirection page", inspector shows the same property twice.

### Screenshot
![image](https://user-images.githubusercontent.com/3937361/82451369-880fd900-9acb-11ea-9ba8-09fd3c964e5c.png)

**Comment by LukeTowers** [comment]
@kavishdahekar please post the component code for that snippet.

**Comment by kavishdahekar** [comment]
This is snippet code I found in `themes/rainlab-relax/partials/snippets/login.htm`
```
description = "Shows the client area sign in form"

[viewBag]
snippetCode = "login-module"
snippetName = "Sign in module"
snippetProperties[redirect|type] = "string"
snippetProperties[redirect|title] = "Redirection page"
snippetProperties[redirect|default] = "/clients"
==
{% if user %}
    <p>You are logged in</p>
    <p>
        <a href="{{ 'clients'|staticPage }}" class="btn btn-default">
            Access Client Area
        </a>
    </p>
{% else %}
    {{ form_ajax('onSignin', {
        redirect: 'clients'|staticPage,
        class: 'module-form'
    }) }}
        <label>{{ loginAttributeLabel }}</label>
        <input type="text" name="login" value="" class="text" />

        <label>Password</label>
        <input type="password" name="password" value="" class="text" />
        <button type="submit" class="submit">Sign in</button>
    {{ form_close() }}

    <div class="row">
        <div class="col-md-6">
            <a href="{{ 'forgot-password'|page }}">
                Forgot password?
            </a>
        </div>
        <div class="col-md-6 text-right">
            <a href="{{ 'account'|page }}">
                Sign up
            </a>
        </div>
    </div>
{% endif %}
```

**Comment by bennothommo** [comment]
@LukeTowers @kavishdahekar it is a bug, but a low priority one. The problem stems from the fact that clicking multiple times on the snippet fires off several of duplicate AJAX queries. I was able to get three of the same property to come up by rapidly clicking three times on the snippet placeholder before the property editor showed. If you click the snippet placeholder once (which I believe is the intended action), the property only shows up once.

The simple fix is to prevent duplicate AJAX queries from being fired when clicking on the placeholder.

**Comment by kavishdahekar** [comment]
Thanks @bennothommo . The double click was sort of a natural response for wanting to bring up the inspector 😁, but glad it uncovered a bug albeit a low priority one. cheers!

**Comment by bennothommo** [comment]
No worries @kavishdahekar, thanks for bringing it to our attention!
