### ISSUE TITLE
Pages wont open after updates installedv

### ISSUE THREAD

**Issue by RaelKbg** [rainlab/pages-plugin#442]

**Comment by LukeTowers** [comment]
@RaelKbg please open your developer tools console and tell us what you see there.

**Comment by RaelKbg** [comment]
Good day 

After installing /rainlab/pages pluggin updates, the website and octobercms started giving error, need help with the pluggin please

Thank you

**Comment by LukeTowers** [comment]
Please post what the error is, can't help you if you don't tell us what error you're getting. Also, consider signing up for premium support if your website is important to your business: https://octobercms.com/premium-support

**Comment by RaelKbg** [comment]
![error 2](https://user-images.githubusercontent.com/15814873/84603663-51419e80-ae90-11ea-876d-5e3e3a5b7c7c.JPG)
![error 1](https://user-images.githubusercontent.com/15814873/84603664-530b6200-ae90-11ea-8828-0cfd952fc03f.JPG)


These are the 2 errors that I get when opening the website and when trying to access pages from octobercms

**Comment by RaelKbg** [comment]
Hi Luke, please the errors thats Im getting

**Comment by LukeTowers** [comment]
@RaelKbg you need to update the October core. If you're using composer, run `composer update`. If you are not, then you'll need to temporarily disable this plugin by moving it out of the plugin folder, and then go to the backend and update October itself, and then add the plugin back in.

**Comment by RaelKbg** [comment]
Hi @LukeTowers, I've never worked with october this is new for me. Im working on the october back end, I cant find composer. I disabled the pages plugin, forced the update to run but the issue hasnt cleared.

**Comment by LukeTowers** [comment]
What version of PHP are you using?

**Comment by bennothommo** [comment]
@RaelKbg what version of October is reported in the backend (in the Updates & Plugins settings page)? Does running `php artisan cache:clear` help out?

**Comment by RaelKbg** [comment]
Hi Guys, sorry i've been swamped with other stuff. We restored the website to an early version before the update. it;s back on

To answer your questions. I'm unable to see what version of PHP this website is on. @bennothommo how do I run that php artisan cache:clear??? please see attached the picture of what october looks like on my side

**Comment by RaelKbg** [comment]
> 

> 

- [ ]   #@`[](url)`

**Comment by RaelKbg** [comment]
![October](https://user-images.githubusercontent.com/15814873/84812561-e36fb100-b00e-11ea-9399-14356083adcc.JPG)

**Comment by LukeTowers** [comment]
@RaelKbg create a new CMS page and in the code section put 
```php
function onStart() {
    phpinfo();
}
```
then visit the page in the frontend and show us what it says.

**Comment by RaelKbg** [comment]
![php version](https://user-images.githubusercontent.com/15814873/84815230-0603c900-b013-11ea-874c-98b428b8a805.JPG)

**Comment by LukeTowers** [comment]
@RaelKbg check config/cms.php and make sure disableCoreUpdates is set to false. Then check for updates again

**Comment by RaelKbg** [comment]
Hi @LukeTowers please forgive my ignorance but where should I go to disable the core update?? this is completely new to me

**Comment by LukeTowers** [comment]
@RaelKbg check your *config/cms.php* file and make sure that `disableCoreUpdates` is set to false. It should look like: https://github.com/octobercms/october/blob/develop/config/cms.php#L134

**Comment by RaelKbg** [comment]
Hi @LukeTowers iv disabled teh core update and managed to installed the pluggin updates successfully, unforturnaly that messed up the website design 
![menus](https://user-images.githubusercontent.com/15814873/84830720-3d31a480-b02a-11ea-8d18-86c0ea638d23.JPG)

**Comment by RaelKbg** [comment]
also do you know what could be causing this error?? im unable to update something on the website
![error](https://user-images.githubusercontent.com/15814873/84830789-6fdb9d00-b02a-11ea-873d-8e5b6f04ad0e.jpeg)

**Comment by LukeTowers** [comment]
Any number of things can cause a 403 forbidden error but in this case it's probably either misconfigured file permissions or server configuration. The design breaking sounds like one of your plugins that are supposed to be present broke or maybe it broke because your server is not responding correctly to certain asset paths. I can't help you any more without access to your server itself. Do you have any IT support from your hosting company?

**Comment by RaelKbg** [comment]
No I dont. looks like I need to get more support for this. 

regarding the disableCoreUpdates should I leave it to false?? or can I turn it back on with true??

**Comment by bennothommo** [comment]
@RaelKbg Always leave it `false` unless you are using Composer, or you don't want any further October CMS updates.

**Comment by RaelKbg** [comment]
thank you
