### ISSUE TITLE
menu.yaml is cut off after line 1199

### ISSUE THREAD

**Issue by tilljedamczik** [rainlab/pages-plugin#443]
- OctoberCMS Build: 465
- RainLab Pages Plugin Version: 1.3.3
- PHP Version: 7.2.11

### Description:
We want to create a menu with 100+ entries, but the editor limits the size of the menu.yaml. The menu.yaml is cut off after line 1199 (see screenshot).

### Steps To Reproduce:
Create menu.yaml with more than 1199 lines, save it and try to change it with the backend editor.

### Screenshot:
![static_pages_menu_yaml-error](https://user-images.githubusercontent.com/14052311/84882733-faa2b300-b08f-11ea-8bc9-14e1d811cf2f.png)

**Comment by bennothommo** [comment]
@tilljedamczik Please upgrade to Pages plugin 1.3.5 - this issue was fixed in [1.3.4](https://github.com/rainlab/pages-plugin/releases/tag/v1.3.4).

**Comment by tilljedamczik** [comment]
Perfect, thanks for the quick response!
