### ISSUE TITLE
Getting undefined method from the menu item in pages

### ISSUE THREAD

**Issue by chungvlei** [rainlab/pages-plugin#446]
- OctoberCMS Build: 456 
- RainLab Pages Plugin Version: 1.3.3
- PHP Version: 7.3

### Steps To Reproduce:

I am getting this error if I go to pages (at the top navigation) > menu (on the left navigation) > any menu that I created
`"Call to undefined method October\Rain\Halcyon\Builder::getParent()" on line 789 of /var/app/current/vendor/october/rain/src/Halcyon/Builder.php`

I also noticed that was a POST to "/backend/rainlab/pages" and returned a "500 (Internal Server Error)" when I clicked on the any item on the menu.

**Comment by LukeTowers** [comment]
@chungvlei are you able to provide the full stack trace? Also, please update to 468 of October and 1.3.5 of RainLab.Pages

**Comment by chungvlei** [comment]
@LukeTowers 
Sure, here is the trace from the event log.
[trace.txt](https://github.com/rainlab/pages-plugin/files/5024373/trace.txt)

**Comment by LukeTowers** [comment]
@chungvlei did you update the plugin? Please do so, attempt to recreate the issue, and then submit the new stack trace and the contents of plugins/rainlab/pages/controllers/Index.php

**Comment by bennothommo** [comment]
@chungvlei @LukeTowers a missing `getParent` method exception would imply that the `NestedTree` trait is not being included. Have you removed or modified that at all?

**Comment by chungvlei** [comment]
@bennothommo We did some modification but we are adding more functions to the UI but not removing anything from the code. Which file should I check to see if the NestedTree is included or not?

**Comment by bennothommo** [comment]
@chungvlei Sorry it appears I'm mistaken - there is a `getParent` method that is part of the `Page` class in the Pages plugin. They don't use the `NestedTree` trait as that's only for database models. Are you extending the Page plugin functionality in any way through events, perhaps?

**Comment by chungvlei** [comment]
Unfortunately no, we added the functions without using extend so that is preventing us to upgrade it to the latest version. We are trying to move the custom features using the extend but it may take us a while to move everything as that also involve some UI changes.

**Comment by LukeTowers** [comment]
@chungvlei sounds like it's an issue in your code then. We can't support customizations made directly to the plugin codebase.
