### ISSUE TITLE
Unlinking from navigation?

### ISSUE THREAD

**Issue by inalto** [rainlab/pages-plugin#447]
When hiding from navigation, in a page, the title of the page correctly disappear from static breadcrumbs.
I think could be a good idea to also have a switch "not linked" that just does not put a link on the breadcrumb but the name is still there and act as a "separator".

**Comment by LukeTowers** [comment]
@inalto you should be able to do that yourself, either by using the custom class, or the generic attributes section and then reading from those values in your breadcrumb rendering code.
