### ISSUE TITLE
On 1.3.5 pages opens two times

### ISSUE THREAD

**Issue by xitara** [rainlab/pages-plugin#448]
- OctoberCMS Build: 468
- RainLab Pages Plugin Version: 1.3.5
- PHP Version: 7.3/7.4

### Description:
if I click on a existing page in static pages, the first page opens in one tab
every page after the first, the page opened 2 times (2 tabs)
if two tabs are open, saving has no effect. 
this issue was not on 1.3.3

Testet on two machines, one with build 468, ohne with composer-hash 432e4f88044b358be62c554cf78f2e2c
downgrading plugin to 1.3.3 on the build 468 solves the problem (delete folder /pages and copy old one.
downgrading with artisan has no effect)

### Steps To Reproduce:
go to "pages"
open one existing page
open another existing page

![Bildschirmfoto_2020-08-19_16-13-45](https://user-images.githubusercontent.com/26457767/90646470-87582180-e237-11ea-9cf9-7fa2bcd6fbb9.png)

**Comment by LukeTowers** [comment]
@xitara is there anything in your browser dev console? Sounds like you might be loading some JS more than once.

**Comment by xitara** [comment]
I found the problem: On deactivating the plugin Inetis.RicheditorSnippets (v2.1.3) the pages opens only one time.
Don't know, it is a bug in this plugin or in rainlab.pages

here's a dev-console screenshot with activated Inetis.RicheditorSnippets:
![Bildschirmfoto_2020-08-20_11-00-56](https://user-images.githubusercontent.com/26457767/90751357-53800900-e2d6-11ea-8c92-5363b9c200c7.png)

**Comment by LukeTowers** [comment]
@xitara sounds like a bug in their plugin, submit an issue to their repository.
