### ISSUE TITLE
Add extra types to snippet properties | richeditor + mediauploader etc

### ISSUE THREAD

**Issue by wordshop-git** [rainlab/pages-plugin#449]
Sorry if this is the wrong place to put this

To begin we've been creating snippets that we use on our sites to allow users to build up better-looking sites from within static pages

Up until now, we've been getting by with using 'type: string' to copy and paste large blocks of text into these snippets but it would be great if we could add a 'type:richeditor' to the snippet properties to allow us to enter and style larger blocks of code without the users ever having to write any html.

![image](https://user-images.githubusercontent.com/58780682/93236088-51468880-f776-11ea-9373-d566fe903174.png)

As above I'd like to be able to have a richeditor in the red box and a media uploader in the green box

I'm more than happy to work towards making a pull request if this is something that will be useful to others

After searching through the plugin code I can't make out where these type fields are being rendered so would need to be pointed in the right direction

**Comment by LukeTowers** [comment]
@wordshop-git they're handled by the Inspector JS in /modules/system/assets/ui/js/inspect.*.js files.

**Comment by bennothommo** [comment]
@wordshop-git As an alternative, you could use the **Content** section in the **Pages** plugin to define the contents for these types of fields, and then simply have a dropdown of all content blocks available in the Snippet properties instead.

**Comment by wordshop-git** [comment]
> @wordshop-git As an alternative, you could use the **Content** section in the **Pages** plugin to define the contents for these types of fields, and then simply have a dropdown of all content blocks available in the Snippet properties instead.

Is this functionality already in place? Can I pass the **Content** list to a snippet property drop-down by default?

I like the idea of this although it requires users to jump in and out of the content and the page to do what could be as simple as making a word bold

**Comment by wordshop-git** [comment]
> @wordshop-git they're handled by the Inspector JS in /modules/system/assets/ui/js/inspect.*.js files.

Thanks for this, am I right in thinking that the current `inspector.editor.string.js` is what gets called when you have `type: string` set against your snippet?

If that's the case I'd have to create an `inspector.editor.richeditor.js` file that would render a rich editor instead of a standard text field?

**Comment by LukeTowers** [comment]
@wordshop-git that's correct, but you'd also have to go through the other Inspector JS files to figure out where else you have to add references / handling to make it work.

**Comment by bennothommo** [comment]
@wordshop-git You'd likely need to have a plugin provide the dropdown list of content files - I don't believe there's any in-built functionality to generate this list, AFAIK.

I'm not sure I'm on board with allowing richeditor fields in the properties for the simple fact that it's a very "heavy" widget, and may not function well in the small space that the properties editor provides.

**Comment by LukeTowers** [comment]
It would definitely have to be a popup modal to handle the contents.

**Comment by wordshop-git** [comment]
> @wordshop-git that's correct, but you'd also have to go through the other Inspector JS files to figure out where else you have to add references / handling to make it work.

@LukeTowers I see what you mean, well if I ever get time I might have a look into it

@bennothommo I was imagining it as a popup rather than an inline field, but it seems like it's pretty complicated and if you guys don't think it's something you'd want to support I can just try and sort a system that will allow us to link Content fields to the Snippet

If adding a rich editor to a snippet is a no go could we try to add support for page variables against the content blocks as you can in a page/ layout? That way we could have content blocks that have a fixed layout and allow users to add them to a page? Although this sounds like functionality that already exists in another plugin somewhere

**Comment by LukeTowers** [comment]
@wordshop-git to be clear, I support the addition of richeditor and mediafinder field types in the inspector, we just can't have the richeditor be inline. It's definitely somewhat complicated to add support, which is why nobody's done it yet, but it's not impossible.

**Comment by wordshop-git** [comment]
> @wordshop-git to be clear, I support the addition of richeditor and mediafinder field types in the inspector, we just can't have the richeditor be inline. It's definitely somewhat complicated to add support, which is why nobody's done it yet, but it's not impossible.

@LukeTowers Well being completely honest I'm probably not the man to do it but I'll definitely give it a shot, I think it would be nice as it allows devs to create partials convert them to snippets, and then tell a user to go in a build the page up just by adding snippets. Thanks for the help I'll see how I get on if I believe it's way over my head shall I close this issue or leave it be for now?

**Comment by wordshop-git** [comment]
@LukeTowers @bennothommo First snag is I can't find the `propertyEditors` namespace as per this error

`Uncaught Error: The Inspector editor class "richeditor" is not defined in the $.oc.inspector.propertyEditors namespace.`

Looked through the following files and none of it makes any sense to me so taking a break for now ahah

![image](https://user-images.githubusercontent.com/58780682/93464720-84595b00-f8e1-11ea-93c1-30094a8a3a40.png)

**Comment by wordshop-git** [comment]
Right so spent all day on this so far and I think I'd be better off just making a plugin to give us the functionality I'm looking for rather than trying to extend the current functionality of the system, it's just going to take me way too long and I can't justify the time at work this is as far as I've gotten:

![image](https://user-images.githubusercontent.com/58780682/93480758-b2e13100-f8f5-11ea-950c-c247473c94aa.png)

I'm not sure how you guys intend this functionality to work and I'm pretty sure someone would have to walk me through the whole process of getting this working so really not much benefit to yourselves either

I'm basically calling it for now and will just find a workaround, thanks for the help!

**Comment by LukeTowers** [comment]
@wordshop-git looks like you're making decent progress so far, the community would appreciate it being available for everyone :)

Did you figure out how to get the class to register or do you still need help on that front? It should be just needing to add the file to the JS file in assets/ui/js that loads all the other inspector JS files.

**Comment by wordshop-git** [comment]
> @wordshop-git looks like you're making decent progress so far, the community would appreciate it being available for everyone :)
> 
> Did you figure out how to get the class to register or do you still need help on that front? It should be just needing to add the file to the JS file in assets/ui/js that loads all the other inspector JS files.

@LukeTowers Thanks, I'm not sure if I did it correctly but I copied the line in `storm.js` that registered the `inspector.string` but replaced it with my `richeditor` class I messed around getting it to setup a text editor and stuff but from here I have no idea where to go from here

I'll give it another shot then I'll need some help in terms of git setup. What steps do I need to take to create a good git setup?

Also how do we want the richeditor/ modal to appear in the inspector? I'm assuming you'd rather not use a button as I have above I was mainly messing about to see what I could put in there. I'd guess we'd want some kind of preview in the field just to show that it's not blank and then the modal get's called when you focus the element?

**Comment by LukeTowers** [comment]
@bennothommo is your CLI tool ready for the contributor install process?

@wordshop-git I think a button can be fine, something like "Edit content" with the styling maybe shrunk down to fit inside the inspector window better, but that's a minor detail.

**Comment by wordshop-git** [comment]
> @bennothommo is your CLI tool ready for the contributor install process?
> 
> @wordshop-git I think a button can be fine, something like "Edit content" with the styling maybe shrunk down to fit inside the inspector window better, but that's a minor detail.

@LukeTowers That sounds good then, is there a pop up modal I can hook into that'll open centered in the page kind of like the relation manager popups you can create? Also can I pull anything from the https://octobercms.com/docs/ui/ page to use in the backend? I'm assuming I should avoid styling stuff myself to try and keep the Ocotber feel intact?

**Comment by LukeTowers** [comment]
@wordshop-git that's correct re: the UI docs. See https://github.com/octobercms/october/blob/develop/modules/backend/behaviors/relationcontroller/assets/js/october.relation.js#L12-L25 for how popups are handled by the relationcontroller.

**Comment by wordshop-git** [comment]
> @wordshop-git that's correct re: the UI docs. See https://github.com/octobercms/october/blob/develop/modules/backend/behaviors/relationcontroller/assets/js/october.relation.js#L12-L25 for how popups are handled by the relationcontroller.

@LukeTowers I've found an `editor.popupbase.js` that loads a nicer popup like so -
![image](https://user-images.githubusercontent.com/58780682/93622519-31f96680-f9d5-11ea-9156-5dedf6f8bdb5.png)

You open it by clicking the form field but we could just as easily give that a tag some styling so it's clearer what clicking on that field does

I think I should just be able to call a richeditor here -
![image](https://user-images.githubusercontent.com/58780682/93622634-5fdeab00-f9d5-11ea-9bc6-3a5bf53f3976.png)
And then try and pass the richeditor content to the onSubmit function which will automatically send it to the correct place within the snippet markup on the page?

If this is the wrong way to go about it please let me know as I really don;t know what's best practice here!

Thanks for the help so far but it's already starting to feel like this might be possible!

**Comment by wordshop-git** [comment]
@LukeTowers In regard to the relation controller that'll definitely help, maybe I'd be better off setting it up that way as the relation controllers already support richeditors

**Comment by bennothommo** [comment]
> @bennothommo is your CLI tool ready for the contributor install process?

@LukeTowers not yet, unfortunately :(

**Comment by daftspunk** [comment]
WRT to the OP's issue - inline HTML inside a snippet results in HTML inside HTML. It is advisable to make reference to a Tailor entry, or a Content Block instead. Here's a link: https://docs.octobercms.com/3.x/cms/themes/content.html
