### ISSUE TITLE
The YAML value does not appear to be valid UTF-8. with october 1.1

### ISSUE THREAD

**Issue by insology** [rainlab/pages-plugin#451]
- OctoberCMS Build: 1.1
- RainLab Pages Plugin Version: 1.3.5
- PHP Version: 7.3

### Description:
When try to access to pages section in backend return the error The "
<img width="1178" alt="Schermata 2020-09-18 alle 12 26 14" src="https://user-images.githubusercontent.com/3527474/93587622-79b6c880-f9aa-11ea-9535-73e9f121f70e.png">
YAML value does not appear to be valid UTF-8"

### Steps To Reproduce:
Install plugin in october 1.1 and visit the pages section in backend

**Comment by LukeTowers** [comment]
@insology is this on a completely fresh install of October or do you have an existing theme with YAML files?

**Comment by insology** [comment]
@LukeTowers is an upgrade from 1.0 to 1.1

**Comment by LukeTowers** [comment]
@insology please post any .yaml files in your theme

**Comment by insology** [comment]
`name: 'Juicy Music'
description: 'Custom theme for Juicy'
author: 'Insology Studio S.r.l.'
homepage: https://www.insology.com/
code: '1.0'`

**Comment by insology** [comment]
name: 'Juicy Music'
description: 'Custom theme for Juicy'
author: 'Insology Studio S.r.l.'
homepage: https://www.insology.com/
code: '1.0'

**Comment by insology** [comment]
name: Main
items:
    -
        title: Who
        nesting: '0'
        type: static-page
        url: ''
        code: ''
        reference: who
        cmsPage: ''
        replace: '0'
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
    -
        title: Artists
        nesting: ''
        type: cms-page
        url: ''
        code: ''
        reference: artists
        cmsPage: ''
        replace: ''
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'

**Comment by insology** [comment]
items:
    -
        title: 'Contact us'
        type: cms-page
        code: ''
        reference: contacts
        viewBag:
            isHidden: '0'
            cssClass: ''
            isExternal: '0'
name: Secondary

**Comment by insology** [comment]
static-pages:
    who: {  }
    cookie-policy: {  }
    privacy-policy: {  }

**Comment by insology** [comment]
[yaml.zip](https://github.com/rainlab/pages-plugin/files/5246722/yaml.zip)

**Comment by insology** [comment]
found the issue, was a temp file ._ created on my mac.
Thanks a lot!
