### ISSUE TITLE
Text files in Content section OctoberCMS 1.1

### ISSUE THREAD

**Issue by panakour** [rainlab/pages-plugin#453]
- OctoberCMS Build: 1.1
- RainLab Pages Plugin Version: latest
- PHP Version: 7.4

Content section does not accept .txt file as it was in older octobercms version

![image](https://user-images.githubusercontent.com/12927166/94812996-25770400-0400-11eb-98c2-0e2c6aa4bbbe.png)

**Comment by LukeTowers** [comment]
@panakour could you show us your usage exactly?

**Comment by panakour** [comment]
@LukeTowers I just figured out that the issue occurs only when I have more than one language.
![Peek 2020-10-02 11-50](https://user-images.githubusercontent.com/12927166/94905384-74c34000-04a5-11eb-98e3-fbe22696f583.gif)

**Comment by LukeTowers** [comment]
@bennothommo @mjauvin any ideas?

**Comment by bennothommo** [comment]
@LukeTowers no idea - will have to run some tests.

**Comment by mjauvin** [comment]
didn't even know txt was allowed. I thought it was only accepting htm/md files...

**Comment by mjauvin** [comment]
yop, docs does list txt files as valid.

**Comment by mjauvin** [comment]
what's odd is that the allowed extensions are defined in base Content.php only and the MLContent or its ancestors never reach that class, they extend CmsCompoundObject... so this should not have worked with branch 1.0 either.

**Comment by mjauvin** [comment]
Ok, so if you add the allowedExtensions from modules/cms/classes/Content.php to MLContent.php (in RainLab/Translate) this solves the issue.

**Comment by LukeTowers** [comment]
Fixed by https://github.com/rainlab/translate-plugin/commit/a52d08a62141e44414d29ed130894233e0f50e22
