### ISSUE TITLE
Bump the plugin version

### ISSUE THREAD

**Issue by friiks** [rainlab/pages-plugin#456]
I was not sure if I should create a new PR for this as the repo owner should probably decide about versioning, but I noticed that [this](https://github.com/rainlab/pages-plugin/pull/445) this PR has been merged, but the version has not been bumped.
I assume that's how the marketplace checks if it should be updated.

I have added the fix manually for now, but that's not a maintainable solution.

**Comment by LukeTowers** [comment]
@bennothommo handles bumping the version

**Comment by bennothommo** [comment]
@friiks the next version - 1.3.6 - is still waiting one final PR to be completed and merged before I release the next version (https://github.com/rainlab/pages-plugin/pull/450).

**Comment by friiks** [comment]
Understood, thanks for the clarification!
