### ISSUE TITLE
Build 261

### ISSUE THREAD

**Issue by jamiegrand** [rainlab/pages-plugin#46]
Not sure how to fix this but when I updated to build 261, the static pages plugin is no longer working. any pages created remain blank. I notice this happening on sites that I created in beta and updated to to rc  server logs show.

 [Mon Jun 08 17:07:23.280599 2015] [core:notice] [pid 1168] AH00051: child pid 1998 exit signal Segmentation fault (11), possible coredump in /etc/apache2

**Comment by daftspunk** [comment]
This should be fixed by https://github.com/octobercms/october/commit/84da449d055385c42eb220840a408463ddfc12f3
