### ISSUE TITLE
Problem with richeditor inside repeater and polish words

### ISSUE THREAD

**Issue by hnitek** [rainlab/pages-plugin#464]
- OctoberCMS Build: 469
- RainLab Pages Plugin Version: 1.3.6
- PHP Version: 7.4

### Description:
I have a problem with Polish words in repeater field. For example when I input work "także" in richeditor inside repeater, I cannot save page because this error occurs:
![Screenshot 2020-10-15 at 18 36 36](https://user-images.githubusercontent.com/2734780/96160123-d4920000-0f15-11eb-8b4b-af36d2847a6d.jpg)

and when I change one char ("takze" instead of "także"), it works finne.

Problem occurs only in richeditor which is placed inside repeater.

I've never had a case like this before and I have been having this problem in three projects for about 2 weeks now and I cannot resolve this.

### Steps To Reproduce:
Create repeater with text fields
`{repeater name="services" tab="Services"}`
   ` {variable name="title" type="text" span="storm" cssClass="col-md-12" label="Title"}{/variable}`
   ` {variable name="excerpt" type="text" span="storm" cssClass="col-md-12" label="Excerpt"}{/variable}`
    `{variable name="content1" type="richeditor" span="storm" cssClass="col-md-6" label="Content"}{/variable}`
    `{variable name="content2" type="richeditor" span="storm" cssClass="col-md-6" label="Content"}{/variable}`
    `{variable name="featured" type="text" span="storm" cssClass="col-md-12" label="Featured field"}{/variable}`
  `{/repeater}`

type some polish words which contains "ż" char like `żaglówka, życzenia, także` and try to save.

**Comment by bennothommo** [comment]
@hnitek That appears to be a fault in your Nginx config somewhere. You will need to investigate your server logs and provide us the error being thrown at that point.

**Comment by LukeTowers** [comment]
If you're using cpanel or Apache in general try looking at your mod security rules, could be something in there screwing it up.

**Comment by hnitek** [comment]
Problem solved. 
It was an issue with WAF on nginx.
