### ISSUE TITLE
example.com/backend/rainlab/pages redirect to error page(500)

### ISSUE THREAD

**Issue by uvolovik** [rainlab/pages-plugin#466]
- OctoberCMS Build: 469
- RainLab Pages Plugin Version: 1.3.6
- PHP Version: 7.1.33

Hi! When I try to open "pages", I get a 500 error page, but on my local computer I can open that page and use all the plugin's features.

**Comment by LukeTowers** [comment]
What do your error logs say?

**Comment by uvolovik** [comment]
It's funny, because logs are clean

**Comment by LukeTowers** [comment]
Check your server logs too, not just the October ones.
