### ISSUE TITLE
Question about backend performance with 1000+ static pages. 

### ISSUE THREAD

**Issue by bob-tm** [rainlab/pages-plugin#467]
I'm using static pages plugin with 1100+ pages and count of them grows.  

It's take a lot of time (5-6 seconds) to access /admin/rainlab/pages or search some page by keyword. Server performance is not bottleneck in this case. 

It's possible to speed up? Cache some pages meta? Use DB index?

I may try do it myself, but how do it right? 
It's even possible to extend pages-plugin with my custom-cache-plugin without patching pages-plugin?

**Comment by LukeTowers** [comment]
My first question would be why so many? It starts to sound like you'd be better off with a different way of managing all that content given the relatively limited ways of searching and filtering through static pages.

**Comment by bob-tm** [comment]
Pages-plugin + translation + october + content in static files - is ideal for our tasks! No problems, except page tree speed. No way to change :) 

I want to cache each page metadata, and listen 'pages.object.save' event to clear cache for individual page. Seems like it can be easily implemented and needs minimum code patching. Or I can copy paste your controller to new one, and implement my own with new cached index. In this case it can use future Pages-plugin updates with minimum problems. 

LukeTowers, can my idea work? Your known all details, maybe you can suggest better way to adopt Pages-plugin to large amount of pages?

**Comment by LukeTowers** [comment]
@bob-tm I would start by using the RainLab.DebugBar plugin (only available through composer with October v1.1 right now) to profile the performance to see where the major bottlenecks are. Once you figure that out, it should be relatively easy to fix the issue, and if you post your results here we might even be able to fix it in the plugin itself. One major problem you're going to run into with that many pages though is just plain browser performance to render and manage that many elements at once, a minimum of one element per page just to select them.

**Comment by bob-tm** [comment]
I change my previous comment. 
List and search much faster now!

**Comment by LukeTowers** [comment]
@bob-tm give #468 a try and let me know how that works for you.

**Comment by bob-tm** [comment]
There are syntax error near  `if (isset($pagesArray[$fileName]))` closed ) is missing. 
Performance is ok!  0.23 sec for getPageTree function.

**Comment by bob-tm** [comment]
Full Page tree:
request 1.4
widget.render 0.875639733  
widget.getData 0.251523967 
getPageTree 0.244119911

tnx! Awesome feedback!
