### ISSUE TITLE
Why would I want to use static page plugin?

### ISSUE THREAD

**Issue by NgKhanh** [rainlab/pages-plugin#469]
Hello, I'm new in OctoberCMS. I'm confusing to use this pages-plugin. It creates a page and content, that already exist in CMS. I can't use {% component 'blogPosts' %} in staticPage. Why we need this plugin, please help!

**Comment by LukeTowers** [comment]
@NgKhanh this plugin is very useful for clients without the technical skills required for the regular CMS section in October. And you can use components, they just have to be registered as Page Snippets first and then you can insert them as snippets instead.
