### ISSUE TITLE
Unable to create menus

### ISSUE THREAD

**Issue by digitreadmedia** [rainlab/pages-plugin#476]
- OctoberCMS Build: 2.0 (Clean install)
- RainLab Pages Plugin Version: 1.3.7
- PHP Version: 7.4

### Description:
Unable to create menus.  Results in the following error:
Object of class October\Rain\Router\UrlGenerator could not be converted to string" on line 6 of plugins/rainlab/pages/formwidgets/menuitems/partials/_menuitems.htm

### Steps To Reproduce:
1. Go to Pages
2. Go to Menus
3. Click on Add
4. Object of class October\Rain\Router\UrlGenerator could not be converted to string" on line 6 of plugins/rainlab/pages/formwidgets/menuitems/partials/_menuitems.htm

**Comment by massimomegistus** [comment]
Same issue here

**Comment by daftspunk** [comment]
Fixed in `rainlab/pages-plugin:1.4.0`. Thanks for the report!
