### ISSUE TITLE
Bug: Clicking on the button tabs in the header does nothing. 

### ISSUE THREAD

**Issue by artistro08** [rainlab/pages-plugin#479]
- OctoberCMS Build: 2.0.14 
- RainLab Pages Plugin Version: 1.4.3
- PHP Version: 7.4

### Description:
See quick screenshare: 

https://user-images.githubusercontent.com/6427230/118370646-4135b180-b56e-11eb-9312-1dbc1b1e8d93.mp4

basically, I cannot click those tabs there on the page. But I can open the pages. 

### Steps To Reproduce:
Install Fresh OctoberCMS 
Port old OctoberCMS to new following this guide: https://octobercms.com/support/article/rn-13
Install plugin updates via composer
bug persists

**Comment by daftspunk** [comment]
Thanks @artistro08! We'll take a look soon

From the video, it looks like you have touch mode enabled. As a workaround, you can delete the cookie called `oc-user-touch` to restore the desktop menu

**Comment by artistro08** [comment]
Thanks for the quick fix! Much appreciated. If it helps, I run off a touch screen laptop.

**Comment by alekseybobkov** [comment]
Hello @artistro08, the Pages plugin navigation is not compatible with touch screen devices. There is nothing we can do about it at the moment. Removing the cookie and using the mouse (or trackpad) should help.

**Comment by alekseybobkov** [comment]
This will be fixed in the next core update.
