### ISSUE TITLE
Open menu item in new tab

### ISSUE THREAD

**Issue by jBOKA** [rainlab/pages-plugin#48]
Is there a reason there is no possibility to add menu items (e.g. of type URL) with the option to open in a new tab? For example an external link to another website.

**Comment by hybridvision** [comment]
There was a pull request for this feature and you can see the official answer about it: https://github.com/rainlab/pages-plugin/pull/29 - I think the suggested way in that discussion should work now. There's also more info in this post: https://octobercms.com/blog/post/getting-started-static-pages (see the part about adding the menus and customising the output - you could add a check in there to see if it is an external URL).

Another alternative is to use something like jQuery to detect external links and dynamically add a target attribute. It might not be suitable for all cases but it can be an easy way to apply that rule globally.

**Comment by jBOKA** [comment]
That should help. Thanks for the answer!

**Comment by hybridvision** [comment]
No problems, good luck :)
