### ISSUE TITLE
Mustache Error

### ISSUE THREAD

**Issue by ngilneia** [rainlab/pages-plugin#483]
When I use double mustache in the page like
style="background-image: url('{{ 'assets/img/bg/common-bg.svg' | theme }}');"
or img src="url('{{ 'assets/img/bg/common-bg.svg'  }}')"

I get an error like 
GET http://localhost/base/url/path/%7B%7B.%7D%7D 404 (Not Found)

Is this a bug or i made some mistakes...

**Comment by daftspunk** [comment]
This is likely caused because Mustache variables (Twig) is not directly supported by the Static Pages implementation. You can use snippets to make dynamic content user friendly.

Hope this helps
