### ISSUE TITLE
The partial '_mediafinder.htm' is not found.

### ISSUE THREAD

**Issue by alex-mokkas** [rainlab/pages-plugin#484]
- OctoberCMS Build: 2.0.28
- RainLab Pages Plugin Version: 1.4.5
- PHP Version: 7.3.29

"The partial '_mediafinder.htm' is not found." on line 93 of /var/www/dev.sofia.gr/modules/system/traits/ViewMaker.php

### Steps To Reproduce:
1. Install Pages plugin
2. Create a layout with custom page fields. One of the fields must be the type of mediafinder.
3. Make a static page with the above layout.

**Comment by daftspunk** [comment]
This error has been seen before. Please update to the latest version of RainLab.Translate to fix it. If it is something else, please @ my username to get my attention again.

Thanks!

**Comment by alex-mokkas** [comment]
@daftspunk I've updated the Translate plugin and it seems to work as expected. The problem was that I was running the october:update command but some plugins couldn't be updated. I had to run plugin:install for each one of them.
