### ISSUE TITLE
Page content don't render in backend editor

### ISSUE THREAD

**Issue by Mattia-Marchiorato** [rainlab/pages-plugin#489]
- OctoberCMS Build: 471
- RainLab Pages Plugin Version:1.3.6
- PHP Version: 7.4

### Description:
On some device when they access to a page in backend in the editor there is no content.
If we inspect the html code we see the html content.

### Steps To Reproduce:
Edit a page or create a new page

**Comment by Mattia-Marchiorato** [comment]
The issue is caused by an height: auto !important; on .field-richeditor.stretch .fr-box:not(.fr-fullscreen) .fr-wrapper that is write in richeditor.css

**Comment by daftspunk** [comment]
Hey @Mattia-Marchiorato 

This plugin is at current version v1.4.0, please test using this version.

Thanks!

**Comment by Mattia-Marchiorato** [comment]
Hello @daftspunk 
same problem with the 1.4.6, that happen only in some pc/mac with chrome/safari, at this moment firefox is working.
I tested on my iPhone with chrome and i have the same issue.

Thanks

MM

**Comment by daftspunk** [comment]
I'm sorry I could not replicate this issue using October CMS v2.1.7 across common Mac and PC browsers. The editor appears to render fine in all cases.
