### ISSUE TITLE
Placeholder tabs missing in build 270 + v1.1.0

### ISSUE THREAD

**Issue by hybridvision** [rainlab/pages-plugin#49]
This is a reoccurrence of issue #31 - using build 270 and the latest version of the plugin (v1.1.0), the placeholder tabs don't show in the editor anymore.

Please can you take a look?

**Comment by vojtasvoboda** [comment]
@hybridvision Can you try my hotfix please?

**Comment by hybridvision** [comment]
@vojtasvoboda Thanks, works for me! :+1:
