### ISSUE TITLE
Call to a member function getViewBag() on null

### ISSUE THREAD

**Issue by Anas-shamia** [rainlab/pages-plugin#490]
- OctoberCMS Build: 2.1.6 
- RainLab Pages Plugin Version: 1.4.6
- PHP Version: 7.4

### Description:
I installed RainLab.Translate Plugin and I am trying to translate static page but I always get this error call to a member function getViewBag() on null

### Steps To Reproduce:

- Create a Static page with default language and save it everything will work fine
- Now Add translation for the static page and save it 
- Now I get the error

![Screen Shot 2021-08-30 at 4 07 43 PM](https://user-images.githubusercontent.com/17951168/131343851-251169d9-9457-4d91-97d2-bf318b435ecb.png)

**Comment by daftspunk** [comment]
Hi @Anas-shamia 

I could not replicate this error using the instructions. Try clearing your cache to see if it helps.

**Comment by daftspunk** [comment]
I've traced this logic and logically it should never happen. I also couldn't replicate this. Best I can do is squash the error. See 1c68baec9a8022909f5d2d21d86915519eb79751

**Comment by shoguniphicus** [comment]
> I've traced this logic and logically it should never happen. I also couldn't replicate this. Best I can do is squash the error. See [1c68bae](https://github.com/rainlab/pages-plugin/commit/1c68baec9a8022909f5d2d21d86915519eb79751)

Super. This fixed the problem. I had cleared the cache too. But for some reason, the array came up with null.
