### ISSUE TITLE
How to add static pages variable (custom page field) to layout from plugin?

### ISSUE THREAD

**Issue by anik1ng** [rainlab/pages-plugin#493]
In layout: {variable name="tagline" label="Tagline" tab="Header" type="text"}{/variable}

But how i can add it from my Plugin Component? Or Plugin boot method?

**Comment by artistro08** [comment]
you call it in twig 

since you have `{variable name="tagline" label="Tagline" tab="Header" type="text"}{/variable}`

you can call it by name

`{{ tagline }}`

**Comment by daftspunk** [comment]
You can extend forms programmatically using the `backend.form.extendFields` event.

Here is a screencast that shows how to do it: https://octobercms.com/support/article/ob-10

Here is a reference to the documentation that shows how to do it:

---

##### Custom menu item form fields

Just like CMS objects have the view bag component to store arbitrary values, you may use the `viewBag` property of the `MenuItem` class to store custom data values and add corresponding form fields.

    Event::listen('backend.form.extendFields', function ($widget) {
        if (
            !$widget->getController() instanceof \RainLab\Pages\Controllers\Index ||
            !$widget->model instanceof \RainLab\Pages\Classes\MenuItem
        ) {
            return;
        }

        $widget->addTabFields([
            'viewBag[featured]' => [
                'tab' => 'Display',
                'label' => 'Featured',
                'comment' => 'Mark this menu item as featured',
                'type' => 'checkbox'
            ]
        ]);
    });

This value can then be accessed in Twig using the `{{ item.viewBag }}` property on the menu item. For example:

    {% for item in items %}
        <li class="{{ item.viewBag.featured ? 'featured' }}">
            <a href="{{ item.url }}">
                {{ item.title }}
            </a>
        </li>
    {% endfor %}

**Comment by anik1ng** [comment]
@daftspunk thx for you answer, Sam!

I try to create plugin for auto adding static pages fields, and make from this fields blocks. Use my plugin you can create blocks with custom partial, and create in block any fields. It's work by stock static pages functionality.

Look examples:

In backend you have new functionality to manage static pages blocks:
<img width="1680" alt="Screenshot 2021-09-14 at 10 14 46" src="https://user-images.githubusercontent.com/505388/133189052-628f96f1-d4ef-40c6-a82d-dc3798a231e3.png">

You can create block, with any type fields:
<img width="1680" alt="Screenshot 2021-09-14 at 10 16 23" src="https://user-images.githubusercontent.com/505388/133189189-25eb41e9-7923-4757-a50c-e234c6be5e65.png">

After create block, my plugin create .yaml file with form setup.

You also edit partial with block-edit page.
<img width="1680" alt="Screenshot 2021-09-14 at 10 17 25" src="https://user-images.githubusercontent.com/505388/133189277-e78feea0-bf55-480e-998a-22fd8a32dadb.png">
If partial not exist, plugin create partial with block name in partials/pluginName/ directory.

Plugin work so easy, you need place my component to layout, and create block with fields. After this on any page that uses this layout you can manage custom blocks from my plugin:

<img width="1266" alt="Screenshot 2021-09-14 at 10 21 18" src="https://user-images.githubusercontent.com/505388/133189627-27d41a26-3c19-49dd-9fe3-4cc756940cbf.png">

<img width="1266" alt="Screenshot 2021-09-14 at 10 22 44" src="https://user-images.githubusercontent.com/505388/133189786-ff1e2c36-3e98-4fcd-9a82-a748749c0b91.png">

So easy to create any custom block, and manage it. It's use functionality of StaticPages. You can reorder block, place 2-3-any blocks on any order, and you frontend will show it! It's like place variables to layout, but more functionality.

**This is the background to my problem.**

For this to work, i use repeater with groups. Need place this code to layout:

```html
{repeater name="sections" groups="~/plugins/anikin/pageconstructor/models/block/constructor.yaml" tab="Page Constructor" prompt="Add section"}
    {variable name="_dummy" type="text"}{/variable}
{/repeater}

{% for section in sections %}
    {% partial 'pageconstructor/' ~ section._group data=section cons='cons' index=loop.index %}
{% endfor %}
```

I want to avoid manually adding code to layout. And i can place `{% for .. ` into partial of my plugin. But i can't place `{repeater ...` code into my plugins partial. I cannot find any elegant solution to this problem.

I studied the work of Static Pages and did not find any events before the parser finds all the variables and the repeater and, based on this, adds fields to the backing form.

Please give me advice on how to solve my problem.

**Comment by daftspunk** [comment]
> Please give me advice on how to solve my problem.

This is indeed a tricky problem, however, it should be solvable. The Pages plugin simply uses the event system to inject fields based on the content.

```
            $widget->bindEvent('form.extendFieldsBefore', function() use ($widget, $object) {
                $this->checkContentField($widget, $object);
                $this->addPagePlaceholders($widget, $object);
                $this->addPageSyntaxFields($widget, $object);
            });
```

It would appear that you need to inject fields based on the CMS Object's component properties. Notice that this event gives you everything you need, including the `$widget` and `$page` object.

I hope this gives you some better direction! Let me know if you have any other questions related to this advice.
