### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by webfalter** [rainlab/pages-plugin#500]
OctoberCMS Build: 3.0.12
RainLab Pages Plugin Version: 1.14.12
PHP version: 8.1.4

Blank Page in Menu Frontend in my project after update

Examples are in the topic
https://octobercms.com/theme/rainlab-bonjour
https://octobercms.com/theme/rainlab-relax

**Comment by daftspunk** [comment]
Hi @webfalter, thanks for the report. This is fixed in:

- OctoberCMS Build: 3.0.13
- RainLab Pages Plugin Version: 1.14.13

**Comment by webfalter** [comment]
Thanks
but there are still errors
Example of both topic
![Bildschirmfoto 2022-04-05 um 16 05 25](https://user-images.githubusercontent.com/481551/161772516-76c704ea-5e2d-4cf8-a3f2-ff79db82670b.png)
![Bildschirmfoto 2022-04-05 um 16 05 03](https://user-images.githubusercontent.com/481551/161772523-7c043264-c3bb-4503-b1a2-0d4fe98f70e3.png)
s

**Comment by daftspunk** [comment]
This is an issue with the theme itself and Twig v3.0

Fixes are here:
https://github.com/rainlab/bonjour-theme/commit/8ee8f8bf869f1351163aa9037e6ce45230c248b1
https://github.com/rainlab/relax-theme/commit/9a4d669f255c95a356961f3f6d02a2b8aaff972c

Here is the relevant document:
https://twig.symfony.com/doc/2.x/deprecated.html

And deprecation:
> Adding an if condition on a for tag is deprecated in Twig 2.10. Use a filter filter or an "if" condition inside the "for" body instead (if your condition depends on a variable updated inside the loop).

**Comment by daftspunk** [comment]
New releases for these themes have been published. This is fixed in:

- RainLab.Relax - v1.0.3
- RainLab.Bonjour - v1.0.2

**Comment by webfalter** [comment]
Thanks for the quick help
