### ISSUE TITLE
October 3.x (2.x?) mediafinder compatibility issue

### ISSUE THREAD

**Issue by acasar** [rainlab/pages-plugin#502]
- OctoberCMS Build: v3.0.35
- RainLab Pages Plugin Version: v1.5.0
- PHP Version: 8.1

### Description:
If we have a mediafinder widget on a page and we try to edit a menu item in another tab, there is a javascript error.

![image](https://user-images.githubusercontent.com/6329543/168881405-d717e963-f60b-42ae-a71c-29d5f3746b9d.png)

![image](https://user-images.githubusercontent.com/6329543/168881694-9f86200c-0afa-4b73-85d6-08e12c23ecfb.png)

### Steps To Reproduce:
1. Add a mediafinder widget to the static page layout, e.g.:
``{variable name="background" type="mediafinder" label="Background" tab="Layout" mode="image"}{/variable}``
2. Go to **/backend/rainlab/pages** and click **+ Add** to open a new page. Make sure a layout with mediafinder widget is selected
3. Click on **Menus** -> **+ Add** -> **+ Add item** to open a popup for adding a new menu item while the page is still open in another tab
4. A javascript error described above appears

**Comment by samgeorges** [comment]
Thanks @acasar. Looks like some leaky code. This will be fixed in the next patch release.
