### ISSUE TITLE
UX issues in October v3

### ISSUE THREAD

**Issue by acasar** [rainlab/pages-plugin#504]
- OctoberCMS Build: v3.0.44
- RainLab Pages Plugin Version: v1.5.0
- PHP Version: 8.1

### Description:
Checkboxes do not appear on Pages and Menus in side panel:

![image](https://user-images.githubusercontent.com/6329543/172925947-467bfc53-56e6-4047-ba34-2304938e6a88.png)

But it seems they are just transparent, since clicking on this general area, brings up the delete button:

![image](https://user-images.githubusercontent.com/6329543/172926019-e442a65b-b02a-4bf9-bcae-732848c3b41f.png)

Checkboxes work normally on Contents side panel (notice, the delete button is red here compared to other two panels - it would be nice to have this unified across all 3 content types):

![image](https://user-images.githubusercontent.com/6329543/172926112-ca0b1ff2-62b1-49ba-93aa-e1a11376f47d.png)

### Steps To Reproduce:
Click on "Pages" main menu in the CMS and follow the screenshots above.

**Comment by daftspunk** [comment]
Thanks!
