### ISSUE TITLE
Can't update to 1.5.1

### ISSUE THREAD

**Issue by acasar** [rainlab/pages-plugin#505]
The latest version in https://gateway.octobercms.com/ is still 1.5.0, which is not compatible with October v3.0.45.

If I try forcing 1.5.1 in composer.json I get:

> Root composer.json requires rainlab/pages-plugin 1.5.1, it is satisfiable by rainlab/pages-plugin[v1.5.1] from composer repo (https://repo.packagist.org) but rainlab/pages-plugin[v1.2.9, ..., v1.5.0] from composer repo (https://gateway.octobercms.com) has higher repository priority. The packages from the higher priority repository do not match your constraint and are therefore not installable. That repository is canonical so the lower priority repo's packages are not installable. See https://getcomposer.org/repoprio for details and assistance.

**Comment by daftspunk** [comment]
Confirmed the gateway missed the tag. Try again, should work.

**Comment by acasar** [comment]
It works now, thanks 👍
