### ISSUE TITLE
Issues with Menu reference finder in the latest October Build (could be AJAX issue)

### ISSUE THREAD

**Issue by acasar** [rainlab/pages-plugin#506]
- OctoberCMS Build: 3.0.59
- RainLab Pages Plugin Version: 1.5.1
- PHP Version: 8.1

### Description:

I noticed that a problem with a menu reference finder appeared with the latest October changes.

### Steps To Reproduce:

If we have a Menu with 2 menu items and I click on the first one, the reference finder works as expected:

![image](https://user-images.githubusercontent.com/6329543/176128784-411b68c1-1ef0-4a21-a3f7-e5685259071e.png)

However if I close the popup and open it again, it always display an empty dropdown and I can't type into it any more:

![image](https://user-images.githubusercontent.com/6329543/176129155-48026bd5-f0ff-490e-a432-fcb1224fdaf9.png)

This may be related to recent changes in October core or Ajax framework.

**Comment by samgeorges** [comment]
Thanks for finding this.
