### ISSUE TITLE
Unable to edit pages, getting an error Unknown "inline" filter in "getTwigNodeTree"

### ISSUE THREAD

**Issue by digitreadmedia** [rainlab/pages-plugin#512]
- OctoberCMS Build: 3.0.72
- RainLab Pages Plugin Version: 1.55
- PHP Version: 8.0

### Description:
Trying to edit pages in the backend results in an error: "Unknown "inline" filter in "getTwigNodeTree" at line 40." on line 785 of ...\vendor\twig\twig\src\ExpressionParser.php

### Steps To Reproduce:
Click on pages in the top menu, open a page to edit, popup error occurs.

![image](https://user-images.githubusercontent.com/48868778/190888820-9ee749cf-655e-4312-9cf2-fab8081433f1.png)

**Comment by daftspunk** [comment]
Hello @digitreadmedia, looks like your Twig is using an unknown filter called `|inline`. Search your layout code and partials for this and remove it. Hopefully, that should resolve the error.

**Comment by digitreadmedia** [comment]
Thank you, found the issue, was a plugin that did not load.  Issue is fixed now.
