### ISSUE TITLE
Getting duplicate 'Add new section' list

### ISSUE THREAD

**Issue by timmarner** [rainlab/pages-plugin#516]
Hi,

Im using the advance 'Add section' feature in the page layout so i can add section to my page like a kind of page builder. however the dropdown list of section seems to be duplicating but i only have one of each in my yaml file.

Its really strange.

**Comment by daftspunk** [comment]
Hi @timmarner 

It's difficult to know why this happens based on the information provided. If you find some more specific reason why it happens, please let us know.

Best regards.
