### ISSUE TITLE
Duplicate pages

### ISSUE THREAD

**Issue by RitsmG** [rainlab/pages-plugin#517]
Hi,

Is there a way to duplicate pages from within pages plugin in the backend

Thanks!

**Comment by daftspunk** [comment]
Unfortunately, no this plugin does not have a duplicate feature, however you can duplicate the files in the filesystem manually.

**Comment by jan-vince** [comment]
I needed this too, so you can use [Small Extensions](https://octobercms.com/plugin/janvince-smallextensions) plugin to duplicate pages right in backend (thanks to @Rike-cz)
