### ISSUE TITLE
Pages Menu option Accessibility

### ISSUE THREAD

**Issue by RitsmG** [rainlab/pages-plugin#518]
The "Menu's"  menu option in the pages plugin is hidden away in the pages plugin. 
Would it be possible to get the Pages submenus either in the main item as a dropdown or is it possible to get the "Menu's" item as an item in the main menu by itself?

Thanks!

**Comment by daftspunk** [comment]
Hi @RitsmG 

Since the release of v3.2, a page finder form widget can be used to design menus. It works especially well with Tailor, there is a "Sitemap" example that ships with the demo theme.

I hope this helps.
