### ISSUE TITLE
Inspector data-property-xxx attributes do not support complex values

### ISSUE THREAD

**Issue by ssi-com-pl** [rainlab/pages-plugin#519]
Hi! I need to use objectList field in component, but when I add it to static page there is an error:
Inspector data-property-xxx attributes do not support complex values
![image](https://user-images.githubusercontent.com/57666038/232732953-414bbf64-67b5-484c-a4dc-7a9b2fa07801.png)
![image](https://user-images.githubusercontent.com/57666038/232733194-b4213b37-bec8-45c2-84a9-9200ca49be45.png)

**Comment by ssi-com-pl** [comment]
Thank you

**Comment by daftspunk** [comment]
Confirmed this is fixed in October CMS v3.4
