### ISSUE TITLE
No longer able to add snippets to the editor

### ISSUE THREAD

**Issue by hybridvision** [rainlab/pages-plugin#52]
With the latest version of the Pages plugin (v1.1.3) and build 277 of OctoberCMS, it's no longer possible to insert snippets from the menu in the backend. Attempting to do so shows an alert saying "Snippets can only be added to page Content or HTML placeholders".

![image](https://cloud.githubusercontent.com/assets/11492432/8650881/1994409a-2976-11e5-8de7-df83ec71ade6.png)

Existing snippets still work and it is possible to fudge a new snippet by inserting HTML in the code so I think it's just a validation bug upon insertion.

I haven't had time to look into this further but I assume it will be an easy fix. I've confirmed this bug exists in a couple of different installs.

Thanks!

**Comment by hybridvision** [comment]
I found the problem and fixed it - pull request submitted. Still figuring out how Github works!

**Comment by felixinx** [comment]
@hybridvision 

> Still figuring out how Github works!

What? You're perfect in GitHub :+1: !

**Comment by hybridvision** [comment]
Haha merci @felixinx :)

I did manage to send my first pull request to myself, so not sure I'm quite perfect yet!

**Comment by Insanityandme** [comment]
Got the same error, read somewhere that it's because I'm not using the standard editor, anyone has a solution?

**Comment by FelixINX** [comment]
@Insanityandme You cannot use snippets without the default October editor.

**Comment by Insanityandme** [comment]
I see, thanks!
