### ISSUE TITLE
Error str_starts_with() with static menu

### ISSUE THREAD

**Issue by ogalbnafets** [rainlab/pages-plugin#521]
- OctoberCMS Build: 3.3.6
- RainLab Pages Plugin Version: 1.5.9
- PHP Version: >8

### Description:
I configured my menu in Static Pages and when accessing it again I get this error:
"str_starts_with(): Argument #1 ($haystack) must be of type string, array given" on line 58 of 
/var/www/xxxxx/ocms/live/vendor/october/rain/src/Translation/Translator.php

I am using OFFLINE.Mall and Tailor Entries with Static Menu

### Steps To Reproduce:

- Creating new menu
- Adding Entries from OFFLINE.Mall and Tailor (Stream/Structure)
- Saving
- Trying to edit again

I hope this is enough information - if you need further information contact me :)

Thanks :)

**Comment by daftspunk** [comment]
Hi @ogalbnafets 

We may need to see the complete stack trace in **storage/logs/system.log**. Feel free to email this to hello@octobercms.com to get personalized support.

Best regards
