### ISSUE TITLE
Problem with Taglist 

### ISSUE THREAD

**Issue by Radzio1615** [rainlab/pages-plugin#523]
- OctoberCMS Build: 3.4.9
- RainLab Pages Plugin Version: 1.5.10
- PHP Version: 8.0.26

### Description:
I have a problem with the Taglist field. Only one tag is saved in the yaml file. The field after refreshing the page is empty

### Steps To Reproduce:
1. Define new field:
```
Event::listen('backend.form.extendFields', function ($widget) {
    if (
        !$widget->getController() instanceof \RainLab\Pages\Controllers\Index ||
        !$widget->model instanceof \RainLab\Pages\Classes\MenuItem
    ) {
        return;
    }
  $widget->addTabFields([
    'viewBag[tags]' => [
        'tab' => 'Tags',
        'label' => 'Tags',
        'type' => 'taglist',
        'mode' => 'string',
        'separator' => 'space',
        'customTags' => true,
        'span' => 'auto',
        'useKey' => true,
        'options' =>  [
            'tag' => 'Tag 1',
            'tag-2' => 'Tag 2',
            'tag3' => 'Tag 3',
        ],
        'trigger' => [
            'action' => 'show',
            'field' => 'type',
            'condition' => 'value[url][cms-page][static-page]'
        ]
    ],
  ]);
});
```
2. Add an item to the menu and select 2 tags:
![image](https://github.com/rainlab/pages-plugin/assets/40895581/d000a686-c253-4a13-b8e1-e72af8486a43)

3. Save menu item > Save menu > Refresh browser page > Select menu > Edit menu item and you'll see no tags selected:
![image](https://github.com/rainlab/pages-plugin/assets/40895581/99359a70-b9fa-4723-8d0a-ad3179112155)

4. Open menu .yaml file and see that only one tag is saved:
![image](https://github.com/rainlab/pages-plugin/assets/40895581/6ffb5e10-c516-4450-85ff-cde5996c128f)

Saved value should be eg.: `tags: 'tag tag3'`

**Comment by daftspunk** [comment]
Unfortunately, `taglist` is not supported by the Pages plugin. Please try using Tailor found in October CMS v3.

Thanks!
