### ISSUE TITLE
Access the static page via Sceduled Cron job

### ISSUE THREAD

**Issue by techmighty** [rainlab/pages-plugin#524]
Is it possible to  access  the static page from scheduled cron job  .
Fetch the page details by giving page title or url and write the content on that page  . I have tried but the runnnig the cron job could not access the page

**Comment by daftspunk** [comment]
Hi @techmighty 

Sure, you can do it with this code. For a filename "test.htm":

```php
RainLab\Pages\Classes\Page::find('test');
```
