### ISSUE TITLE
URL is empty on the frontend using the OFFLINE.BOXES type

### ISSUE THREAD

**Issue by LeonKercmar** [rainlab/pages-plugin#525]
- OctoberCMS Build: 3.4.16
- RainLab Pages Plugin Version: 1.5.12
- PHP Version: 8.2
- Laravel: 10

### Description:
Url is empty on the frontend when i try using the OFFLINE.BOXES type.

**Comment by webfalter** [comment]
Why don't you use 2.0.3?

**Comment by LeonKercmar** [comment]
I've tried using the latest version but it didn't fix the problem.

**Comment by daftspunk** [comment]
> Url is empty on the frontend when i try using the OFFLINE.BOXES type.

Can you elaborate on this? What is the expected behavior? What is the actual behavior?

**Comment by LeonKercmar** [comment]
So for an example in the backend under Pages > Menus I have a menu called Big Menu which has a menu item (picture bellow)
![image](https://github.com/rainlab/pages-plugin/assets/105213431/8540ed73-5cf9-4502-a1e8-527c8a052c1c)

In the editor under the header partial I get the items like this (picture bellow)
![image](https://github.com/rainlab/pages-plugin/assets/105213431/604faaba-52d3-410c-a431-fd391e7fdcac)

In front end I get the item title but the url parameter is empty (picture bellow)
![image](https://github.com/rainlab/pages-plugin/assets/105213431/3293743e-adb9-4c05-bcda-06c0a86b53ea)

**Comment by daftspunk** [comment]
This looks related to the Offline.Boxes plugin, instead of the pages plugin. The menu resolver is returning an empty link.

Instructions on this process is found here: https://docs.octobercms.com/3.x/element/form/widget-pagefinder.html#resolving-page-links
