### ISSUE TITLE
Delete buttons not working in October 3.5

### ISSUE THREAD

**Issue by acasar** [rainlab/pages-plugin#526]
In october 3.5 a string ``input-trigger`` is appended to the ``data-control`` attribute of a delete button:

![image](https://github.com/rainlab/pages-plugin/assets/6329543/673d7aa2-b744-4581-9874-4bc770a5dae6)

As a consequence the ``[data-control=delete-object]`` selector fails and the following javascript is not attached correctly:
https://github.com/rainlab/pages-plugin/blob/master/assets/js/pages-page.js#L64

**Comment by daftspunk** [comment]
Thanks @acasar !
