### ISSUE TITLE
Snippets not showing up

### ISSUE THREAD

**Issue by LeonKercmar** [rainlab/pages-plugin#527]
- OctoberCMS Build: 3.4.12
- RainLab Pages Plugin Version: 2.0.4
- PHP Version: 8.1

### Description:
I've inserted a Snippet on my Page and it shows up in my primary language which is fine but as soon as i switch the language to any other language like English it doesn't show up and in the front end it gives me an error saying "Snippet with the requested code News was not found in the theme".
![image](https://github.com/rainlab/pages-plugin/assets/105213431/390d30a0-8673-4ca5-a75e-a4968a0f7aab)

### Steps To Reproduce:
1. Create a page
2. Insert Snippet
3. Go to the page
4. Snippet shows up in main langauge
5. Switch Language
6. Snippet doesn't show up

**Comment by daftspunk** [comment]
Hi @LeonKercmar 

Check to confirm that both sites are using the same theme, also, make sure that the "Edit theme" has not been set to something else by the Editor; you can confirm by checking what theme is used when you open Editor.

I hope this helps you.
