### ISSUE TITLE
404 pages build with Rainlab.Pages no longer shown

### ISSUE THREAD

**Issue by renickbuettner** [rainlab/pages-plugin#530]
- OctoberCMS Build: 3.6.8 
- RainLab Pages Plugin Version: 2.0.4
- PHP Version: 8.3

### Description:
I just noticed that the 404 page I built with Static Pages is no longer shown correctly. Usually pages with the route 404 will be shown by OctoberCMS as 404 Not found page. 

May we can re-introduce the old behavior again, and use the page with the url "/404" again for OctoberCMS default error page.

### Steps To Reproduce:

- Create a page with the url /404 within Static Pages
- This page should be shown when an user is accessing a page, and OctoberCMS drops the 404 Not found error

**Comment by daftspunk** [comment]
Hey @renickbuettner 

I can't seem to reproduce this...

> This page should be shown when an user is accessing a page, and OctoberCMS drops the 404 Not found error

Confirmed the 404 static page is displayed as expected.

![image](https://github.com/rainlab/pages-plugin/assets/1392869/7d42f65f-3d57-4f89-a902-8480f1efc110)
