### ISSUE TITLE
Text editor disappeared

### ISSUE THREAD

**Issue by s-verhappen-qteco** [rainlab/pages-plugin#533]
- OctoberCMS Build: 3.6.27
- RainLab Pages Plugin Version: 2.0.5
- PHP Version: 8.2.16

### Description:
Text editor in pages plugin disappeared.

### Steps To Reproduce:
Yesterday I did update my CMS to 3.6.27, and made a change inside the raw page file. after this the texteditor no longer shows up in pages

<img width="1550" alt="Screenshot 2024-07-31 at 12 22 06" src="https://github.com/user-attachments/assets/05e4f632-396f-48ca-9c4e-f82560aaebad">

**Comment by daftspunk** [comment]
Hey @s-verhappen-qteco 

A couple of things to check:

1. Do you see any console errors in the developer tools of the browser?
2. Check that the layout has the "Use page content field" checkbox marked

![image](https://github.com/user-attachments/assets/9e98ca84-72ce-4ebe-85c8-fd1a6feddf0e)

I hope this helps.
