### ISSUE TITLE
Store open tabs in cookie should be optional

### ISSUE THREAD

**Issue by jan-vince** [rainlab/pages-plugin#535]
- OctoberCMS Build:  3.6.28
- RainLab Pages Plugin Version: 2.1.1
- PHP Version: 8.2.18

### Description:
Function of storing open tabs in a cookie (https://github.com/rainlab/pages-plugin/commit/a9b39255d98bba7e2fbdabb6fdd1a1c2fd224763) should be optional (through Settings?) or there should be a function to close all tabs at once.

Waiting for backend Pages section to load with many open tabs can take a lot of time. 

And closing many open tabs one by one is sometimes a pain.

**Comment by daftspunk** [comment]
Hey @jan-vince 

How about `remember_tabs_max` set to a number of recent tabs to remember? Setting to `0` will remember none. Perhaps you want to set it to `5` or some more manageable amount.

**Comment by jan-vince** [comment]
Sounds good!
