### ISSUE TITLE
"Hide In Navigation" on Page doesn't hide it from Menu

### ISSUE THREAD

**Issue by mickburkesnr** [rainlab/pages-plugin#55]
When creating static pages, there are some I need to hide just because there's no content on the page. On the page there is a checkbox labeled "Hide in navigation - Check this box to hide this page from automatically generated menus and breadcrumbs."

Thing is, I've checked this on several pages and they still display in the menu which I've called using the default method as outlined in the documentation.

I've checked the website when not logged in and the pages are still displayed in the menu.
##

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
