### ISSUE TITLE
Menu Item Deleting not working

### ISSUE THREAD

**Issue by astucieuxzephyr** [rainlab/pages-plugin#56]
Hi, on my October installation, 
When I go in the Pages section, then in the left Menus section,
In a menu, the Trash button (for deleting a menu item) doesn't work and I don't understand why.
I got the same problem on my website on production. Any idea ?
Thank you very much.

**Comment by daftspunk** [comment]
Seems to be working for me. Do you get any error messages?

**Comment by JurekRaben** [comment]
Had some strange behavior: deleted a page, but a partial was deleted instead. Maybe my browser backend session was outdated.

**Comment by astucieuxzephyr** [comment]
Hi, I finally found the solution to this simple problem : Better Pop Up Blocker, a plugin I installed on Chrome, was blocking the deletion. Thank you Daftspunk for your quick feedback. :+1:
