### ISSUE TITLE
Request: Extended partial properties

### ISSUE THREAD

**Issue by JurekRaben** [rainlab/pages-plugin#59]
Hi, the properties in the partials are quite useful.

But I am heavily missing some more features for the backend:
- A textarea/string type instead only a textfield/string.
- A pagelink type instead a plain string url. So that the customer simply can select a target page in a select box instead entering a raw url...

How could I add these by myself? Thx.
##

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
