### ISSUE TITLE
[Bug?]  CMS page dropdown

### ISSUE THREAD

**Issue by DanielHitchen** [rainlab/pages-plugin#6]
When selecting `Blog Category` or `All blog categories` from the TYPE dropdown, the `CMS Page` dropdown is empty - is this correct?

![untitled](https://cloud.githubusercontent.com/assets/7501909/4505616/f687d470-4af7-11e4-9665-05e1162500d7.jpg)

![untitled](https://cloud.githubusercontent.com/assets/7501909/4505630/37c0e83c-4af8-11e4-88d3-4ea1cc4e6270.jpg)

**Comment by dimti** [comment]
Hi all

I fetched similar situation. Unable to see CMS Pages in menu type Blog Category. October update and plugins on latest version in two weeks ago. I read manuals, getting-started, but not help. CMS Pages not showing in menu item type Blog Category.

![_2016-11-13_18-36-53](https://cloud.githubusercontent.com/assets/582144/20246850/3339687e-a9d9-11e6-8d38-4a01b728abe3.png)
![_2016-11-13_18-19-20](https://cloud.githubusercontent.com/assets/582144/20246851/333b2236-a9d9-11e6-9cb9-f44172a007f7.png)

Where is code and how i can debug this, why is CMS Pages not showing?

**Comment by daftspunk** [comment]
It will only show CMS pages that use the blog category component on there, with a valid slug used. Try installing RainLab.Vanilla theme for another example. It should be working here:

https://github.com/rainlab/vanilla-theme

Duplicate of #122
