### ISSUE TITLE
{% if placeholder(name') %} -> no more editable

### ISSUE THREAD

**Issue by JurekRaben** [rainlab/pages-plugin#60]
If I wrap a placeholder with an if-clause, like:
  {% placeholder link title="Link" type="html" %}{% placeholder link title="Link" type="html" %}{% endif %}

The placeholder will not appear in the static pages editor as editable content.... Why this???  How can I now fill-in something to the placeholder?

**Comment by jonpxpx** [comment]
I've ran into this problem as well after refactoring the number layouts on a site which has screwed up a site that I am due to put live in next couple of days.

**Comment by agentk** [comment]
We can use placeholders inside `{% if %}{% endif %}` if the list of twig nodes is flattened first.

**Comment by daftspunk** [comment]
Should be fixed by 6da73343514b81e66e6fa135c110722457c3c5c3

Thanks
