### ISSUE TITLE
[Bug?] Error when creating new page

### ISSUE THREAD

**Issue by DanielHitchen** [rainlab/pages-plugin#65]
Hi,

Getting this error notification when creating a new page:

![error](https://cloud.githubusercontent.com/assets/7501909/9247240/5fd2a24a-41a9-11e5-820d-004ec3612e9b.jpeg)

**Comment by felixinx** [comment]
Hi, why have you closed this issue? Problem resolved?

**Comment by DanielHitchen** [comment]
@felixinx yes, this issue was being caused by a "var" Twig filter I'd created in a plugin, being utilised in my theme which had since been re-named to "_var" therefore throwing the error above - didn't want the devs wasting their time looking into it, so just closed the issue

**Comment by felixinx** [comment]
Oh ok, have great time with October!
