### ISSUE TITLE
content field keeps getting filled with paragraph

### ISSUE THREAD

**Issue by dogiedog** [rainlab/pages-plugin#66]
I'm having issues with default content in placeholders, when I filled my placeholder but I want to get the default value back, it won't show. Because there is still a paragraph tag in the "put".

You can reproduce this by:
1) Making a static page which has a placeholder with default content
2) Fill the placeholder and save the page
3) Remove all contents from the placeholder (in the static page plugin)
4) Look at the page and there will be no default value because of the paragraph tag (see example below)

```
{% put placeholder1 %}
<p><br></p>
{% endput %}
```
##

**Comment by hybridvision** [comment]
I think this might be a bit of a bug in the Redactor editor where it doesn't actually remove everything when you clear the contents of the editor. I seem to remember noticing a similar problem once or twice in the past.

Have you tried switching to the HTML view and clearing out the contents from there? It's not a real fix for the problem but if that works then it might confirm that Redactor isn't properly clearing itself always.

I assume you also checked that there weren't any stray line breaks in the editor after you'd cleared the content? You shouldn't be able to move the cursor up or down once it is empty. In your example, it seems like there is one extra line break somewhere...

**Comment by dogiedog** [comment]
@hybridvision I tried all of this.
I tried to switch to HTML view and delete all contents from there (with mouse and with cmd + a -> delete)
Also tried it in the wysiwyg view... still it's giving me the paragraph.

Additional info, I'm using Firefox.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred. Also, October switched to using Froala instead of Redactor, issue should no longer be present.
