### ISSUE TITLE
Add support for syntax fields dropdown, radio

### ISSUE THREAD

**Issue by shrpne** [rainlab/pages-plugin#69]
Is it possible to use dropdown or radio variables in syntax fields?

**Comment by daftspunk** [comment]
No, sorry about that, we may consider it in the future.

**Comment by daftspunk** [comment]
Found a way to do this quickly and cheaply. Borrow syntax from snippet dropdown definition:


> Options - the option list for the drop-down properties. The option list should have the following format: key:Value | key2:Value. The keys represent the internal option value, and values represent the string that users see in the drop-down list. The pipe character separates individual options. Example: us:US | ca:Canada.

```
{variable name="layoutoption" type="dropdown" options="key:Value | key2:Value"}{/variable}
```

**Comment by daftspunk** [comment]
This has been implemented

### Dropdown

Renders a dropdown form field.

    {dropdown name="dropdown" label="Pick one" options="One|Two"}{/dropdown}

### Radio

Renders a radio form field.

    {radio name="radio" label="Thoughts?" options="y:Yes|n:No|m:Maybe"}{/radio}

**Comment by shrpne** [comment]
thank you!

**Comment by iboved** [comment]
Hi, guys!
How to use dynamic options from some method?
This doesn't work:
`{dropdown name="hotel" label="Hotel" options="getHotelOptions"}{/dropdown}`

**Comment by w20k** [comment]
@iboved please use Slack instead of posting questions under abandoned or old issues.

Slack: https://octobercms-slack.herokuapp.com/
