### ISSUE TITLE
Uploading images

### ISSUE THREAD

**Issue by RichardLindhout** [rainlab/pages-plugin#7]
Can't add any images (only shows placeholder image)
I can edit the html but my client doesn't understand :(

Besides that it is a great plugin!!

**Comment by geverges-oleg** [comment]
+1

**Comment by shina** [comment]
+1

**Comment by vojtasvoboda** [comment]
I think this issue is solved. In last version of October you have Media manager which allows you to add any image.

**Comment by LukeTowers** [comment]
As stated by @vojtasvoboda
