### ISSUE TITLE
WYSIWYG editor adding <p> tags and <br> tags

### ISSUE THREAD

**Issue by bjpayne** [rainlab/pages-plugin#73]
The WYSIWYG editor is adding ```<p>``` tags and ```<br>``` tags to the top of a form I am adding.

**Comment by felixinx** [comment]
Thats not a Plugin problem, this is the WYSIWYG that manage this.

**Comment by sunilcse24** [comment]
How to avoid this tags?

**Comment by bjpayne** [comment]
@sunilcse24 I was able to fix this by letting the editor add then go back and add a hidden css class to them. Not ideal, but all I have been able to come up with. Hopefully that helps.

**Comment by djein** [comment]
Hi! I probably have problem related to this.
I have a placeholder with default markup. If a page has some placeholder value which I'd like to remove and return to default I can't do this. I have 
{% put content %}
<p></p>
{% endput %}
and have no options to clean this field entirely. 

Should I open new issue for this? Thanks you in advance

**Comment by FelixINX** [comment]
You should not use Twig language in static pages. Where do you put these? `{% put content %}`

**Comment by djein** [comment]
Hi @FelixINX 
I am not putting this myself, this is what I see in the page file after attempt to remove placeholder content
```
my configuration data
==
{% put content %}
<p>​</p>
{% endput %}
==
my page content
```
I suppose that WYSIWIG replaces an empty string by '<p></p>' and the plugin get this string like placeholder content. As a result I can't return to default.

**Comment by EngBadr** [comment]
Of course this awesome plugin , but the editor generate a dummy <br> and <p> tags , it generated once I wrote any page and make my page so bad , I tried to remove it in the code but It still happen 
any suggestion!

**Comment by LaravelNick** [comment]
Wish there was some way to disable this annoyance.

**Comment by LaravelNick** [comment]
Wish there was some way to disable this annoyance.

**Comment by daftspunk** [comment]
This should be resolved when we implemented Froala editor recently. This issue should have been closed as part of that. If Froala is still causing issues, then we need to log a new one with replication instructions.

Fixed by https://github.com/octobercms/october/issues/2005
