### ISSUE TITLE
Need to add a custom field in static page form

### ISSUE THREAD

**Issue by sunilcse24** [rainlab/pages-plugin#75]
How to add a custom field like 'published' button in a static page?
##

**Comment by felixinx** [comment]
Hi,

Take a look at [custom page fields](https://github.com/rainlab/pages-plugin#custom-page-fields) and [building client-friendly website](https://vimeo.com/132426322).

I don't think that you can put a button, but you can put input.

**Comment by sunilcse24** [comment]
Can we able to add a custom dropdown field on the static page?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
