### ISSUE TITLE
Image Insertion and snippet inclusion in RichTextEditor is not working consistently

### ISSUE THREAD

**Issue by sunilcse24** [rainlab/pages-plugin#79]
I have to insert an Image and snippet in RichTextEditor which is not working consistently.

Please help me to fix this asap.

Note :
This issue occurs in Firefox and Chrome browsers.
##

![imgup](https://cloud.githubusercontent.com/assets/6761717/9954476/fd5eebb2-5e06-11e5-8f52-92b888c80b8c.jpg)
##

**Comment by sunilcse24** [comment]
![wysiwyg](https://cloud.githubusercontent.com/assets/6761717/10038812/93e44d72-61e8-11e5-821b-505c7d4758be.jpg)

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
