### ISSUE TITLE
Incomplete documentation on Syntax fields

### ISSUE THREAD

**Issue by CptMeatball** [rainlab/pages-plugin#80]
Syntax fields are awesome! But I can't figure out how to use the repeater type. There is only limited documentation present in the read me and documentation of the plugin itself.

I can get the repeater to show, but I can't get any fields in the repeater.

**Comment by daftspunk** [comment]
The repeater type isn't supported yet

**Comment by CptMeatball** [comment]
Ah well. Tough luck for me. Can you tell me what types are supported?

**Comment by FelixINX** [comment]
I'm not sure - but the documentation is incomplete.
What I know:

- `text`
- `mediafinder`

I want to trace where it come from, for debbuging.

**Comment by daftspunk** [comment]
Great! Thanks! I will add these to the documentation. We are working on adding support for the repeater with our recently added ["October flavoured INI" syntax](https://github.com/octobercms/library/blob/master/src/Parse/Ini.php).

**Comment by daftspunk** [comment]
This should be documented now.
