### ISSUE TITLE
How to create responsive image in wysiwyg editor?

### ISSUE THREAD

**Issue by faniislahul** [rainlab/pages-plugin#86]
I wonder how to create responsive image from media in wysiwyg editor. Anyone have idea?
##

**Comment by hybridvision** [comment]
Can you explain a bit more what you mean by a "responsive image"? Usually this is something handled by CSS and/or JS so it's not clear what you're trying to achieve inside the editor...

**Comment by jonpxpx** [comment]
You could use CSS to do this:
```
img {
    max-width: 100%;
    height: auto;
}
```
As the most basic example possible

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
