### ISSUE TITLE
Large images added to image fields fill entire backend page

### ISSUE THREAD

**Issue by jwilson8767** [rainlab/pages-plugin#88]
Uploading a large image to an image field forces the editor off the bottom of the screen and the image overflows the right side of the screen. (see images for example). I suggest displaying a thumbnail view instead of the full size image.
![image](https://cloud.githubusercontent.com/assets/10873576/10290996/5ada8410-6b75-11e5-86a4-797288a6fdad.png)
![image](https://cloud.githubusercontent.com/assets/10873576/10291004/66a74c2e-6b75-11e5-9aed-15dcc6914695.png)
##

**Comment by gavinfostered** [comment]
+1

**Comment by Kunilt** [comment]
+1

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
