### ISSUE TITLE
Can't add Static Pages component to a Layout file

### ISSUE THREAD

**Issue by stevecrossuk** [rainlab/pages-plugin#89]
I have downloaded the most recent version of OctoberCMS today (06/10/15) and then added Rainlab Pages to it. Tried this on a variety of different server setups that I know already work with your plugin and October CMS.

When you go to CMS, Layouts, add a new Layout and then drag the Components > Static Pages, and then choose Save..and then close the file, it doesn't save the link. It works ok for static menus (it saves those), just not static pages.

I found an early working version of the plugin and an older working version of OctoberCMS and installed these onto the same servers and it worked ok.

Please let me know when the issue is fixed and I can use the latest versions.

**Comment by alekseybobkov** [comment]
Fixed in Build 303 :-)
