### ISSUE TITLE
How to manage content with 2 columns layout ?

### ISSUE THREAD

**Issue by tplessis** [rainlab/pages-plugin#90]
Hi guys,

I've a two columns content layout and i would like to manage content of these two columns separately, with 2 differents WYSIWIG editors. I don't want to put all of the content with the 2 columns directly in only one static page, there's a lot of chance my client will break all the things...

Is it possible to do that with the actual version of the static page plugin ? Or what is the best way to do that ?

Regards,
##

**Comment by hybridvision** [comment]
Hello,

Placeholders are what you're after - put them in your parent layout and the pages plugin will display a separate editor for each layout in its own tab. It's very neat. See here: https://octobercms.com/blog/post/static-pages-content-blocks-and-placeholders

**Comment by that0n3guy** [comment]
As of 1.2.6, I think variables can also be used for this.

**Comment by LukeTowers** [comment]
@that0n3guy is correct.
