### ISSUE TITLE
add class to menu UL element

### ISSUE THREAD

**Issue by donaldej** [rainlab/pages-plugin#94]
Hello,

I created a fork of this plugin and added a new field to the menu creation view. The problem I am having now is injecting it into the _SELF_ object to make accessible to the menu templates. Would you mind pointing me in the right direction? In the StaticMenu.php file I have been poking around where it creates the menuItems reference, but I cant seem to get this right.

**Comment by oostmeijer** [comment]
Hi, 

can't this be a feature request for the next update?

**Comment by donaldej** [comment]
I should close this. I already added it in my fork.

Thanks,
Donnie Jones

Date: Mon, 19 Oct 2015 05:37:03 -0700

**Comment by oostmeijer** [comment]
Hi Donnie,

how does this work? Will your fork commit be incorporated in the main plugin?

regards,

Jelle

**Comment by donaldej** [comment]
It works well. It just added a cssClass field to the menu itself (so the ul class can not have a class). I created a pull request.

**Comment by donaldej** [comment]
Closing because I added the feature. Created a fork of it.
