### ISSUE TITLE
StaticMenu: Class field for UL element / dropdown of subitems

### ISSUE THREAD

**Issue by oostmeijer** [rainlab/pages-plugin#98]
Hi,

I was trying to add custom classes to the ul elements of the static menu component. [donaldej](https://github.com/donaldej) created a feature to add classes to the menu ul element with pull [#96](https://github.com/rainlab/pages-plugin/pull/96).

I was trying to modify the menu item to have a similar cssMenuClass attribute to be set for the dropdown ul elements in a menu. I've managed to implement this for the MenuItem by adding an extra ViewBag attribute. However this is then displayed for all menuitems (also the ones which don't have children / subitems).
I can't figure out how to hide this field for menuitems which don't have children / subitems. Can someone suggest me how to implement this?

Regards
##

**Comment by donaldej** [comment]
Did you end up using this? Notice any issues so far?

**Comment by xNok** [comment]
It could be great to add this feature to personalise the ul.
Don't forget that this pluggins has been made for non developers.

For instance navs :
```html
<ul class="nav nav-pills">
  <li role="presentation" class="active"><a href="#">Home</a></li>
  <li role="presentation"><a href="#">Profile</a></li>
  <li role="presentation"><a href="#">Messages</a></li>
</ul>
```
Dropdown Menu
```html
<ul>
    <li>
        <a href="http://example.com">Home</a>
    </li>
    <li class="child-active">
        <a href="http://example.com/about">About</a>
        <u class="dropdown-menu">
            <li class="active">
                <a href="http://example.com/about/directions">Directions</a>
            </li>
        </ul>
    </li>
</ul>
```
One simple solution might be adding an attributes tab to personnalize the menu & an attribute to morph througt a dropdown button

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
