### ISSUE TITLE
Adding subpage adds page to root instead of intended folder

### ISSUE THREAD

**Issue by gavinworks** [rainlab/pages-plugin#99]
After updating to the latest release choosing "Add subpage" adds the page as normal but adds it to the root of the document tree in the pages list instead of the intended parent.

Replicate:
1. Pages > Add Subpage.
2. Choose a different layout to the one already selected.
3. Save page.

Selected layout in my case has an media finder variable called headerimage which may help debugging/replicating.

**Comment by gavinfostered** [comment]
Update: This only happens if you choose a different layout then the one selected on the "New Page" screen. If you stick with the layout selected, works as expected.

**Comment by voveson** [comment]
Any update on this issue?

**Comment by daftspunk** [comment]
Fixed by 8a9d76873a8322fdc3bd61e914989f4805e91f48 available in 1.2.5
